// ===== MASSIVE PHRASES DATABASE =====
const phrasesData = {
    greetings: [
        { english: "Hello, how are you?", portuguese: "Olá, como você está?" },
        { english: "Nice to meet you!", portuguese: "Prazer em conhecê-lo!" },
        { english: "How's it going?", portuguese: "Como vão as coisas?" },
        { english: "Long time no see!", portuguese: "Há quanto tempo!" },
        { english: "What's up?", portuguese: "E aí?" },
        { english: "I'm doing great, thanks!", portuguese: "Estou muito bem, obrigado!" },
        { english: "See you later!", portuguese: "Até mais!" },
        { english: "Take care!", portuguese: "Se cuide!" },
        { english: "Have a nice day!", portuguese: "Tenha um bom dia!" },
        { english: "It was nice talking to you.", portuguese: "Foi bom conversar com você." },
        { english: "Good to see you again!", portuguese: "Bom ver você de novo!" },
        { english: "How have you been?", portuguese: "Como você tem estado?" },
        { english: "I'm pleased to meet you.", portuguese: "É um prazer conhecê-lo." },
        { english: "What have you been up to?", portuguese: "O que você tem feito?" },
        { english: "See you tomorrow!", portuguese: "Vejo você amanhã!" },
        { english: "Catch you later!", portuguese: "Até mais tarde!" },
        { english: "Stay in touch!", portuguese: "Mantenha contato!" },
        { english: "It's been a while!", portuguese: "Faz um tempo!" },
        { english: "How's everything?", portuguese: "Como está tudo?" },
        { english: "I hope you're doing well.", portuguese: "Espero que esteja bem." }
    ],
    restaurant: [
        { english: "A table for two, please.", portuguese: "Uma mesa para duas pessoas, por favor." },
        { english: "Can I see the menu?", portuguese: "Posso ver o cardápio?" },
        { english: "What do you recommend?", portuguese: "O que você recomenda?" },
        { english: "I'd like to order...", portuguese: "Eu gostaria de pedir..." },
        { english: "Could I have the bill, please?", portuguese: "Pode trazer a conta, por favor?" },
        { english: "Is tip included?", portuguese: "A gorjeta está incluída?" },
        { english: "This is delicious!", portuguese: "Isso está delicioso!" },
        { english: "I'm allergic to...", portuguese: "Sou alérgico a..." },
        { english: "Can I pay by card?", portuguese: "Posso pagar com cartão?" },
        { english: "Keep the change.", portuguese: "Fique com o troco." },
        { english: "I'll have the same.", portuguese: "Vou querer o mesmo." },
        { english: "Is this dish spicy?", portuguese: "Este prato é apimentado?" },
        { english: "Could I have some water?", portuguese: "Poderia trazer água?" },
        { english: "I'm a vegetarian.", portuguese: "Sou vegetariano." },
        { english: "Do you have any specials today?", portuguese: "Vocês têm promoções hoje?" },
        { english: "The food was amazing.", portuguese: "A comida estava incrível." },
        { english: "Can I get this to go?", portuguese: "Posso levar isso para viagem?" },
        { english: "I'd like a refill, please.", portuguese: "Gostaria de mais uma dose, por favor." },
        { english: "Do you have gluten-free options?", portuguese: "Vocês têm opções sem glúten?" },
        { english: "Could you bring some napkins?", portuguese: "Poderia trazer alguns guardanapos?" }
    ],
    shopping: [
        { english: "How much does this cost?", portuguese: "Quanto custa isso?" },
        { english: "Do you have this in a different size?", portuguese: "Você tem isso em outro tamanho?" },
        { english: "Can I try this on?", portuguese: "Posso experimentar isso?" },
        { english: "Where is the fitting room?", portuguese: "Onde fica o provador?" },
        { english: "I'm just looking, thanks.", portuguese: "Só estou olhando, obrigado." },
        { english: "Do you accept credit cards?", portuguese: "Vocês aceitam cartão de crédito?" },
        { english: "Is there a discount?", portuguese: "Há algum desconto?" },
        { english: "Can I return this?", portuguese: "Posso devolver isso?" },
        { english: "Do you have this in another color?", portuguese: "Você tem isso em outra cor?" },
        { english: "I'll take it!", portuguese: "Vou levar!" },
        { english: "It's too expensive.", portuguese: "É muito caro." },
        { english: "Do you have something cheaper?", portuguese: "Você tem algo mais barato?" },
        { english: "This doesn't fit me.", portuguese: "Isso não serve em mim." },
        { english: "I need a larger size.", portuguese: "Preciso de um tamanho maior." },
        { english: "I need a smaller size.", portuguese: "Preciso de um tamanho menor." },
        { english: "Is this on sale?", portuguese: "Isso está em promoção?" },
        { english: "Where can I find the shoes?", portuguese: "Onde posso encontrar os sapatos?" },
        { english: "I'm looking for a gift.", portuguese: "Estou procurando um presente." },
        { english: "Can you gift wrap this?", portuguese: "Você pode embalar para presente?" },
        { english: "Do you have a receipt?", portuguese: "Você tem o recibo?" }
    ],
    travel: [
        { english: "Where is the nearest hotel?", portuguese: "Onde fica o hotel mais próximo?" },
        { english: "How do I get to the airport?", portuguese: "Como chego ao aeroporto?" },
        { english: "I have a reservation.", portuguese: "Tenho uma reserva." },
        { english: "What time is check-in?", portuguese: "Que horas é o check-in?" },
        { english: "Is breakfast included?", portuguese: "O café da manhã está incluído?" },
        { english: "I need a taxi.", portuguese: "Preciso de um táxi." },
        { english: "How far is it?", portuguese: "Qual é a distância?" },
        { english: "Can you show me on the map?", portuguese: "Pode me mostrar no mapa?" },
        { english: "I'm lost.", portuguese: "Estou perdido." },
        { english: "Where is the bus station?", portuguese: "Onde fica a rodoviária?" },
        { english: "What's the Wi-Fi password?", portuguese: "Qual é a senha do Wi-Fi?" },
        { english: "Is there a pool?", portuguese: "Tem piscina?" },
        { english: "Could I have a late checkout?", portuguese: "Posso fazer check-out mais tarde?" },
        { english: "The room is not clean.", portuguese: "O quarto não está limpo." },
        { english: "I'd like to extend my stay.", portuguese: "Gostaria de estender minha estadia." },
        { english: "Where can I exchange money?", portuguese: "Onde posso trocar dinheiro?" },
        { english: "Is there a train to the city center?", portuguese: "Tem trem para o centro da cidade?" },
        { english: "How long does the trip take?", portuguese: "Quanto tempo leva a viagem?" },
        { english: "Where is the boarding gate?", portuguese: "Onde fica o portão de embarque?" },
        { english: "My flight has been delayed.", portuguese: "Meu voo foi atrasado." }
    ],
    work: [
        { english: "I have a meeting at 10.", portuguese: "Tenho uma reunião às 10." },
        { english: "Can you send me the report?", portuguese: "Pode me enviar o relatório?" },
        { english: "When is the deadline?", portuguese: "Qual é o prazo?" },
        { english: "I need more time.", portuguese: "Preciso de mais tempo." },
        { english: "Let's schedule a call.", portuguese: "Vamos agendar uma ligação." },
        { english: "I'll get back to you.", portuguese: "Eu retorno para você." },
        { english: "What's the priority?", portuguese: "Qual é a prioridade?" },
        { english: "Can we discuss this later?", portuguese: "Podemos discutir isso depois?" },
        { english: "I'm working on it.", portuguese: "Estou trabalhando nisso." },
        { english: "Consider it done.", portuguese: "Considere feito." },
        { english: "Let me check my calendar.", portuguese: "Deixe-me verificar minha agenda." },
        { english: "I'll be out of the office.", portuguese: "Estarei fora do escritório." },
        { english: "Please forward me the email.", portuguese: "Por favor, encaminhe o email para mim." },
        { english: "I appreciate your help.", portuguese: "Agradeço sua ajuda." },
        { english: "Keep me updated.", portuguese: "Me mantenha atualizado." },
        { english: "Let's touch base next week.", portuguese: "Vamos nos falar na próxima semana." },
        { english: "That's not my department.", portuguese: "Isso não é do meu departamento." },
        { english: "I'll handle it.", portuguese: "Eu cuido disso." },
        { english: "Can you clarify that?", portuguese: "Você pode esclarecer isso?" },
        { english: "I have a conflict at that time.", portuguese: "Tenho um conflito nesse horário." }
    ],
    emergency: [
        { english: "Help!", portuguese: "Socorro!" },
        { english: "Call an ambulance!", portuguese: "Chame uma ambulância!" },
        { english: "I need a doctor.", portuguese: "Preciso de um médico." },
        { english: "Where is the hospital?", portuguese: "Onde fica o hospital?" },
        { english: "It's an emergency!", portuguese: "É uma emergência!" },
        { english: "I don't feel well.", portuguese: "Não estou me sentindo bem." },
        { english: "Call the police!", portuguese: "Chame a polícia!" },
        { english: "I lost my passport.", portuguese: "Perdi meu passaporte." },
        { english: "I've been robbed.", portuguese: "Fui roubado." },
        { english: "Is there a pharmacy nearby?", portuguese: "Tem uma farmácia por perto?" },
        { english: "I'm having chest pain.", portuguese: "Estou com dor no peito." },
        { english: "I need help immediately.", portuguese: "Preciso de ajuda imediatamente." },
        { english: "There's been an accident.", portuguese: "Houve um acidente." },
        { english: "I can't breathe properly.", portuguese: "Não consigo respirar direito." },
        { english: "My wallet was stolen.", portuguese: "Minha carteira foi roubada." },
        { english: "I need to contact my embassy.", portuguese: "Preciso contatar minha embaixada." },
        { english: "I'm allergic to this medication.", portuguese: "Sou alérgico a este medicamento." },
        { english: "Someone is following me.", portuguese: "Alguém está me seguindo." },
        { english: "I need a lawyer.", portuguese: "Preciso de um advogado." },
        { english: "Please take me to the hospital.", portuguese: "Por favor, me leve ao hospital." }
    ],
    smalltalk: [
        { english: "What do you do for a living?", portuguese: "O que você faz da vida?" },
        { english: "Where are you from?", portuguese: "De onde você é?" },
        { english: "How long have you been here?", portuguese: "Há quanto tempo você está aqui?" },
        { english: "What are your hobbies?", portuguese: "Quais são seus hobbies?" },
        { english: "Do you like traveling?", portuguese: "Você gosta de viajar?" },
        { english: "What kind of music do you like?", portuguese: "Que tipo de música você gosta?" },
        { english: "Have you seen any good movies lately?", portuguese: "Viu algum filme bom ultimamente?" },
        { english: "What's your favorite food?", portuguese: "Qual sua comida favorita?" },
        { english: "The weather is nice today.", portuguese: "O tempo está bom hoje." },
        { english: "Do you have any plans for the weekend?", portuguese: "Tem planos para o fim de semana?" },
        { english: "Do you have any siblings?", portuguese: "Você tem irmãos?" },
        { english: "What do you think about...?", portuguese: "O que você acha de...?" },
        { english: "That's interesting!", portuguese: "Isso é interessante!" },
        { english: "I totally agree with you.", portuguese: "Concordo totalmente com você." },
        { english: "Really? Tell me more.", portuguese: "Sério? Me conte mais." },
        { english: "How was your day?", portuguese: "Como foi seu dia?" },
        { english: "Did you have a good weekend?", portuguese: "Teve um bom fim de semana?" },
        { english: "What are you doing after this?", portuguese: "O que você vai fazer depois?" },
        { english: "It's nice out, isn't it?", portuguese: "Está agradável lá fora, não é?" },
        { english: "Have you ever been to...?", portuguese: "Você já foi para...?" }
    ],
    feelings: [
        { english: "I'm so happy!", portuguese: "Estou tão feliz!" },
        { english: "I feel tired.", portuguese: "Estou me sentindo cansado." },
        { english: "I'm excited about this!", portuguese: "Estou empolgado com isso!" },
        { english: "I'm a bit nervous.", portuguese: "Estou um pouco nervoso." },
        { english: "I'm worried about...", portuguese: "Estou preocupado com..." },
        { english: "I'm grateful for your help.", portuguese: "Sou grato pela sua ajuda." },
        { english: "I miss you.", portuguese: "Sinto sua falta." },
        { english: "I'm proud of you!", portuguese: "Estou orgulhoso de você!" },
        { english: "I'm sorry to hear that.", portuguese: "Sinto muito em ouvir isso." },
        { english: "I love you.", portuguese: "Eu te amo." },
        { english: "I'm feeling overwhelmed.", portuguese: "Estou me sentindo sobrecarregado." },
        { english: "That makes me so angry.", portuguese: "Isso me deixa com tanta raiva." },
        { english: "I feel so relieved.", portuguese: "Me sinto tão aliviado." },
        { english: "I'm disappointed.", portuguese: "Estou desapontado." },
        { english: "I'm confused about this.", portuguese: "Estou confuso sobre isso." },
        { english: "I feel motivated!", portuguese: "Me sinto motivado!" },
        { english: "I'm stressed out.", portuguese: "Estou muito estressado." },
        { english: "I feel peaceful.", portuguese: "Me sinto em paz." },
        { english: "I'm frustrated with this.", portuguese: "Estou frustrado com isso." },
        { english: "I feel appreciated.", portuguese: "Me sinto valorizado." }
    ],
    opinions: [
        { english: "I think that's a great idea.", portuguese: "Acho que é uma ótima ideia." },
        { english: "In my opinion...", portuguese: "Na minha opinião..." },
        { english: "I strongly believe that...", portuguese: "Acredito firmemente que..." },
        { english: "I don't really agree.", portuguese: "Não concordo muito." },
        { english: "From my point of view...", portuguese: "Do meu ponto de vista..." },
        { english: "That's exactly what I think!", portuguese: "É exatamente o que eu penso!" },
        { english: "I'm not sure about that.", portuguese: "Não tenho certeza disso." },
        { english: "I see your point, but...", portuguese: "Entendo seu ponto, mas..." },
        { english: "That's a good point.", portuguese: "Esse é um bom ponto." },
        { english: "I completely disagree.", portuguese: "Discordo completamente." },
        { english: "I couldn't agree more.", portuguese: "Não poderia concordar mais." },
        { english: "Let me think about it.", portuguese: "Deixe-me pensar sobre isso." },
        { english: "That's an interesting perspective.", portuguese: "Essa é uma perspectiva interessante." },
        { english: "I have mixed feelings about this.", portuguese: "Tenho sentimentos mistos sobre isso." },
        { english: "As far as I'm concerned...", portuguese: "No que me diz respeito..." }
    ],
    technology: [
        { english: "My phone is not working.", portuguese: "Meu celular não está funcionando." },
        { english: "Can you send me your number?", portuguese: "Pode me enviar seu número?" },
        { english: "I'll text you later.", portuguese: "Te mando mensagem depois." },
        { english: "The internet is slow.", portuguese: "A internet está lenta." },
        { english: "Let me add you on social media.", portuguese: "Deixa eu te adicionar nas redes sociais." },
        { english: "Did you see my post?", portuguese: "Viu minha postagem?" },
        { english: "I need to charge my phone.", portuguese: "Preciso carregar meu celular." },
        { english: "The app keeps crashing.", portuguese: "O app fica travando." },
        { english: "Can you screenshot that?", portuguese: "Pode tirar print disso?" },
        { english: "I'll video call you.", portuguese: "Vou te ligar por vídeo." },
        { english: "My password doesn't work.", portuguese: "Minha senha não funciona." },
        { english: "I need to update the software.", portuguese: "Preciso atualizar o software." },
        { english: "The file is too large.", portuguese: "O arquivo é muito grande." },
        { english: "Can you share your screen?", portuguese: "Pode compartilhar sua tela?" },
        { english: "I'll forward you the link.", portuguese: "Vou te encaminhar o link." }
    ]
};

// ===== LEVEL ASSESSMENT TEST =====
const assessmentQuestions = [
    // Level 1: Beginner (Questions 1-10)
    { question: "What is 'Hello' in Portuguese?", options: ["Olá", "Tchau", "Obrigado", "Por favor"], correct: 0, level: 1 },
    { question: "How do you say 'Thank you'?", options: ["Sorry", "Please", "Thank you", "Goodbye"], correct: 2, level: 1 },
    { question: "Complete: 'Good ___' (morning greeting)", options: ["night", "morning", "bye", "luck"], correct: 1, level: 1 },
    { question: "What color is 'azul' in English?", options: ["Red", "Green", "Blue", "Yellow"], correct: 2, level: 1 },
    { question: "How do you say 'água' in English?", options: ["Food", "Water", "Milk", "Juice"], correct: 1, level: 1 },
    { question: "What is 'three' in Portuguese?", options: ["Um", "Dois", "Três", "Quatro"], correct: 2, level: 1 },
    { question: "Complete: 'I ___ hungry' (to be)", options: ["is", "am", "are", "be"], correct: 1, level: 1 },
    { question: "What is 'mãe' in English?", options: ["Father", "Brother", "Sister", "Mother"], correct: 3, level: 1 },
    { question: "How do you say 'casa' in English?", options: ["Car", "House", "School", "Hospital"], correct: 1, level: 1 },
    { question: "What is the opposite of 'big'?", options: ["Large", "Heavy", "Small", "Tall"], correct: 2, level: 1 },

    // Level 2: Elementary (Questions 11-20)
    { question: "Complete: 'She ___ to school every day'", options: ["go", "goes", "going", "gone"], correct: 1, level: 2 },
    { question: "What does 'I'm looking for' mean?", options: ["Estou olhando", "Estou procurando", "Estou achando", "Estou vendo"], correct: 1, level: 2 },
    { question: "Choose the correct sentence:", options: ["He don't like coffee", "He doesn't like coffee", "He not like coffee", "He no like coffee"], correct: 1, level: 2 },
    { question: "What is 'yesterday' in Portuguese?", options: ["Amanhã", "Hoje", "Ontem", "Agora"], correct: 2, level: 2 },
    { question: "Complete: 'I ___ TV right now'", options: ["watch", "watches", "am watching", "watched"], correct: 2, level: 2 },
    { question: "What does 'expensive' mean?", options: ["Barato", "Caro", "Bonito", "Feio"], correct: 1, level: 2 },
    { question: "Choose: 'There ___ many people here'", options: ["is", "are", "am", "be"], correct: 1, level: 2 },
    { question: "What is 'sometimes' in Portuguese?", options: ["Sempre", "Nunca", "Às vezes", "Raramente"], correct: 2, level: 2 },
    { question: "Complete: 'I have ___ been to London'", options: ["ever", "never", "always", "still"], correct: 1, level: 2 },
    { question: "What does 'appointment' mean?", options: ["Apartamento", "Compromisso", "Pagamento", "Departamento"], correct: 1, level: 2 },

    // Level 3: Pre-Intermediate (Questions 21-30)
    { question: "What does 'give up' mean?", options: ["Devolver", "Desistir", "Doar", "Subir"], correct: 1, level: 3 },
    { question: "Complete: 'If I ___ rich, I would travel'", options: ["am", "was", "were", "be"], correct: 2, level: 3 },
    { question: "What is 'although' in Portuguese?", options: ["Portanto", "Embora", "Porque", "Porém"], correct: 1, level: 3 },
    { question: "Choose the correct form: 'The book ___ by many people'", options: ["was read", "read", "is read", "reading"], correct: 0, level: 3 },
    { question: "What does 'figure out' mean?", options: ["Desenhar", "Descobrir", "Imaginar", "Figurar"], correct: 1, level: 3 },
    { question: "Complete: 'I wish I ___ speak French'", options: ["can", "could", "will", "would"], correct: 1, level: 3 },
    { question: "What is 'deadline' in Portuguese?", options: ["Linha morta", "Prazo", "Final", "Meta"], correct: 1, level: 3 },
    { question: "Choose: 'He's been working here ___ 2019'", options: ["for", "since", "from", "during"], correct: 1, level: 3 },
    { question: "What does 'however' mean?", options: ["Como", "No entanto", "Porém", "Contudo"], correct: 1, level: 3 },
    { question: "'Run out of' means:", options: ["Correr para fora", "Esgotar/Acabar", "Fugir de", "Correr de"], correct: 1, level: 3 },

    // Level 4: Intermediate (Questions 31-40)
    { question: "What does 'piece of cake' mean?", options: ["Pedaço de bolo", "Muito fácil", "Muito bom", "Muito caro"], correct: 1, level: 4 },
    { question: "Complete: 'He ___ have left already'", options: ["must", "can", "should", "would"], correct: 0, level: 4 },
    { question: "What does 'break a leg' mean?", options: ["Quebrar a perna", "Ter cuidado", "Boa sorte", "Correr rápido"], correct: 2, level: 4 },
    { question: "'Under the weather' means:", options: ["Debaixo do tempo", "Indisposto/Doente", "Na chuva", "Frio"], correct: 1, level: 4 },
    { question: "Complete: 'Had I known, I ___ helped'", options: ["would have", "will have", "have", "had"], correct: 0, level: 4 },
    { question: "What does 'stakeholder' mean?", options: ["Acionista", "Parte interessada", "Titular", "Funcionário"], correct: 1, level: 4 },
    { question: "'Get out of hand' means:", options: ["Tirar da mão", "Sair do controle", "Pegar algo", "Desistir"], correct: 1, level: 4 },
    { question: "What is 'leverage' in business?", options: ["Alavanca", "Alavancar/Usar a favor", "Levantar", "Elevar"], correct: 1, level: 4 },
    { question: "'Notwithstanding' means:", options: ["Não obstante", "Sem resistir", "Não entendendo", "Com tudo"], correct: 0, level: 4 },
    { question: "What does 'hit the nail on the head' mean?", options: ["Martelar", "Acertar em cheio", "Ter sorte", "Trabalhar duro"], correct: 1, level: 4 },

    // Level 5: Upper-Intermediate (Questions 41-50)
    { question: "What does 'pursuant to' mean?", options: ["Perseguindo", "Conforme/De acordo com", "Através de", "Apesar de"], correct: 1, level: 5 },
    { question: "'A dime a dozen' means:", options: ["Muito caro", "Muito raro", "Muito comum/Barato", "Muito bom"], correct: 2, level: 5 },
    { question: "What is 'scalability' in Portuguese?", options: ["Escala", "Escalabilidade", "Escalada", "Escalar"], correct: 1, level: 5 },
    { question: "'Bend over backwards' means:", options: ["Curvar-se", "Fazer de tudo para ajudar", "Voltar atrás", "Exercitar-se"], correct: 1, level: 5 },
    { question: "What does 'henceforth' mean?", options: ["Por aqui", "De agora em diante", "Por conseguinte", "Entretanto"], correct: 1, level: 5 },
    { question: "'Through thick and thin' means:", options: ["Através de tudo", "Em qualquer situação", "Fino e grosso", "Rapidamente"], correct: 1, level: 5 },
    { question: "What is 'ROI' short for?", options: ["Return On Investment", "Rate Of Interest", "Range Of Impact", "Result Of Input"], correct: 0, level: 5 },
    { question: "'Let the cat out of the bag' means:", options: ["Soltar o gato", "Revelar um segredo", "Deixar escapar", "Libertar"], correct: 1, level: 5 },
    { question: "What does 'bottleneck' mean in business?", options: ["Gargalo de garrafa", "Gargalo/Obstáculo", "Engarrafamento", "Problema"], correct: 1, level: 5 },
    { question: "'When pigs fly' means:", options: ["Quando porcos voam", "Nunca", "Em breve", "Talvez"], correct: 1, level: 5 }
];

// ===== GRAMMAR LESSONS =====
const grammarLessons = {
    beginner: [
        { title: "Verb TO BE", content: "I am, You are, He/She/It is, We are, They are", examples: ["I am happy", "She is a teacher", "They are friends"] },
        { title: "Simple Present", content: "Used for habits and facts. Add -s/-es for he/she/it", examples: ["I work every day", "She works at home", "They study English"] },
        { title: "Articles A/AN/THE", content: "A before consonants, AN before vowels, THE for specific things", examples: ["A book", "An apple", "The sun"] },
        { title: "Plural Nouns", content: "Add -s or -es to make plurals", examples: ["book → books", "box → boxes", "baby → babies"] },
        { title: "Possessive Adjectives", content: "My, Your, His, Her, Its, Our, Their", examples: ["My car", "Her house", "Their children"] }
    ],
    intermediate: [
        { title: "Present Perfect", content: "Have/Has + Past Participle. For experiences and unfinished time", examples: ["I have visited Paris", "She has lived here for 5 years", "They have just arrived"] },
        { title: "Past Continuous", content: "Was/Were + Verb-ing. For actions in progress in the past", examples: ["I was sleeping when you called", "They were working all day"] },
        { title: "Conditionals", content: "If + condition, result. Zero, First, Second, Third", examples: ["If it rains, I stay home (Zero)", "If I win, I will celebrate (First)", "If I were rich, I would travel (Second)"] },
        { title: "Passive Voice", content: "Object becomes subject. To be + Past Participle", examples: ["The book was written by him", "English is spoken here", "The cake was made by my mom"] },
        { title: "Reported Speech", content: "Reporting what someone said. Changes in tense and pronouns", examples: ["He said he was tired", "She told me she would come", "They asked if I was ready"] }
    ],
    advanced: [
        { title: "Inversion", content: "Inverting subject and verb for emphasis", examples: ["Never have I seen such beauty", "Rarely does he make mistakes", "Not only did she win, but also set a record"] },
        { title: "Subjunctive", content: "Expressing wishes, demands, suggestions", examples: ["I wish I were there", "It's important that he be on time", "I suggest that she take the offer"] },
        { title: "Cleft Sentences", content: "It is/was... that/who for emphasis", examples: ["It was John who called", "It's the money that I need", "What I want is peace"] },
        { title: "Mixed Conditionals", content: "Mixing time references in conditionals", examples: ["If I had studied, I would be successful now", "If she were smarter, she would have passed"] },
        { title: "Advanced Modals", content: "Must have, Could have, Should have + Past Participle", examples: ["He must have forgotten", "She could have called", "They should have tried harder"] }
    ]
};

// ===== IRREGULAR VERBS =====
const irregularVerbs = [
    { base: "be", past: "was/were", participle: "been", translation: "ser/estar" },
    { base: "become", past: "became", participle: "become", translation: "tornar-se" },
    { base: "begin", past: "began", participle: "begun", translation: "começar" },
    { base: "break", past: "broke", participle: "broken", translation: "quebrar" },
    { base: "bring", past: "brought", participle: "brought", translation: "trazer" },
    { base: "build", past: "built", participle: "built", translation: "construir" },
    { base: "buy", past: "bought", participle: "bought", translation: "comprar" },
    { base: "catch", past: "caught", participle: "caught", translation: "pegar" },
    { base: "choose", past: "chose", participle: "chosen", translation: "escolher" },
    { base: "come", past: "came", participle: "come", translation: "vir" },
    { base: "cost", past: "cost", participle: "cost", translation: "custar" },
    { base: "cut", past: "cut", participle: "cut", translation: "cortar" },
    { base: "do", past: "did", participle: "done", translation: "fazer" },
    { base: "draw", past: "drew", participle: "drawn", translation: "desenhar" },
    { base: "drink", past: "drank", participle: "drunk", translation: "beber" },
    { base: "drive", past: "drove", participle: "driven", translation: "dirigir" },
    { base: "eat", past: "ate", participle: "eaten", translation: "comer" },
    { base: "fall", past: "fell", participle: "fallen", translation: "cair" },
    { base: "feel", past: "felt", participle: "felt", translation: "sentir" },
    { base: "find", past: "found", participle: "found", translation: "encontrar" },
    { base: "fly", past: "flew", participle: "flown", translation: "voar" },
    { base: "forget", past: "forgot", participle: "forgotten", translation: "esquecer" },
    { base: "get", past: "got", participle: "got/gotten", translation: "obter" },
    { base: "give", past: "gave", participle: "given", translation: "dar" },
    { base: "go", past: "went", participle: "gone", translation: "ir" },
    { base: "grow", past: "grew", participle: "grown", translation: "crescer" },
    { base: "have", past: "had", participle: "had", translation: "ter" },
    { base: "hear", past: "heard", participle: "heard", translation: "ouvir" },
    { base: "hide", past: "hid", participle: "hidden", translation: "esconder" },
    { base: "hit", past: "hit", participle: "hit", translation: "bater" },
    { base: "hold", past: "held", participle: "held", translation: "segurar" },
    { base: "hurt", past: "hurt", participle: "hurt", translation: "machucar" },
    { base: "keep", past: "kept", participle: "kept", translation: "manter" },
    { base: "know", past: "knew", participle: "known", translation: "saber" },
    { base: "lead", past: "led", participle: "led", translation: "liderar" },
    { base: "learn", past: "learnt/learned", participle: "learnt/learned", translation: "aprender" },
    { base: "leave", past: "left", participle: "left", translation: "sair/deixar" },
    { base: "lend", past: "lent", participle: "lent", translation: "emprestar" },
    { base: "let", past: "let", participle: "let", translation: "deixar" },
    { base: "lose", past: "lost", participle: "lost", translation: "perder" },
    { base: "make", past: "made", participle: "made", translation: "fazer" },
    { base: "mean", past: "meant", participle: "meant", translation: "significar" },
    { base: "meet", past: "met", participle: "met", translation: "encontrar" },
    { base: "pay", past: "paid", participle: "paid", translation: "pagar" },
    { base: "put", past: "put", participle: "put", translation: "colocar" },
    { base: "read", past: "read", participle: "read", translation: "ler" },
    { base: "ride", past: "rode", participle: "ridden", translation: "andar" },
    { base: "ring", past: "rang", participle: "rung", translation: "tocar" },
    { base: "rise", past: "rose", participle: "risen", translation: "subir" },
    { base: "run", past: "ran", participle: "run", translation: "correr" },
    { base: "say", past: "said", participle: "said", translation: "dizer" },
    { base: "see", past: "saw", participle: "seen", translation: "ver" },
    { base: "sell", past: "sold", participle: "sold", translation: "vender" },
    { base: "send", past: "sent", participle: "sent", translation: "enviar" },
    { base: "set", past: "set", participle: "set", translation: "definir" },
    { base: "shake", past: "shook", participle: "shaken", translation: "sacudir" },
    { base: "shine", past: "shone", participle: "shone", translation: "brilhar" },
    { base: "show", past: "showed", participle: "shown", translation: "mostrar" },
    { base: "shut", past: "shut", participle: "shut", translation: "fechar" },
    { base: "sing", past: "sang", participle: "sung", translation: "cantar" },
    { base: "sit", past: "sat", participle: "sat", translation: "sentar" },
    { base: "sleep", past: "slept", participle: "slept", translation: "dormir" },
    { base: "speak", past: "spoke", participle: "spoken", translation: "falar" },
    { base: "spend", past: "spent", participle: "spent", translation: "gastar" },
    { base: "stand", past: "stood", participle: "stood", translation: "ficar de pé" },
    { base: "steal", past: "stole", participle: "stolen", translation: "roubar" },
    { base: "swim", past: "swam", participle: "swum", translation: "nadar" },
    { base: "take", past: "took", participle: "taken", translation: "pegar" },
    { base: "teach", past: "taught", participle: "taught", translation: "ensinar" },
    { base: "tell", past: "told", participle: "told", translation: "contar" },
    { base: "think", past: "thought", participle: "thought", translation: "pensar" },
    { base: "throw", past: "threw", participle: "thrown", translation: "jogar" },
    { base: "understand", past: "understood", participle: "understood", translation: "entender" },
    { base: "wake", past: "woke", participle: "woken", translation: "acordar" },
    { base: "wear", past: "wore", participle: "worn", translation: "vestir" },
    { base: "win", past: "won", participle: "won", translation: "vencer" },
    { base: "write", past: "wrote", participle: "written", translation: "escrever" }
];

// ===== DAILY TIPS =====
const dailyTips = [
    "📚 Pratique inglês por pelo menos 15 minutos todo dia. Consistência é a chave!",
    "🎧 Ouça músicas em inglês e tente acompanhar as letras.",
    "📺 Assista séries com legendas em inglês para melhorar o listening.",
    "📝 Mantenha um diário em inglês, mesmo que seja só uma frase por dia.",
    "🗣️ Fale em voz alta! Mesmo sozinho, pratique a pronúncia.",
    "🎯 Foque em aprender vocabulário útil para seu dia a dia.",
    "📱 Mude o idioma do seu celular para inglês.",
    "👥 Encontre um parceiro de estudos para praticar conversação.",
    "🎬 Assista vídeos no YouTube em inglês sobre assuntos que você gosta.",
    "📖 Leia artigos curtos em inglês todos os dias.",
    "🎤 Use o reconhecimento de voz para verificar sua pronúncia.",
    "💭 Pense em inglês! Tente narrar suas atividades mentalmente.",
    "🔄 Revise o vocabulário aprendido regularmente.",
    "🎵 Cante em inglês - isso ajuda na fluência e pronúncia!",
    "📊 Acompanhe seu progresso e celebre pequenas vitórias.",
    "🌐 Siga páginas em inglês nas redes sociais.",
    "📻 Ouça podcasts em inglês enquanto faz outras atividades.",
    "✍️ Escreva resumos do que você aprendeu.",
    "🎮 Jogue jogos em inglês para aprender de forma divertida.",
    "📣 Não tenha medo de errar - erros são parte do aprendizado!"
];
