// ===== MEGA VOCABULARY 3: CLOTHING, ACCESSORIES & TRANSPORT =====
const clothingVocabulary2 = [
    { word: "Shirt", translation: "Camisa", phonetic: "/ʃɜːrt/", category: "Clothing", example: "White shirt.", examplePt: "Camisa branca." },
    { word: "T-shirt", translation: "Camiseta", phonetic: "/ˈtiːʃɜːrt/", category: "Clothing", example: "Cotton T-shirt.", examplePt: "Camiseta de algodão." },
    { word: "Pants", translation: "Calça", phonetic: "/pænts/", category: "Clothing", example: "Blue pants.", examplePt: "Calça azul." },
    { word: "Jeans", translation: "Jeans", phonetic: "/dʒiːnz/", category: "Clothing", example: "Skinny jeans.", examplePt: "Jeans skinny." },
    { word: "Shorts", translation: "Shorts", phonetic: "/ʃɔːrts/", category: "Clothing", example: "Summer shorts.", examplePt: "Shorts de verão." },
    { word: "Dress", translation: "Vestido", phonetic: "/dres/", category: "Clothing", example: "Red dress.", examplePt: "Vestido vermelho." },
    { word: "Skirt", translation: "Saia", phonetic: "/skɜːrt/", category: "Clothing", example: "Long skirt.", examplePt: "Saia longa." },
    { word: "Jacket", translation: "Jaqueta", phonetic: "/ˈdʒækɪt/", category: "Clothing", example: "Leather jacket.", examplePt: "Jaqueta de couro." },
    { word: "Coat", translation: "Casaco", phonetic: "/koʊt/", category: "Clothing", example: "Winter coat.", examplePt: "Casaco de inverno." },
    { word: "Sweater", translation: "Suéter", phonetic: "/ˈswetər/", category: "Clothing", example: "Wool sweater.", examplePt: "Suéter de lã." },
    { word: "Hoodie", translation: "Moletom", phonetic: "/ˈhʊdi/", category: "Clothing", example: "Comfortable hoodie.", examplePt: "Moletom confortável." },
    { word: "Suit", translation: "Terno", phonetic: "/suːt/", category: "Clothing", example: "Business suit.", examplePt: "Terno de negócios." },
    { word: "Tie", translation: "Gravata", phonetic: "/taɪ/", category: "Clothing", example: "Silk tie.", examplePt: "Gravata de seda." },
    { word: "Belt", translation: "Cinto", phonetic: "/belt/", category: "Clothing", example: "Leather belt.", examplePt: "Cinto de couro." },
    { word: "Socks", translation: "Meias", phonetic: "/sɑːks/", category: "Clothing", example: "Cotton socks.", examplePt: "Meias de algodão." },
    { word: "Shoes", translation: "Sapatos", phonetic: "/ʃuːz/", category: "Clothing", example: "New shoes.", examplePt: "Sapatos novos." },
    { word: "Boots", translation: "Botas", phonetic: "/buːts/", category: "Clothing", example: "Rain boots.", examplePt: "Botas de chuva." },
    { word: "Sneakers", translation: "Tênis", phonetic: "/ˈsniːkərz/", category: "Clothing", example: "Running sneakers.", examplePt: "Tênis de corrida." },
    { word: "Sandals", translation: "Sandálias", phonetic: "/ˈsændlz/", category: "Clothing", example: "Summer sandals.", examplePt: "Sandálias de verão." },
    { word: "Slippers", translation: "Chinelos", phonetic: "/ˈslɪpərz/", category: "Clothing", example: "Cozy slippers.", examplePt: "Chinelos aconchegantes." },
    { word: "Hat", translation: "Chapéu", phonetic: "/hæt/", category: "Clothing", example: "Straw hat.", examplePt: "Chapéu de palha." },
    { word: "Cap", translation: "Boné", phonetic: "/kæp/", category: "Clothing", example: "Baseball cap.", examplePt: "Boné de baseball." },
    { word: "Scarf", translation: "Cachecol", phonetic: "/skɑːrf/", category: "Clothing", example: "Warm scarf.", examplePt: "Cachecol quente." },
    { word: "Gloves", translation: "Luvas", phonetic: "/ɡlʌvz/", category: "Clothing", example: "Winter gloves.", examplePt: "Luvas de inverno." },
    { word: "Underwear", translation: "Roupa íntima", phonetic: "/ˈʌndərwer/", category: "Clothing", example: "Cotton underwear.", examplePt: "Roupa íntima." },
    { word: "Pajamas", translation: "Pijama", phonetic: "/pəˈdʒɑːməz/", category: "Clothing", example: "Comfortable pajamas.", examplePt: "Pijama confortável." },
    { word: "Swimsuit", translation: "Roupa de banho", phonetic: "/ˈswɪmsuːt/", category: "Clothing", example: "Beach swimsuit.", examplePt: "Roupa de banho." },
    { word: "Uniform", translation: "Uniforme", phonetic: "/ˈjuːnɪfɔːrm/", category: "Clothing", example: "School uniform.", examplePt: "Uniforme escolar." },
    { word: "Watch", translation: "Relógio", phonetic: "/wɑːtʃ/", category: "Accessories", example: "Smart watch.", examplePt: "Relógio inteligente." },
    { word: "Ring", translation: "Anel", phonetic: "/rɪŋ/", category: "Accessories", example: "Wedding ring.", examplePt: "Anel de casamento." },
    { word: "Necklace", translation: "Colar", phonetic: "/ˈnekləs/", category: "Accessories", example: "Gold necklace.", examplePt: "Colar de ouro." },
    { word: "Bracelet", translation: "Pulseira", phonetic: "/ˈbreɪslɪt/", category: "Accessories", example: "Silver bracelet.", examplePt: "Pulseira de prata." },
    { word: "Earrings", translation: "Brincos", phonetic: "/ˈɪrɪŋz/", category: "Accessories", example: "Diamond earrings.", examplePt: "Brincos de diamante." },
    { word: "Glasses", translation: "Óculos", phonetic: "/ˈɡlæsɪz/", category: "Accessories", example: "Reading glasses.", examplePt: "Óculos de leitura." },
    { word: "Sunglasses", translation: "Óculos de sol", phonetic: "/ˈsʌnɡlæsɪz/", category: "Accessories", example: "Cool sunglasses.", examplePt: "Óculos de sol legais." },
    { word: "Wallet", translation: "Carteira", phonetic: "/ˈwɑːlɪt/", category: "Accessories", example: "Leather wallet.", examplePt: "Carteira de couro." },
    { word: "Purse", translation: "Bolsa", phonetic: "/pɜːrs/", category: "Accessories", example: "Designer purse.", examplePt: "Bolsa de marca." },
    { word: "Backpack", translation: "Mochila", phonetic: "/ˈbækpæk/", category: "Accessories", example: "School backpack.", examplePt: "Mochila escolar." },
    { word: "Umbrella", translation: "Guarda-chuva", phonetic: "/ʌmˈbrelə/", category: "Accessories", example: "Folding umbrella.", examplePt: "Guarda-chuva dobrável." },
    { word: "Headphones", translation: "Fones de ouvido", phonetic: "/ˈhedfəʊnz/", category: "Accessories", example: "Wireless headphones.", examplePt: "Fones sem fio." }
];

const transportVocabulary2 = [
    { word: "Car", translation: "Carro", phonetic: "/kɑːr/", category: "Transport", example: "Fast car.", examplePt: "Carro rápido." },
    { word: "Bus", translation: "Ônibus", phonetic: "/bʌs/", category: "Transport", example: "City bus.", examplePt: "Ônibus da cidade." },
    { word: "Train", translation: "Trem", phonetic: "/treɪn/", category: "Transport", example: "High-speed train.", examplePt: "Trem de alta velocidade." },
    { word: "Subway", translation: "Metrô", phonetic: "/ˈsʌbweɪ/", category: "Transport", example: "Take the subway.", examplePt: "Pegue o metrô." },
    { word: "Plane", translation: "Avião", phonetic: "/pleɪn/", category: "Transport", example: "Commercial plane.", examplePt: "Avião comercial." },
    { word: "Bicycle", translation: "Bicicleta", phonetic: "/ˈbaɪsɪkl/", category: "Transport", example: "Ride a bicycle.", examplePt: "Andar de bicicleta." },
    { word: "Motorcycle", translation: "Moto", phonetic: "/ˈmoʊtərsaɪkl/", category: "Transport", example: "Fast motorcycle.", examplePt: "Moto rápida." },
    { word: "Taxi", translation: "Táxi", phonetic: "/ˈtæksi/", category: "Transport", example: "Call a taxi.", examplePt: "Chame um táxi." },
    { word: "Truck", translation: "Caminhão", phonetic: "/trʌk/", category: "Transport", example: "Delivery truck.", examplePt: "Caminhão de entrega." },
    { word: "Van", translation: "Van", phonetic: "/væn/", category: "Transport", example: "Family van.", examplePt: "Van familiar." },
    { word: "Boat", translation: "Barco", phonetic: "/boʊt/", category: "Transport", example: "Fishing boat.", examplePt: "Barco de pesca." },
    { word: "Ship", translation: "Navio", phonetic: "/ʃɪp/", category: "Transport", example: "Cruise ship.", examplePt: "Navio de cruzeiro." },
    { word: "Helicopter", translation: "Helicóptero", phonetic: "/ˈhelɪkɑːptər/", category: "Transport", example: "Police helicopter.", examplePt: "Helicóptero da polícia." },
    { word: "Ambulance", translation: "Ambulância", phonetic: "/ˈæmbjələns/", category: "Transport", example: "Call an ambulance.", examplePt: "Chame uma ambulância." },
    { word: "Traffic", translation: "Trânsito", phonetic: "/ˈtræfɪk/", category: "Transport", example: "Heavy traffic.", examplePt: "Trânsito pesado." },
    { word: "Parking", translation: "Estacionamento", phonetic: "/ˈpɑːrkɪŋ/", category: "Transport", example: "Parking lot.", examplePt: "Estacionamento." },
    { word: "Highway", translation: "Rodovia", phonetic: "/ˈhaɪweɪ/", category: "Transport", example: "Main highway.", examplePt: "Rodovia principal." },
    { word: "Traffic light", translation: "Semáforo", phonetic: "/ˈtræfɪk laɪt/", category: "Transport", example: "Wait for the light.", examplePt: "Espere o semáforo." },
    { word: "Seatbelt", translation: "Cinto de segurança", phonetic: "/ˈsiːtbelt/", category: "Transport", example: "Fasten your seatbelt.", examplePt: "Coloque o cinto." },
    { word: "License", translation: "Habilitação", phonetic: "/ˈlaɪsns/", category: "Transport", example: "Driver's license.", examplePt: "Carteira de motorista." }
];

console.log('👔 Clothing & Transport loaded:', clothingVocabulary2.length + transportVocabulary2.length, 'words');
