// ===== MASSIVE VOCABULARY DATABASE - PART 1: BEGINNER =====
const beginnerVocabulary = [
    // GREETINGS & ESSENTIALS (50 words)
    { word: "Hello", translation: "Olá", phonetic: "/həˈloʊ/", category: "Greetings", example: "Hello, how are you?", examplePt: "Olá, como você está?" },
    { word: "Hi", translation: "Oi", phonetic: "/haɪ/", category: "Greetings", example: "Hi there!", examplePt: "Oi!" },
    { word: "Good morning", translation: "Bom dia", phonetic: "/ɡʊd ˈmɔːrnɪŋ/", category: "Greetings", example: "Good morning, everyone!", examplePt: "Bom dia a todos!" },
    { word: "Good afternoon", translation: "Boa tarde", phonetic: "/ɡʊd æftərˈnuːn/", category: "Greetings", example: "Good afternoon, sir.", examplePt: "Boa tarde, senhor." },
    { word: "Good evening", translation: "Boa noite (chegando)", phonetic: "/ɡʊd ˈiːvnɪŋ/", category: "Greetings", example: "Good evening, welcome!", examplePt: "Boa noite, bem-vindo!" },
    { word: "Good night", translation: "Boa noite (despedida)", phonetic: "/ɡʊd naɪt/", category: "Greetings", example: "Good night, sleep well!", examplePt: "Boa noite, durma bem!" },
    { word: "Goodbye", translation: "Adeus/Tchau", phonetic: "/ɡʊdˈbaɪ/", category: "Greetings", example: "Goodbye, see you!", examplePt: "Tchau, até mais!" },
    { word: "Bye", translation: "Tchau", phonetic: "/baɪ/", category: "Greetings", example: "Bye, take care!", examplePt: "Tchau, se cuida!" },
    { word: "Please", translation: "Por favor", phonetic: "/pliːz/", category: "Essentials", example: "Please, help me.", examplePt: "Por favor, me ajude." },
    { word: "Thank you", translation: "Obrigado(a)", phonetic: "/θæŋk juː/", category: "Essentials", example: "Thank you very much!", examplePt: "Muito obrigado!" },
    { word: "Thanks", translation: "Valeu/Obrigado", phonetic: "/θæŋks/", category: "Essentials", example: "Thanks a lot!", examplePt: "Valeu demais!" },
    { word: "You're welcome", translation: "De nada", phonetic: "/jɔːr ˈwelkəm/", category: "Essentials", example: "You're welcome!", examplePt: "De nada!" },
    { word: "Sorry", translation: "Desculpe", phonetic: "/ˈsɑːri/", category: "Essentials", example: "I'm sorry for the delay.", examplePt: "Desculpe pelo atraso." },
    { word: "Excuse me", translation: "Com licença", phonetic: "/ɪkˈskjuːz miː/", category: "Essentials", example: "Excuse me, where is...?", examplePt: "Com licença, onde fica...?" },
    { word: "Yes", translation: "Sim", phonetic: "/jes/", category: "Essentials", example: "Yes, I understand.", examplePt: "Sim, eu entendo." },
    { word: "No", translation: "Não", phonetic: "/noʊ/", category: "Essentials", example: "No, thank you.", examplePt: "Não, obrigado." },
    { word: "Maybe", translation: "Talvez", phonetic: "/ˈmeɪbi/", category: "Essentials", example: "Maybe tomorrow.", examplePt: "Talvez amanhã." },
    { word: "Of course", translation: "Claro", phonetic: "/əv kɔːrs/", category: "Essentials", example: "Of course I can!", examplePt: "Claro que posso!" },

    // NUMBERS (30 words)
    { word: "Zero", translation: "Zero", phonetic: "/ˈzɪroʊ/", category: "Numbers", example: "Zero degrees.", examplePt: "Zero graus." },
    { word: "One", translation: "Um", phonetic: "/wʌn/", category: "Numbers", example: "One coffee, please.", examplePt: "Um café, por favor." },
    { word: "Two", translation: "Dois", phonetic: "/tuː/", category: "Numbers", example: "Two tickets.", examplePt: "Dois ingressos." },
    { word: "Three", translation: "Três", phonetic: "/θriː/", category: "Numbers", example: "Three days.", examplePt: "Três dias." },
    { word: "Four", translation: "Quatro", phonetic: "/fɔːr/", category: "Numbers", example: "Four people.", examplePt: "Quatro pessoas." },
    { word: "Five", translation: "Cinco", phonetic: "/faɪv/", category: "Numbers", example: "Five minutes.", examplePt: "Cinco minutos." },
    { word: "Six", translation: "Seis", phonetic: "/sɪks/", category: "Numbers", example: "Six hours.", examplePt: "Seis horas." },
    { word: "Seven", translation: "Sete", phonetic: "/ˈsevən/", category: "Numbers", example: "Seven days a week.", examplePt: "Sete dias por semana." },
    { word: "Eight", translation: "Oito", phonetic: "/eɪt/", category: "Numbers", example: "Eight o'clock.", examplePt: "Oito horas." },
    { word: "Nine", translation: "Nove", phonetic: "/naɪn/", category: "Numbers", example: "Nine months.", examplePt: "Nove meses." },
    { word: "Ten", translation: "Dez", phonetic: "/ten/", category: "Numbers", example: "Ten dollars.", examplePt: "Dez dólares." },
    { word: "Twenty", translation: "Vinte", phonetic: "/ˈtwenti/", category: "Numbers", example: "Twenty years old.", examplePt: "Vinte anos de idade." },
    { word: "Fifty", translation: "Cinquenta", phonetic: "/ˈfɪfti/", category: "Numbers", example: "Fifty percent.", examplePt: "Cinquenta por cento." },
    { word: "Hundred", translation: "Cem", phonetic: "/ˈhʌndrəd/", category: "Numbers", example: "One hundred percent.", examplePt: "Cem por cento." },
    { word: "Thousand", translation: "Mil", phonetic: "/ˈθaʊzənd/", category: "Numbers", example: "One thousand people.", examplePt: "Mil pessoas." },
    { word: "First", translation: "Primeiro", phonetic: "/fɜːrst/", category: "Numbers", example: "The first time.", examplePt: "A primeira vez." },
    { word: "Second", translation: "Segundo", phonetic: "/ˈsekənd/", category: "Numbers", example: "The second floor.", examplePt: "O segundo andar." },
    { word: "Third", translation: "Terceiro", phonetic: "/θɜːrd/", category: "Numbers", example: "Third place.", examplePt: "Terceiro lugar." },

    // COLORS (15 words)
    { word: "Red", translation: "Vermelho", phonetic: "/red/", category: "Colors", example: "The red car.", examplePt: "O carro vermelho." },
    { word: "Blue", translation: "Azul", phonetic: "/bluː/", category: "Colors", example: "Blue sky.", examplePt: "Céu azul." },
    { word: "Green", translation: "Verde", phonetic: "/ɡriːn/", category: "Colors", example: "Green light.", examplePt: "Luz verde." },
    { word: "Yellow", translation: "Amarelo", phonetic: "/ˈjeloʊ/", category: "Colors", example: "Yellow sun.", examplePt: "Sol amarelo." },
    { word: "Orange", translation: "Laranja", phonetic: "/ˈɔːrɪndʒ/", category: "Colors", example: "Orange juice.", examplePt: "Suco de laranja." },
    { word: "Purple", translation: "Roxo", phonetic: "/ˈpɜːrpl/", category: "Colors", example: "Purple flower.", examplePt: "Flor roxa." },
    { word: "Pink", translation: "Rosa", phonetic: "/pɪŋk/", category: "Colors", example: "Pink dress.", examplePt: "Vestido rosa." },
    { word: "Black", translation: "Preto", phonetic: "/blæk/", category: "Colors", example: "Black coffee.", examplePt: "Café preto." },
    { word: "White", translation: "Branco", phonetic: "/waɪt/", category: "Colors", example: "White snow.", examplePt: "Neve branca." },
    { word: "Gray", translation: "Cinza", phonetic: "/ɡreɪ/", category: "Colors", example: "Gray clouds.", examplePt: "Nuvens cinzas." },
    { word: "Brown", translation: "Marrom", phonetic: "/braʊn/", category: "Colors", example: "Brown hair.", examplePt: "Cabelo castanho." },

    // FAMILY (20 words)
    { word: "Family", translation: "Família", phonetic: "/ˈfæməli/", category: "Family", example: "My family is big.", examplePt: "Minha família é grande." },
    { word: "Mother", translation: "Mãe", phonetic: "/ˈmʌðər/", category: "Family", example: "My mother is kind.", examplePt: "Minha mãe é gentil." },
    { word: "Father", translation: "Pai", phonetic: "/ˈfɑːðər/", category: "Family", example: "My father works.", examplePt: "Meu pai trabalha." },
    { word: "Parents", translation: "Pais", phonetic: "/ˈperənts/", category: "Family", example: "My parents love me.", examplePt: "Meus pais me amam." },
    { word: "Brother", translation: "Irmão", phonetic: "/ˈbrʌðər/", category: "Family", example: "My older brother.", examplePt: "Meu irmão mais velho." },
    { word: "Sister", translation: "Irmã", phonetic: "/ˈsɪstər/", category: "Family", example: "My little sister.", examplePt: "Minha irmãzinha." },
    { word: "Son", translation: "Filho", phonetic: "/sʌn/", category: "Family", example: "My son is young.", examplePt: "Meu filho é jovem." },
    { word: "Daughter", translation: "Filha", phonetic: "/ˈdɔːtər/", category: "Family", example: "My daughter studies.", examplePt: "Minha filha estuda." },
    { word: "Grandfather", translation: "Avô", phonetic: "/ˈɡrændˌfɑːðər/", category: "Family", example: "My grandfather is wise.", examplePt: "Meu avô é sábio." },
    { word: "Grandmother", translation: "Avó", phonetic: "/ˈɡrændˌmʌðər/", category: "Family", example: "Grandma cooks well.", examplePt: "Vovó cozinha bem." },
    { word: "Uncle", translation: "Tio", phonetic: "/ˈʌŋkl/", category: "Family", example: "My uncle visits.", examplePt: "Meu tio visita." },
    { word: "Aunt", translation: "Tia", phonetic: "/ænt/", category: "Family", example: "My aunt is fun.", examplePt: "Minha tia é divertida." },
    { word: "Cousin", translation: "Primo(a)", phonetic: "/ˈkʌzn/", category: "Family", example: "My cousin plays.", examplePt: "Meu primo brinca." },
    { word: "Husband", translation: "Marido", phonetic: "/ˈhʌzbənd/", category: "Family", example: "Her husband.", examplePt: "O marido dela." },
    { word: "Wife", translation: "Esposa", phonetic: "/waɪf/", category: "Family", example: "His wife.", examplePt: "A esposa dele." },
    { word: "Friend", translation: "Amigo(a)", phonetic: "/frend/", category: "Family", example: "Best friend.", examplePt: "Melhor amigo." },

    // BODY PARTS (25 words)
    { word: "Head", translation: "Cabeça", phonetic: "/hed/", category: "Body", example: "My head hurts.", examplePt: "Minha cabeça dói." },
    { word: "Hair", translation: "Cabelo", phonetic: "/her/", category: "Body", example: "Long hair.", examplePt: "Cabelo longo." },
    { word: "Face", translation: "Rosto", phonetic: "/feɪs/", category: "Body", example: "Beautiful face.", examplePt: "Rosto bonito." },
    { word: "Eye", translation: "Olho", phonetic: "/aɪ/", category: "Body", example: "Blue eyes.", examplePt: "Olhos azuis." },
    { word: "Ear", translation: "Orelha", phonetic: "/ɪr/", category: "Body", example: "Listen with ears.", examplePt: "Ouvir com orelhas." },
    { word: "Nose", translation: "Nariz", phonetic: "/noʊz/", category: "Body", example: "Small nose.", examplePt: "Nariz pequeno." },
    { word: "Mouth", translation: "Boca", phonetic: "/maʊθ/", category: "Body", example: "Open your mouth.", examplePt: "Abra a boca." },
    { word: "Tooth", translation: "Dente", phonetic: "/tuːθ/", category: "Body", example: "White teeth.", examplePt: "Dentes brancos." },
    { word: "Neck", translation: "Pescoço", phonetic: "/nek/", category: "Body", example: "Long neck.", examplePt: "Pescoço longo." },
    { word: "Shoulder", translation: "Ombro", phonetic: "/ˈʃoʊldər/", category: "Body", example: "Strong shoulders.", examplePt: "Ombros fortes." },
    { word: "Arm", translation: "Braço", phonetic: "/ɑːrm/", category: "Body", example: "Left arm.", examplePt: "Braço esquerdo." },
    { word: "Hand", translation: "Mão", phonetic: "/hænd/", category: "Body", example: "Give me your hand.", examplePt: "Me dê sua mão." },
    { word: "Finger", translation: "Dedo (mão)", phonetic: "/ˈfɪŋɡər/", category: "Body", example: "Five fingers.", examplePt: "Cinco dedos." },
    { word: "Leg", translation: "Perna", phonetic: "/leɡ/", category: "Body", example: "Long legs.", examplePt: "Pernas longas." },
    { word: "Foot", translation: "Pé", phonetic: "/fʊt/", category: "Body", example: "Right foot.", examplePt: "Pé direito." },
    { word: "Heart", translation: "Coração", phonetic: "/hɑːrt/", category: "Body", example: "My heart beats.", examplePt: "Meu coração bate." },
    { word: "Back", translation: "Costas", phonetic: "/bæk/", category: "Body", example: "My back hurts.", examplePt: "Minhas costas doem." },

    // FOOD & DRINKS (40 words)
    { word: "Water", translation: "Água", phonetic: "/ˈwɔːtər/", category: "Food", example: "Cold water.", examplePt: "Água gelada." },
    { word: "Food", translation: "Comida", phonetic: "/fuːd/", category: "Food", example: "Delicious food.", examplePt: "Comida deliciosa." },
    { word: "Bread", translation: "Pão", phonetic: "/bred/", category: "Food", example: "Fresh bread.", examplePt: "Pão fresco." },
    { word: "Rice", translation: "Arroz", phonetic: "/raɪs/", category: "Food", example: "White rice.", examplePt: "Arroz branco." },
    { word: "Beans", translation: "Feijão", phonetic: "/biːnz/", category: "Food", example: "Black beans.", examplePt: "Feijão preto." },
    { word: "Meat", translation: "Carne", phonetic: "/miːt/", category: "Food", example: "Grilled meat.", examplePt: "Carne grelhada." },
    { word: "Chicken", translation: "Frango", phonetic: "/ˈtʃɪkɪn/", category: "Food", example: "Fried chicken.", examplePt: "Frango frito." },
    { word: "Fish", translation: "Peixe", phonetic: "/fɪʃ/", category: "Food", example: "Fresh fish.", examplePt: "Peixe fresco." },
    { word: "Egg", translation: "Ovo", phonetic: "/eɡ/", category: "Food", example: "Scrambled eggs.", examplePt: "Ovos mexidos." },
    { word: "Cheese", translation: "Queijo", phonetic: "/tʃiːz/", category: "Food", example: "Cheese pizza.", examplePt: "Pizza de queijo." },
    { word: "Milk", translation: "Leite", phonetic: "/mɪlk/", category: "Food", example: "Fresh milk.", examplePt: "Leite fresco." },
    { word: "Coffee", translation: "Café", phonetic: "/ˈkɔːfi/", category: "Food", example: "Morning coffee.", examplePt: "Café da manhã." },
    { word: "Tea", translation: "Chá", phonetic: "/tiː/", category: "Food", example: "Hot tea.", examplePt: "Chá quente." },
    { word: "Juice", translation: "Suco", phonetic: "/dʒuːs/", category: "Food", example: "Orange juice.", examplePt: "Suco de laranja." },
    { word: "Fruit", translation: "Fruta", phonetic: "/fruːt/", category: "Food", example: "Fresh fruit.", examplePt: "Fruta fresca." },
    { word: "Apple", translation: "Maçã", phonetic: "/ˈæpl/", category: "Food", example: "Red apple.", examplePt: "Maçã vermelha." },
    { word: "Banana", translation: "Banana", phonetic: "/bəˈnænə/", category: "Food", example: "Ripe banana.", examplePt: "Banana madura." },
    { word: "Orange", translation: "Laranja", phonetic: "/ˈɔːrɪndʒ/", category: "Food", example: "Sweet orange.", examplePt: "Laranja doce." },
    { word: "Vegetable", translation: "Vegetal/Legume", phonetic: "/ˈvedʒtəbl/", category: "Food", example: "Fresh vegetables.", examplePt: "Vegetais frescos." },
    { word: "Salad", translation: "Salada", phonetic: "/ˈsæləd/", category: "Food", example: "Green salad.", examplePt: "Salada verde." },
    { word: "Soup", translation: "Sopa", phonetic: "/suːp/", category: "Food", example: "Hot soup.", examplePt: "Sopa quente." },
    { word: "Cake", translation: "Bolo", phonetic: "/keɪk/", category: "Food", example: "Birthday cake.", examplePt: "Bolo de aniversário." },
    { word: "Sugar", translation: "Açúcar", phonetic: "/ˈʃʊɡər/", category: "Food", example: "No sugar.", examplePt: "Sem açúcar." },
    { word: "Salt", translation: "Sal", phonetic: "/sɔːlt/", category: "Food", example: "Add salt.", examplePt: "Adicione sal." },
    { word: "Breakfast", translation: "Café da manhã", phonetic: "/ˈbrekfəst/", category: "Food", example: "Eat breakfast.", examplePt: "Tomar café da manhã." },
    { word: "Lunch", translation: "Almoço", phonetic: "/lʌntʃ/", category: "Food", example: "Lunch time.", examplePt: "Hora do almoço." },
    { word: "Dinner", translation: "Jantar", phonetic: "/ˈdɪnər/", category: "Food", example: "Family dinner.", examplePt: "Jantar em família." },

    // TIME (25 words)
    { word: "Time", translation: "Tempo/Hora", phonetic: "/taɪm/", category: "Time", example: "What time is it?", examplePt: "Que horas são?" },
    { word: "Today", translation: "Hoje", phonetic: "/təˈdeɪ/", category: "Time", example: "Today is Monday.", examplePt: "Hoje é segunda." },
    { word: "Tomorrow", translation: "Amanhã", phonetic: "/təˈmɔːroʊ/", category: "Time", example: "See you tomorrow.", examplePt: "Vejo você amanhã." },
    { word: "Yesterday", translation: "Ontem", phonetic: "/ˈjestərdeɪ/", category: "Time", example: "I worked yesterday.", examplePt: "Trabalhei ontem." },
    { word: "Now", translation: "Agora", phonetic: "/naʊ/", category: "Time", example: "Do it now.", examplePt: "Faça agora." },
    { word: "Later", translation: "Depois", phonetic: "/ˈleɪtər/", category: "Time", example: "Call me later.", examplePt: "Me ligue depois." },
    { word: "Early", translation: "Cedo", phonetic: "/ˈɜːrli/", category: "Time", example: "Wake up early.", examplePt: "Acordar cedo." },
    { word: "Late", translation: "Tarde/Atrasado", phonetic: "/leɪt/", category: "Time", example: "I'm late.", examplePt: "Estou atrasado." },
    { word: "Morning", translation: "Manhã", phonetic: "/ˈmɔːrnɪŋ/", category: "Time", example: "Every morning.", examplePt: "Toda manhã." },
    { word: "Afternoon", translation: "Tarde", phonetic: "/ˌæftərˈnuːn/", category: "Time", example: "This afternoon.", examplePt: "Esta tarde." },
    { word: "Night", translation: "Noite", phonetic: "/naɪt/", category: "Time", example: "At night.", examplePt: "À noite." },
    { word: "Week", translation: "Semana", phonetic: "/wiːk/", category: "Time", example: "Next week.", examplePt: "Próxima semana." },
    { word: "Month", translation: "Mês", phonetic: "/mʌnθ/", category: "Time", example: "Every month.", examplePt: "Todo mês." },
    { word: "Year", translation: "Ano", phonetic: "/jɪr/", category: "Time", example: "New year.", examplePt: "Ano novo." },
    { word: "Monday", translation: "Segunda-feira", phonetic: "/ˈmʌndeɪ/", category: "Time", example: "On Monday.", examplePt: "Na segunda." },
    { word: "Tuesday", translation: "Terça-feira", phonetic: "/ˈtuːzdeɪ/", category: "Time", example: "Next Tuesday.", examplePt: "Próxima terça." },
    { word: "Wednesday", translation: "Quarta-feira", phonetic: "/ˈwenzdeɪ/", category: "Time", example: "Every Wednesday.", examplePt: "Toda quarta." },
    { word: "Thursday", translation: "Quinta-feira", phonetic: "/ˈθɜːrzdeɪ/", category: "Time", example: "On Thursday.", examplePt: "Na quinta." },
    { word: "Friday", translation: "Sexta-feira", phonetic: "/ˈfraɪdeɪ/", category: "Time", example: "Friday night.", examplePt: "Sexta à noite." },
    { word: "Saturday", translation: "Sábado", phonetic: "/ˈsætərdeɪ/", category: "Time", example: "On Saturday.", examplePt: "No sábado." },
    { word: "Sunday", translation: "Domingo", phonetic: "/ˈsʌndeɪ/", category: "Time", example: "Every Sunday.", examplePt: "Todo domingo." },

    // COMMON VERBS (50 words)
    { word: "To be", translation: "Ser/Estar", phonetic: "/tuː biː/", category: "Verbs", example: "I want to be happy.", examplePt: "Quero ser feliz." },
    { word: "To have", translation: "Ter", phonetic: "/tuː hæv/", category: "Verbs", example: "I have a car.", examplePt: "Eu tenho um carro." },
    { word: "To do", translation: "Fazer", phonetic: "/tuː duː/", category: "Verbs", example: "What do you do?", examplePt: "O que você faz?" },
    { word: "To go", translation: "Ir", phonetic: "/tuː ɡoʊ/", category: "Verbs", example: "Let's go home.", examplePt: "Vamos para casa." },
    { word: "To come", translation: "Vir", phonetic: "/tuː kʌm/", category: "Verbs", example: "Come here.", examplePt: "Venha aqui." },
    { word: "To see", translation: "Ver", phonetic: "/tuː siː/", category: "Verbs", example: "I see you.", examplePt: "Eu vejo você." },
    { word: "To know", translation: "Saber/Conhecer", phonetic: "/tuː noʊ/", category: "Verbs", example: "I know that.", examplePt: "Eu sei disso." },
    { word: "To think", translation: "Pensar", phonetic: "/tuː θɪŋk/", category: "Verbs", example: "I think so.", examplePt: "Eu acho que sim." },
    { word: "To take", translation: "Pegar/Levar", phonetic: "/tuː teɪk/", category: "Verbs", example: "Take this.", examplePt: "Pegue isso." },
    { word: "To get", translation: "Obter/Conseguir", phonetic: "/tuː ɡet/", category: "Verbs", example: "Get ready.", examplePt: "Fique pronto." },
    { word: "To make", translation: "Fazer/Criar", phonetic: "/tuː meɪk/", category: "Verbs", example: "Make coffee.", examplePt: "Fazer café." },
    { word: "To say", translation: "Dizer", phonetic: "/tuː seɪ/", category: "Verbs", example: "What did you say?", examplePt: "O que você disse?" },
    { word: "To give", translation: "Dar", phonetic: "/tuː ɡɪv/", category: "Verbs", example: "Give me that.", examplePt: "Me dê isso." },
    { word: "To find", translation: "Encontrar", phonetic: "/tuː faɪnd/", category: "Verbs", example: "Find the key.", examplePt: "Encontre a chave." },
    { word: "To tell", translation: "Contar/Dizer", phonetic: "/tuː tel/", category: "Verbs", example: "Tell me.", examplePt: "Me conte." },
    { word: "To ask", translation: "Perguntar", phonetic: "/tuː æsk/", category: "Verbs", example: "Ask him.", examplePt: "Pergunte a ele." },
    { word: "To work", translation: "Trabalhar", phonetic: "/tuː wɜːrk/", category: "Verbs", example: "I work here.", examplePt: "Eu trabalho aqui." },
    { word: "To need", translation: "Precisar", phonetic: "/tuː niːd/", category: "Verbs", example: "I need help.", examplePt: "Preciso de ajuda." },
    { word: "To want", translation: "Querer", phonetic: "/tuː wɑːnt/", category: "Verbs", example: "I want this.", examplePt: "Eu quero isso." },
    { word: "To like", translation: "Gostar", phonetic: "/tuː laɪk/", category: "Verbs", example: "I like it.", examplePt: "Eu gosto." },
    { word: "To love", translation: "Amar", phonetic: "/tuː lʌv/", category: "Verbs", example: "I love you.", examplePt: "Eu te amo." },
    { word: "To eat", translation: "Comer", phonetic: "/tuː iːt/", category: "Verbs", example: "Let's eat.", examplePt: "Vamos comer." },
    { word: "To drink", translation: "Beber", phonetic: "/tuː drɪŋk/", category: "Verbs", example: "Drink water.", examplePt: "Beba água." },
    { word: "To sleep", translation: "Dormir", phonetic: "/tuː sliːp/", category: "Verbs", example: "Time to sleep.", examplePt: "Hora de dormir." },
    { word: "To wake", translation: "Acordar", phonetic: "/tuː weɪk/", category: "Verbs", example: "Wake up!", examplePt: "Acorde!" },
    { word: "To walk", translation: "Andar/Caminhar", phonetic: "/tuː wɔːk/", category: "Verbs", example: "Walk slowly.", examplePt: "Ande devagar." },
    { word: "To run", translation: "Correr", phonetic: "/tuː rʌn/", category: "Verbs", example: "Run fast.", examplePt: "Corra rápido." },
    { word: "To read", translation: "Ler", phonetic: "/tuː riːd/", category: "Verbs", example: "Read the book.", examplePt: "Leia o livro." },
    { word: "To write", translation: "Escrever", phonetic: "/tuː raɪt/", category: "Verbs", example: "Write your name.", examplePt: "Escreva seu nome." },
    { word: "To speak", translation: "Falar", phonetic: "/tuː spiːk/", category: "Verbs", example: "Speak English.", examplePt: "Fale inglês." },
    { word: "To listen", translation: "Ouvir/Escutar", phonetic: "/tuː ˈlɪsn/", category: "Verbs", example: "Listen carefully.", examplePt: "Ouça com atenção." },
    { word: "To help", translation: "Ajudar", phonetic: "/tuː help/", category: "Verbs", example: "Help me.", examplePt: "Me ajude." },
    { word: "To try", translation: "Tentar", phonetic: "/tuː traɪ/", category: "Verbs", example: "Try again.", examplePt: "Tente de novo." },
    { word: "To buy", translation: "Comprar", phonetic: "/tuː baɪ/", category: "Verbs", example: "Buy food.", examplePt: "Comprar comida." },
    { word: "To sell", translation: "Vender", phonetic: "/tuː sel/", category: "Verbs", example: "Sell the car.", examplePt: "Vender o carro." },
    { word: "To pay", translation: "Pagar", phonetic: "/tuː peɪ/", category: "Verbs", example: "Pay the bill.", examplePt: "Pague a conta." },
    { word: "To open", translation: "Abrir", phonetic: "/tuː ˈoʊpən/", category: "Verbs", example: "Open the door.", examplePt: "Abra a porta." },
    { word: "To close", translation: "Fechar", phonetic: "/tuː kloʊz/", category: "Verbs", example: "Close the window.", examplePt: "Feche a janela." },
    { word: "To start", translation: "Começar", phonetic: "/tuː stɑːrt/", category: "Verbs", example: "Start now.", examplePt: "Comece agora." },
    { word: "To stop", translation: "Parar", phonetic: "/tuː stɑːp/", category: "Verbs", example: "Stop it.", examplePt: "Pare com isso." },
    { word: "To wait", translation: "Esperar", phonetic: "/tuː weɪt/", category: "Verbs", example: "Wait here.", examplePt: "Espere aqui." },
    { word: "To learn", translation: "Aprender", phonetic: "/tuː lɜːrn/", category: "Verbs", example: "Learn English.", examplePt: "Aprender inglês." },
    { word: "To teach", translation: "Ensinar", phonetic: "/tuː tiːtʃ/", category: "Verbs", example: "Teach me.", examplePt: "Me ensine." },
    { word: "To play", translation: "Jogar/Brincar", phonetic: "/tuː pleɪ/", category: "Verbs", example: "Play games.", examplePt: "Jogar jogos." },
    { word: "To watch", translation: "Assistir", phonetic: "/tuː wɑːtʃ/", category: "Verbs", example: "Watch TV.", examplePt: "Assistir TV." },

    // PLACES (25 words)
    { word: "House", translation: "Casa", phonetic: "/haʊs/", category: "Places", example: "Big house.", examplePt: "Casa grande." },
    { word: "Home", translation: "Lar", phonetic: "/hoʊm/", category: "Places", example: "Go home.", examplePt: "Ir para casa." },
    { word: "Room", translation: "Quarto/Sala", phonetic: "/ruːm/", category: "Places", example: "Living room.", examplePt: "Sala de estar." },
    { word: "Kitchen", translation: "Cozinha", phonetic: "/ˈkɪtʃɪn/", category: "Places", example: "In the kitchen.", examplePt: "Na cozinha." },
    { word: "Bathroom", translation: "Banheiro", phonetic: "/ˈbæθruːm/", category: "Places", example: "Where is the bathroom?", examplePt: "Onde é o banheiro?" },
    { word: "Bedroom", translation: "Quarto", phonetic: "/ˈbedruːm/", category: "Places", example: "My bedroom.", examplePt: "Meu quarto." },
    { word: "School", translation: "Escola", phonetic: "/skuːl/", category: "Places", example: "Go to school.", examplePt: "Ir para escola." },
    { word: "Hospital", translation: "Hospital", phonetic: "/ˈhɑːspɪtl/", category: "Places", example: "Near the hospital.", examplePt: "Perto do hospital." },
    { word: "Restaurant", translation: "Restaurante", phonetic: "/ˈrestərɑːnt/", category: "Places", example: "Good restaurant.", examplePt: "Bom restaurante." },
    { word: "Store", translation: "Loja", phonetic: "/stɔːr/", category: "Places", example: "Clothing store.", examplePt: "Loja de roupas." },
    { word: "Market", translation: "Mercado", phonetic: "/ˈmɑːrkɪt/", category: "Places", example: "Supermarket.", examplePt: "Supermercado." },
    { word: "Bank", translation: "Banco", phonetic: "/bæŋk/", category: "Places", example: "At the bank.", examplePt: "No banco." },
    { word: "Airport", translation: "Aeroporto", phonetic: "/ˈerpɔːrt/", category: "Places", example: "International airport.", examplePt: "Aeroporto internacional." },
    { word: "Street", translation: "Rua", phonetic: "/striːt/", category: "Places", example: "Main street.", examplePt: "Rua principal." },
    { word: "City", translation: "Cidade", phonetic: "/ˈsɪti/", category: "Places", example: "Big city.", examplePt: "Cidade grande." },
    { word: "Country", translation: "País", phonetic: "/ˈkʌntri/", category: "Places", example: "My country.", examplePt: "Meu país." },
    { word: "Park", translation: "Parque", phonetic: "/pɑːrk/", category: "Places", example: "In the park.", examplePt: "No parque." },
    { word: "Beach", translation: "Praia", phonetic: "/biːtʃ/", category: "Places", example: "Beautiful beach.", examplePt: "Praia bonita." },
    { word: "Church", translation: "Igreja", phonetic: "/tʃɜːrtʃ/", category: "Places", example: "Old church.", examplePt: "Igreja antiga." },
    { word: "Office", translation: "Escritório", phonetic: "/ˈɔːfɪs/", category: "Places", example: "My office.", examplePt: "Meu escritório." },

    // ADJECTIVES (40 words)
    { word: "Big", translation: "Grande", phonetic: "/bɪɡ/", category: "Adjectives", example: "Big house.", examplePt: "Casa grande." },
    { word: "Small", translation: "Pequeno", phonetic: "/smɔːl/", category: "Adjectives", example: "Small car.", examplePt: "Carro pequeno." },
    { word: "Good", translation: "Bom", phonetic: "/ɡʊd/", category: "Adjectives", example: "Good job.", examplePt: "Bom trabalho." },
    { word: "Bad", translation: "Ruim/Mau", phonetic: "/bæd/", category: "Adjectives", example: "Bad weather.", examplePt: "Tempo ruim." },
    { word: "New", translation: "Novo", phonetic: "/nuː/", category: "Adjectives", example: "New phone.", examplePt: "Celular novo." },
    { word: "Old", translation: "Velho/Antigo", phonetic: "/oʊld/", category: "Adjectives", example: "Old friend.", examplePt: "Velho amigo." },
    { word: "Young", translation: "Jovem", phonetic: "/jʌŋ/", category: "Adjectives", example: "Young man.", examplePt: "Homem jovem." },
    { word: "Happy", translation: "Feliz", phonetic: "/ˈhæpi/", category: "Adjectives", example: "Very happy.", examplePt: "Muito feliz." },
    { word: "Sad", translation: "Triste", phonetic: "/sæd/", category: "Adjectives", example: "So sad.", examplePt: "Tão triste." },
    { word: "Hot", translation: "Quente", phonetic: "/hɑːt/", category: "Adjectives", example: "Hot day.", examplePt: "Dia quente." },
    { word: "Cold", translation: "Frio", phonetic: "/koʊld/", category: "Adjectives", example: "Cold water.", examplePt: "Água fria." },
    { word: "Fast", translation: "Rápido", phonetic: "/fæst/", category: "Adjectives", example: "Fast car.", examplePt: "Carro rápido." },
    { word: "Slow", translation: "Lento", phonetic: "/sloʊ/", category: "Adjectives", example: "Slow motion.", examplePt: "Câmera lenta." },
    { word: "Easy", translation: "Fácil", phonetic: "/ˈiːzi/", category: "Adjectives", example: "Easy task.", examplePt: "Tarefa fácil." },
    { word: "Hard", translation: "Difícil/Duro", phonetic: "/hɑːrd/", category: "Adjectives", example: "Hard work.", examplePt: "Trabalho duro." },
    { word: "Beautiful", translation: "Bonito/Lindo", phonetic: "/ˈbjuːtɪfl/", category: "Adjectives", example: "Beautiful girl.", examplePt: "Menina bonita." },
    { word: "Ugly", translation: "Feio", phonetic: "/ˈʌɡli/", category: "Adjectives", example: "Ugly monster.", examplePt: "Monstro feio." },
    { word: "Rich", translation: "Rico", phonetic: "/rɪtʃ/", category: "Adjectives", example: "Rich man.", examplePt: "Homem rico." },
    { word: "Poor", translation: "Pobre", phonetic: "/pʊr/", category: "Adjectives", example: "Poor family.", examplePt: "Família pobre." },
    { word: "Full", translation: "Cheio", phonetic: "/fʊl/", category: "Adjectives", example: "Full tank.", examplePt: "Tanque cheio." },
    { word: "Empty", translation: "Vazio", phonetic: "/ˈempti/", category: "Adjectives", example: "Empty room.", examplePt: "Sala vazia." },
    { word: "Right", translation: "Certo/Direito", phonetic: "/raɪt/", category: "Adjectives", example: "Right answer.", examplePt: "Resposta certa." },
    { word: "Wrong", translation: "Errado", phonetic: "/rɔːŋ/", category: "Adjectives", example: "Wrong way.", examplePt: "Caminho errado." },
    { word: "Important", translation: "Importante", phonetic: "/ɪmˈpɔːrtənt/", category: "Adjectives", example: "Very important.", examplePt: "Muito importante." },
    { word: "Different", translation: "Diferente", phonetic: "/ˈdɪfrənt/", category: "Adjectives", example: "Something different.", examplePt: "Algo diferente." },
    { word: "Same", translation: "Mesmo", phonetic: "/seɪm/", category: "Adjectives", example: "Same thing.", examplePt: "Mesma coisa." },
    { word: "Tired", translation: "Cansado", phonetic: "/ˈtaɪərd/", category: "Adjectives", example: "I'm tired.", examplePt: "Estou cansado." },
    { word: "Hungry", translation: "Com fome", phonetic: "/ˈhʌŋɡri/", category: "Adjectives", example: "I'm hungry.", examplePt: "Estou com fome." },
    { word: "Thirsty", translation: "Com sede", phonetic: "/ˈθɜːrsti/", category: "Adjectives", example: "I'm thirsty.", examplePt: "Estou com sede." },
    { word: "Busy", translation: "Ocupado", phonetic: "/ˈbɪzi/", category: "Adjectives", example: "Very busy.", examplePt: "Muito ocupado." },
    { word: "Free", translation: "Livre/Grátis", phonetic: "/friː/", category: "Adjectives", example: "Free time.", examplePt: "Tempo livre." },
    { word: "Ready", translation: "Pronto", phonetic: "/ˈredi/", category: "Adjectives", example: "I'm ready.", examplePt: "Estou pronto." },
    { word: "Sure", translation: "Certo/Com certeza", phonetic: "/ʃʊr/", category: "Adjectives", example: "I'm sure.", examplePt: "Tenho certeza." },
    { word: "Possible", translation: "Possível", phonetic: "/ˈpɑːsəbl/", category: "Adjectives", example: "It's possible.", examplePt: "É possível." },
    { word: "Necessary", translation: "Necessário", phonetic: "/ˈnesəseri/", category: "Adjectives", example: "It's necessary.", examplePt: "É necessário." }
];
