// ===== MEGA VOCABULARY 2: ANIMALS & NATURE =====
const animalsVocabulary2 = [
    { word: "Dog", translation: "Cachorro", phonetic: "/dɔːɡ/", category: "Animals", example: "Friendly dog.", examplePt: "Cachorro amigável." },
    { word: "Cat", translation: "Gato", phonetic: "/kæt/", category: "Animals", example: "Black cat.", examplePt: "Gato preto." },
    { word: "Bird", translation: "Pássaro", phonetic: "/bɜːrd/", category: "Animals", example: "Colorful bird.", examplePt: "Pássaro colorido." },
    { word: "Horse", translation: "Cavalo", phonetic: "/hɔːrs/", category: "Animals", example: "Fast horse.", examplePt: "Cavalo rápido." },
    { word: "Cow", translation: "Vaca", phonetic: "/kaʊ/", category: "Animals", example: "Dairy cow.", examplePt: "Vaca leiteira." },
    { word: "Pig", translation: "Porco", phonetic: "/pɪɡ/", category: "Animals", example: "Farm pig.", examplePt: "Porco da fazenda." },
    { word: "Sheep", translation: "Ovelha", phonetic: "/ʃiːp/", category: "Animals", example: "White sheep.", examplePt: "Ovelha branca." },
    { word: "Goat", translation: "Cabra", phonetic: "/ɡoʊt/", category: "Animals", example: "Mountain goat.", examplePt: "Cabra da montanha." },
    { word: "Chicken", translation: "Galinha", phonetic: "/ˈtʃɪkɪn/", category: "Animals", example: "Farm chicken.", examplePt: "Galinha." },
    { word: "Duck", translation: "Pato", phonetic: "/dʌk/", category: "Animals", example: "Wild duck.", examplePt: "Pato selvagem." },
    { word: "Rabbit", translation: "Coelho", phonetic: "/ˈræbɪt/", category: "Animals", example: "Cute rabbit.", examplePt: "Coelho fofo." },
    { word: "Mouse", translation: "Rato", phonetic: "/maʊs/", category: "Animals", example: "Small mouse.", examplePt: "Rato pequeno." },
    { word: "Elephant", translation: "Elefante", phonetic: "/ˈelɪfənt/", category: "Animals", example: "Big elephant.", examplePt: "Elefante grande." },
    { word: "Lion", translation: "Leão", phonetic: "/ˈlaɪən/", category: "Animals", example: "Brave lion.", examplePt: "Leão corajoso." },
    { word: "Tiger", translation: "Tigre", phonetic: "/ˈtaɪɡər/", category: "Animals", example: "Bengal tiger.", examplePt: "Tigre de Bengala." },
    { word: "Bear", translation: "Urso", phonetic: "/ber/", category: "Animals", example: "Brown bear.", examplePt: "Urso marrom." },
    { word: "Wolf", translation: "Lobo", phonetic: "/wʊlf/", category: "Animals", example: "Wild wolf.", examplePt: "Lobo selvagem." },
    { word: "Fox", translation: "Raposa", phonetic: "/fɑːks/", category: "Animals", example: "Red fox.", examplePt: "Raposa vermelha." },
    { word: "Deer", translation: "Cervo", phonetic: "/dɪr/", category: "Animals", example: "Wild deer.", examplePt: "Cervo selvagem." },
    { word: "Monkey", translation: "Macaco", phonetic: "/ˈmʌŋki/", category: "Animals", example: "Playful monkey.", examplePt: "Macaco brincalhão." },
    { word: "Gorilla", translation: "Gorila", phonetic: "/ɡəˈrɪlə/", category: "Animals", example: "Mountain gorilla.", examplePt: "Gorila da montanha." },
    { word: "Zebra", translation: "Zebra", phonetic: "/ˈziːbrə/", category: "Animals", example: "African zebra.", examplePt: "Zebra africana." },
    { word: "Giraffe", translation: "Girafa", phonetic: "/dʒəˈræf/", category: "Animals", example: "Tall giraffe.", examplePt: "Girafa alta." },
    { word: "Hippo", translation: "Hipopótamo", phonetic: "/ˈhɪpoʊ/", category: "Animals", example: "Heavy hippo.", examplePt: "Hipopótamo pesado." },
    { word: "Crocodile", translation: "Crocodilo", phonetic: "/ˈkrɑːkədaɪl/", category: "Animals", example: "Dangerous crocodile.", examplePt: "Crocodilo perigoso." },
    { word: "Snake", translation: "Cobra", phonetic: "/sneɪk/", category: "Animals", example: "Venomous snake.", examplePt: "Cobra venenosa." },
    { word: "Turtle", translation: "Tartaruga", phonetic: "/ˈtɜːrtl/", category: "Animals", example: "Sea turtle.", examplePt: "Tartaruga marinha." },
    { word: "Frog", translation: "Sapo", phonetic: "/frɔːɡ/", category: "Animals", example: "Green frog.", examplePt: "Sapo verde." },
    { word: "Shark", translation: "Tubarão", phonetic: "/ʃɑːrk/", category: "Animals", example: "Great white shark.", examplePt: "Grande tubarão branco." },
    { word: "Whale", translation: "Baleia", phonetic: "/weɪl/", category: "Animals", example: "Blue whale.", examplePt: "Baleia azul." },
    { word: "Dolphin", translation: "Golfinho", phonetic: "/ˈdɑːlfɪn/", category: "Animals", example: "Friendly dolphin.", examplePt: "Golfinho amigável." },
    { word: "Octopus", translation: "Polvo", phonetic: "/ˈɑːktəpəs/", category: "Animals", example: "Giant octopus.", examplePt: "Polvo gigante." },
    { word: "Crab", translation: "Caranguejo", phonetic: "/kræb/", category: "Animals", example: "Beach crab.", examplePt: "Caranguejo de praia." },
    { word: "Butterfly", translation: "Borboleta", phonetic: "/ˈbʌtərflaɪ/", category: "Animals", example: "Colorful butterfly.", examplePt: "Borboleta colorida." },
    { word: "Bee", translation: "Abelha", phonetic: "/biː/", category: "Animals", example: "Busy bee.", examplePt: "Abelha ocupada." },
    { word: "Ant", translation: "Formiga", phonetic: "/ænt/", category: "Animals", example: "Hard-working ant.", examplePt: "Formiga trabalhadora." },
    { word: "Spider", translation: "Aranha", phonetic: "/ˈspaɪdər/", category: "Animals", example: "Big spider.", examplePt: "Aranha grande." },
    { word: "Eagle", translation: "Águia", phonetic: "/ˈiːɡl/", category: "Animals", example: "Bald eagle.", examplePt: "Águia careca." },
    { word: "Owl", translation: "Coruja", phonetic: "/aʊl/", category: "Animals", example: "Wise owl.", examplePt: "Coruja sábia." },
    { word: "Parrot", translation: "Papagaio", phonetic: "/ˈpærət/", category: "Animals", example: "Talking parrot.", examplePt: "Papagaio falante." },
    { word: "Penguin", translation: "Pinguim", phonetic: "/ˈpeŋɡwɪn/", category: "Animals", example: "Emperor penguin.", examplePt: "Pinguim imperador." },
    { word: "Camel", translation: "Camelo", phonetic: "/ˈkæml/", category: "Animals", example: "Desert camel.", examplePt: "Camelo do deserto." },
    { word: "Kangaroo", translation: "Canguru", phonetic: "/ˌkæŋɡəˈruː/", category: "Animals", example: "Australian kangaroo.", examplePt: "Canguru australiano." },
    { word: "Koala", translation: "Coala", phonetic: "/koʊˈɑːlə/", category: "Animals", example: "Cute koala.", examplePt: "Coala fofo." },
    { word: "Panda", translation: "Panda", phonetic: "/ˈpændə/", category: "Animals", example: "Giant panda.", examplePt: "Panda gigante." }
];

const natureVocabulary2 = [
    { word: "Tree", translation: "Árvore", phonetic: "/triː/", category: "Nature", example: "Tall tree.", examplePt: "Árvore alta." },
    { word: "Flower", translation: "Flor", phonetic: "/ˈflaʊər/", category: "Nature", example: "Beautiful flower.", examplePt: "Flor bonita." },
    { word: "Grass", translation: "Grama", phonetic: "/ɡræs/", category: "Nature", example: "Green grass.", examplePt: "Grama verde." },
    { word: "Leaf", translation: "Folha", phonetic: "/liːf/", category: "Nature", example: "Green leaf.", examplePt: "Folha verde." },
    { word: "Branch", translation: "Galho", phonetic: "/bræntʃ/", category: "Nature", example: "Tree branch.", examplePt: "Galho de árvore." },
    { word: "Root", translation: "Raiz", phonetic: "/ruːt/", category: "Nature", example: "Deep roots.", examplePt: "Raízes profundas." },
    { word: "Seed", translation: "Semente", phonetic: "/siːd/", category: "Nature", example: "Plant a seed.", examplePt: "Plante uma semente." },
    { word: "Bush", translation: "Arbusto", phonetic: "/bʊʃ/", category: "Nature", example: "Rose bush.", examplePt: "Arbusto de rosas." },
    { word: "Forest", translation: "Floresta", phonetic: "/ˈfɔːrɪst/", category: "Nature", example: "Dense forest.", examplePt: "Floresta densa." },
    { word: "Jungle", translation: "Selva", phonetic: "/ˈdʒʌŋɡl/", category: "Nature", example: "Amazon jungle.", examplePt: "Selva amazônica." },
    { word: "Mountain", translation: "Montanha", phonetic: "/ˈmaʊntən/", category: "Nature", example: "High mountain.", examplePt: "Montanha alta." },
    { word: "Hill", translation: "Colina", phonetic: "/hɪl/", category: "Nature", example: "Green hill.", examplePt: "Colina verde." },
    { word: "Valley", translation: "Vale", phonetic: "/ˈvæli/", category: "Nature", example: "Beautiful valley.", examplePt: "Vale bonito." },
    { word: "River", translation: "Rio", phonetic: "/ˈrɪvər/", category: "Nature", example: "Long river.", examplePt: "Rio longo." },
    { word: "Lake", translation: "Lago", phonetic: "/leɪk/", category: "Nature", example: "Calm lake.", examplePt: "Lago calmo." },
    { word: "Ocean", translation: "Oceano", phonetic: "/ˈoʊʃn/", category: "Nature", example: "Pacific Ocean.", examplePt: "Oceano Pacífico." },
    { word: "Sea", translation: "Mar", phonetic: "/siː/", category: "Nature", example: "Deep sea.", examplePt: "Mar profundo." },
    { word: "Wave", translation: "Onda", phonetic: "/weɪv/", category: "Nature", example: "Big wave.", examplePt: "Onda grande." },
    { word: "Island", translation: "Ilha", phonetic: "/ˈaɪlənd/", category: "Nature", example: "Tropical island.", examplePt: "Ilha tropical." },
    { word: "Desert", translation: "Deserto", phonetic: "/ˈdezərt/", category: "Nature", example: "Sahara Desert.", examplePt: "Deserto do Saara." },
    { word: "Sand", translation: "Areia", phonetic: "/sænd/", category: "Nature", example: "Beach sand.", examplePt: "Areia da praia." },
    { word: "Rock", translation: "Pedra", phonetic: "/rɑːk/", category: "Nature", example: "Big rock.", examplePt: "Pedra grande." },
    { word: "Waterfall", translation: "Cachoeira", phonetic: "/ˈwɔːtərfɔːl/", category: "Nature", example: "Beautiful waterfall.", examplePt: "Cachoeira bonita." },
    { word: "Volcano", translation: "Vulcão", phonetic: "/vɑːlˈkeɪnoʊ/", category: "Nature", example: "Active volcano.", examplePt: "Vulcão ativo." },
    { word: "Sunny", translation: "Ensolarado", phonetic: "/ˈsʌni/", category: "Weather", example: "Sunny day.", examplePt: "Dia ensolarado." },
    { word: "Cloudy", translation: "Nublado", phonetic: "/ˈklaʊdi/", category: "Weather", example: "Cloudy sky.", examplePt: "Céu nublado." },
    { word: "Rainy", translation: "Chuvoso", phonetic: "/ˈreɪni/", category: "Weather", example: "Rainy weather.", examplePt: "Tempo chuvoso." },
    { word: "Windy", translation: "Ventoso", phonetic: "/ˈwɪndi/", category: "Weather", example: "Windy day.", examplePt: "Dia ventoso." },
    { word: "Snowy", translation: "Nevado", phonetic: "/ˈsnoʊi/", category: "Weather", example: "Snowy winter.", examplePt: "Inverno nevado." },
    { word: "Foggy", translation: "Nebuloso", phonetic: "/ˈfɔːɡi/", category: "Weather", example: "Foggy morning.", examplePt: "Manhã nebulosa." },
    { word: "Thunder", translation: "Trovão", phonetic: "/ˈθʌndər/", category: "Weather", example: "Loud thunder.", examplePt: "Trovão alto." },
    { word: "Lightning", translation: "Relâmpago", phonetic: "/ˈlaɪtnɪŋ/", category: "Weather", example: "Bright lightning.", examplePt: "Relâmpago brilhante." },
    { word: "Rainbow", translation: "Arco-íris", phonetic: "/ˈreɪnboʊ/", category: "Weather", example: "Beautiful rainbow.", examplePt: "Arco-íris bonito." },
    { word: "Spring", translation: "Primavera", phonetic: "/sprɪŋ/", category: "Seasons", example: "Beautiful spring.", examplePt: "Primavera linda." },
    { word: "Summer", translation: "Verão", phonetic: "/ˈsʌmər/", category: "Seasons", example: "Hot summer.", examplePt: "Verão quente." },
    { word: "Autumn", translation: "Outono", phonetic: "/ˈɔːtəm/", category: "Seasons", example: "Colorful autumn.", examplePt: "Outono colorido." },
    { word: "Winter", translation: "Inverno", phonetic: "/ˈwɪntər/", category: "Seasons", example: "Cold winter.", examplePt: "Inverno frio." }
];

console.log('🐾 Animals & Nature loaded:', animalsVocabulary2.length + natureVocabulary2.length, 'words');
