// ===== EXPANDED VOCABULARY - PART 2: VERBS =====
const verbsVocabulary = [
    // ACTION VERBS (100 words)
    { word: "To accept", translation: "Aceitar", phonetic: "/tuː əkˈsept/", category: "Verbs", example: "Accept the offer.", examplePt: "Aceite a oferta." },
    { word: "To add", translation: "Adicionar", phonetic: "/tuː æd/", category: "Verbs", example: "Add more salt.", examplePt: "Adicione mais sal." },
    { word: "To agree", translation: "Concordar", phonetic: "/tuː əˈɡriː/", category: "Verbs", example: "I agree with you.", examplePt: "Eu concordo com você." },
    { word: "To allow", translation: "Permitir", phonetic: "/tuː əˈlaʊ/", category: "Verbs", example: "Allow me to help.", examplePt: "Permita-me ajudar." },
    { word: "To answer", translation: "Responder", phonetic: "/tuː ˈænsər/", category: "Verbs", example: "Answer the question.", examplePt: "Responda a pergunta." },
    { word: "To appear", translation: "Aparecer", phonetic: "/tuː əˈpɪr/", category: "Verbs", example: "He will appear soon.", examplePt: "Ele vai aparecer logo." },
    { word: "To apply", translation: "Aplicar/Candidatar", phonetic: "/tuː əˈplaɪ/", category: "Verbs", example: "Apply for the job.", examplePt: "Candidate-se ao emprego." },
    { word: "To arrive", translation: "Chegar", phonetic: "/tuː əˈraɪv/", category: "Verbs", example: "Arrive on time.", examplePt: "Chegue na hora." },
    { word: "To avoid", translation: "Evitar", phonetic: "/tuː əˈvɔɪd/", category: "Verbs", example: "Avoid mistakes.", examplePt: "Evite erros." },
    { word: "To become", translation: "Tornar-se", phonetic: "/tuː bɪˈkʌm/", category: "Verbs", example: "Become better.", examplePt: "Torne-se melhor." },
    { word: "To begin", translation: "Começar", phonetic: "/tuː bɪˈɡɪn/", category: "Verbs", example: "Begin the class.", examplePt: "Comece a aula." },
    { word: "To believe", translation: "Acreditar", phonetic: "/tuː bɪˈliːv/", category: "Verbs", example: "I believe you.", examplePt: "Eu acredito em você." },
    { word: "To belong", translation: "Pertencer", phonetic: "/tuː bɪˈlɔːŋ/", category: "Verbs", example: "This belongs to me.", examplePt: "Isso pertence a mim." },
    { word: "To break", translation: "Quebrar", phonetic: "/tuː breɪk/", category: "Verbs", example: "Don't break it.", examplePt: "Não quebre." },
    { word: "To bring", translation: "Trazer", phonetic: "/tuː brɪŋ/", category: "Verbs", example: "Bring your book.", examplePt: "Traga seu livro." },
    { word: "To build", translation: "Construir", phonetic: "/tuː bɪld/", category: "Verbs", example: "Build a house.", examplePt: "Construir uma casa." },
    { word: "To burn", translation: "Queimar", phonetic: "/tuː bɜːrn/", category: "Verbs", example: "Don't burn it.", examplePt: "Não queime." },
    { word: "To call", translation: "Chamar/Ligar", phonetic: "/tuː kɔːl/", category: "Verbs", example: "Call me later.", examplePt: "Me ligue depois." },
    { word: "To carry", translation: "Carregar", phonetic: "/tuː ˈkæri/", category: "Verbs", example: "Carry the bags.", examplePt: "Carregue as malas." },
    { word: "To catch", translation: "Pegar/Capturar", phonetic: "/tuː kætʃ/", category: "Verbs", example: "Catch the ball.", examplePt: "Pegue a bola." },
    { word: "To change", translation: "Mudar", phonetic: "/tuː tʃeɪndʒ/", category: "Verbs", example: "Change your clothes.", examplePt: "Troque de roupa." },
    { word: "To check", translation: "Verificar", phonetic: "/tuː tʃek/", category: "Verbs", example: "Check the email.", examplePt: "Verifique o email." },
    { word: "To choose", translation: "Escolher", phonetic: "/tuː tʃuːz/", category: "Verbs", example: "Choose wisely.", examplePt: "Escolha sabiamente." },
    { word: "To clean", translation: "Limpar", phonetic: "/tuː kliːn/", category: "Verbs", example: "Clean the house.", examplePt: "Limpe a casa." },
    { word: "To climb", translation: "Escalar/Subir", phonetic: "/tuː klaɪm/", category: "Verbs", example: "Climb the mountain.", examplePt: "Escale a montanha." },
    { word: "To collect", translation: "Colecionar/Coletar", phonetic: "/tuː kəˈlekt/", category: "Verbs", example: "Collect stamps.", examplePt: "Colecionar selos." },
    { word: "To compare", translation: "Comparar", phonetic: "/tuː kəmˈper/", category: "Verbs", example: "Compare prices.", examplePt: "Compare preços." },
    { word: "To complete", translation: "Completar", phonetic: "/tuː kəmˈpliːt/", category: "Verbs", example: "Complete the task.", examplePt: "Complete a tarefa." },
    { word: "To connect", translation: "Conectar", phonetic: "/tuː kəˈnekt/", category: "Verbs", example: "Connect to WiFi.", examplePt: "Conecte ao WiFi." },
    { word: "To consider", translation: "Considerar", phonetic: "/tuː kənˈsɪdər/", category: "Verbs", example: "Consider the options.", examplePt: "Considere as opções." },
    { word: "To continue", translation: "Continuar", phonetic: "/tuː kənˈtɪnjuː/", category: "Verbs", example: "Continue working.", examplePt: "Continue trabalhando." },
    { word: "To cook", translation: "Cozinhar", phonetic: "/tuː kʊk/", category: "Verbs", example: "Cook dinner.", examplePt: "Cozinhar o jantar." },
    { word: "To copy", translation: "Copiar", phonetic: "/tuː ˈkɑːpi/", category: "Verbs", example: "Copy the text.", examplePt: "Copie o texto." },
    { word: "To count", translation: "Contar", phonetic: "/tuː kaʊnt/", category: "Verbs", example: "Count to ten.", examplePt: "Conte até dez." },
    { word: "To cover", translation: "Cobrir", phonetic: "/tuː ˈkʌvər/", category: "Verbs", example: "Cover the food.", examplePt: "Cubra a comida." },
    { word: "To create", translation: "Criar", phonetic: "/tuː kriˈeɪt/", category: "Verbs", example: "Create something new.", examplePt: "Crie algo novo." },
    { word: "To cross", translation: "Atravessar", phonetic: "/tuː krɔːs/", category: "Verbs", example: "Cross the street.", examplePt: "Atravesse a rua." },
    { word: "To cry", translation: "Chorar", phonetic: "/tuː kraɪ/", category: "Verbs", example: "Don't cry.", examplePt: "Não chore." },
    { word: "To cut", translation: "Cortar", phonetic: "/tuː kʌt/", category: "Verbs", example: "Cut the paper.", examplePt: "Corte o papel." },
    { word: "To dance", translation: "Dançar", phonetic: "/tuː dæns/", category: "Verbs", example: "Dance with me.", examplePt: "Dance comigo." },
    { word: "To decide", translation: "Decidir", phonetic: "/tuː dɪˈsaɪd/", category: "Verbs", example: "Decide now.", examplePt: "Decida agora." },
    { word: "To deliver", translation: "Entregar", phonetic: "/tuː dɪˈlɪvər/", category: "Verbs", example: "Deliver the package.", examplePt: "Entregue o pacote." },
    { word: "To describe", translation: "Descrever", phonetic: "/tuː dɪˈskraɪb/", category: "Verbs", example: "Describe the scene.", examplePt: "Descreva a cena." },
    { word: "To design", translation: "Projetar/Desenhar", phonetic: "/tuː dɪˈzaɪn/", category: "Verbs", example: "Design a logo.", examplePt: "Desenhe um logo." },
    { word: "To destroy", translation: "Destruir", phonetic: "/tuː dɪˈstrɔɪ/", category: "Verbs", example: "Don't destroy it.", examplePt: "Não destrua." },
    { word: "To develop", translation: "Desenvolver", phonetic: "/tuː dɪˈveləp/", category: "Verbs", example: "Develop skills.", examplePt: "Desenvolva habilidades." },
    { word: "To die", translation: "Morrer", phonetic: "/tuː daɪ/", category: "Verbs", example: "Flowers die.", examplePt: "Flores morrem." },
    { word: "To discover", translation: "Descobrir", phonetic: "/tuː dɪˈskʌvər/", category: "Verbs", example: "Discover new places.", examplePt: "Descubra novos lugares." },
    { word: "To discuss", translation: "Discutir", phonetic: "/tuː dɪˈskʌs/", category: "Verbs", example: "Discuss the problem.", examplePt: "Discuta o problema." },
    { word: "To divide", translation: "Dividir", phonetic: "/tuː dɪˈvaɪd/", category: "Verbs", example: "Divide equally.", examplePt: "Divida igualmente." },
    { word: "To draw", translation: "Desenhar", phonetic: "/tuː drɔː/", category: "Verbs", example: "Draw a picture.", examplePt: "Desenhe uma imagem." },
    { word: "To dream", translation: "Sonhar", phonetic: "/tuː driːm/", category: "Verbs", example: "Dream big.", examplePt: "Sonhe grande." },
    { word: "To dress", translation: "Vestir", phonetic: "/tuː dres/", category: "Verbs", example: "Dress nicely.", examplePt: "Vista-se bem." },
    { word: "To drive", translation: "Dirigir", phonetic: "/tuː draɪv/", category: "Verbs", example: "Drive carefully.", examplePt: "Dirija com cuidado." },
    { word: "To drop", translation: "Derrubar/Largar", phonetic: "/tuː drɑːp/", category: "Verbs", example: "Don't drop it.", examplePt: "Não deixe cair." },
    { word: "To earn", translation: "Ganhar", phonetic: "/tuː ɜːrn/", category: "Verbs", example: "Earn money.", examplePt: "Ganhe dinheiro." },
    { word: "To enjoy", translation: "Aproveitar", phonetic: "/tuː ɪnˈdʒɔɪ/", category: "Verbs", example: "Enjoy life.", examplePt: "Aproveite a vida." },
    { word: "To enter", translation: "Entrar", phonetic: "/tuː ˈentər/", category: "Verbs", example: "Enter the room.", examplePt: "Entre na sala." },
    { word: "To escape", translation: "Escapar", phonetic: "/tuː ɪˈskeɪp/", category: "Verbs", example: "Escape danger.", examplePt: "Escape do perigo." },
    { word: "To examine", translation: "Examinar", phonetic: "/tuː ɪɡˈzæmɪn/", category: "Verbs", example: "Examine closely.", examplePt: "Examine de perto." },
    { word: "To exist", translation: "Existir", phonetic: "/tuː ɪɡˈzɪst/", category: "Verbs", example: "Dreams exist.", examplePt: "Sonhos existem." },
    { word: "To expect", translation: "Esperar/Expectar", phonetic: "/tuː ɪkˈspekt/", category: "Verbs", example: "Expect the best.", examplePt: "Espere o melhor." },
    { word: "To explain", translation: "Explicar", phonetic: "/tuː ɪkˈspleɪn/", category: "Verbs", example: "Explain clearly.", examplePt: "Explique claramente." },
    { word: "To express", translation: "Expressar", phonetic: "/tuː ɪkˈspres/", category: "Verbs", example: "Express yourself.", examplePt: "Expresse-se." },
    { word: "To fail", translation: "Falhar", phonetic: "/tuː feɪl/", category: "Verbs", example: "Don't fail.", examplePt: "Não falhe." },
    { word: "To fall", translation: "Cair", phonetic: "/tuː fɔːl/", category: "Verbs", example: "Don't fall.", examplePt: "Não caia." },
    { word: "To feed", translation: "Alimentar", phonetic: "/tuː fiːd/", category: "Verbs", example: "Feed the dog.", examplePt: "Alimente o cachorro." },
    { word: "To feel", translation: "Sentir", phonetic: "/tuː fiːl/", category: "Verbs", example: "Feel better.", examplePt: "Sinta-se melhor." },
    { word: "To fight", translation: "Lutar", phonetic: "/tuː faɪt/", category: "Verbs", example: "Fight for justice.", examplePt: "Lute por justiça." },
    { word: "To fill", translation: "Preencher/Encher", phonetic: "/tuː fɪl/", category: "Verbs", example: "Fill the glass.", examplePt: "Encha o copo." },
    { word: "To finish", translation: "Terminar", phonetic: "/tuː ˈfɪnɪʃ/", category: "Verbs", example: "Finish the work.", examplePt: "Termine o trabalho." },
    { word: "To fit", translation: "Servir/Caber", phonetic: "/tuː fɪt/", category: "Verbs", example: "It fits well.", examplePt: "Serve bem." },
    { word: "To fix", translation: "Consertar", phonetic: "/tuː fɪks/", category: "Verbs", example: "Fix the problem.", examplePt: "Conserte o problema." },
    { word: "To fly", translation: "Voar", phonetic: "/tuː flaɪ/", category: "Verbs", example: "Birds fly.", examplePt: "Pássaros voam." },
    { word: "To follow", translation: "Seguir", phonetic: "/tuː ˈfɑːloʊ/", category: "Verbs", example: "Follow me.", examplePt: "Siga-me." },
    { word: "To force", translation: "Forçar", phonetic: "/tuː fɔːrs/", category: "Verbs", example: "Don't force it.", examplePt: "Não force." },
    { word: "To forget", translation: "Esquecer", phonetic: "/tuː fərˈɡet/", category: "Verbs", example: "Don't forget.", examplePt: "Não esqueça." },
    { word: "To forgive", translation: "Perdoar", phonetic: "/tuː fərˈɡɪv/", category: "Verbs", example: "Forgive me.", examplePt: "Me perdoe." },
    { word: "To freeze", translation: "Congelar", phonetic: "/tuː friːz/", category: "Verbs", example: "Water freezes.", examplePt: "Água congela." },
    { word: "To gain", translation: "Ganhar/Obter", phonetic: "/tuː ɡeɪn/", category: "Verbs", example: "Gain experience.", examplePt: "Ganhe experiência." },
    { word: "To gather", translation: "Reunir", phonetic: "/tuː ˈɡæðər/", category: "Verbs", example: "Gather information.", examplePt: "Reúna informações." },
    { word: "To generate", translation: "Gerar", phonetic: "/tuː ˈdʒenəreɪt/", category: "Verbs", example: "Generate ideas.", examplePt: "Gere ideias." },
    { word: "To grab", translation: "Agarrar", phonetic: "/tuː ɡræb/", category: "Verbs", example: "Grab a coffee.", examplePt: "Pegue um café." },
    { word: "To grow", translation: "Crescer", phonetic: "/tuː ɡroʊ/", category: "Verbs", example: "Plants grow.", examplePt: "Plantas crescem." },
    { word: "To guess", translation: "Adivinhar", phonetic: "/tuː ɡes/", category: "Verbs", example: "Guess the answer.", examplePt: "Adivinhe a resposta." },
    { word: "To guide", translation: "Guiar", phonetic: "/tuː ɡaɪd/", category: "Verbs", example: "Guide the team.", examplePt: "Guie a equipe." },
    { word: "To hang", translation: "Pendurar", phonetic: "/tuː hæŋ/", category: "Verbs", example: "Hang the picture.", examplePt: "Pendure a foto." },
    { word: "To happen", translation: "Acontecer", phonetic: "/tuː ˈhæpən/", category: "Verbs", example: "Things happen.", examplePt: "Coisas acontecem." },
    { word: "To hate", translation: "Odiar", phonetic: "/tuː heɪt/", category: "Verbs", example: "Don't hate.", examplePt: "Não odeie." },
    { word: "To hear", translation: "Ouvir", phonetic: "/tuː hɪr/", category: "Verbs", example: "I can hear you.", examplePt: "Posso ouvi-lo." },
    { word: "To hide", translation: "Esconder", phonetic: "/tuː haɪd/", category: "Verbs", example: "Hide and seek.", examplePt: "Esconde-esconde." },
    { word: "To hire", translation: "Contratar", phonetic: "/tuː ˈhaɪər/", category: "Verbs", example: "Hire employees.", examplePt: "Contrate funcionários." },
    { word: "To hit", translation: "Bater/Acertar", phonetic: "/tuː hɪt/", category: "Verbs", example: "Hit the target.", examplePt: "Acerte o alvo." },
    { word: "To hold", translation: "Segurar", phonetic: "/tuː hoʊld/", category: "Verbs", example: "Hold my hand.", examplePt: "Segure minha mão." },
    { word: "To hope", translation: "Esperar/Ter esperança", phonetic: "/tuː hoʊp/", category: "Verbs", example: "I hope so.", examplePt: "Espero que sim." },
    { word: "To hunt", translation: "Caçar", phonetic: "/tuː hʌnt/", category: "Verbs", example: "Hunt for food.", examplePt: "Caçar comida." },
    { word: "To hurry", translation: "Apressar-se", phonetic: "/tuː ˈhʌri/", category: "Verbs", example: "Hurry up!", examplePt: "Apresse-se!" },
    { word: "To hurt", translation: "Machucar", phonetic: "/tuː hɜːrt/", category: "Verbs", example: "It hurts.", examplePt: "Dói." },
    { word: "To identify", translation: "Identificar", phonetic: "/tuː aɪˈdentɪfaɪ/", category: "Verbs", example: "Identify the problem.", examplePt: "Identifique o problema." },
    { word: "To ignore", translation: "Ignorar", phonetic: "/tuː ɪɡˈnɔːr/", category: "Verbs", example: "Don't ignore me.", examplePt: "Não me ignore." },
    { word: "To imagine", translation: "Imaginar", phonetic: "/tuː ɪˈmædʒɪn/", category: "Verbs", example: "Imagine that.", examplePt: "Imagine isso." },
    { word: "To improve", translation: "Melhorar", phonetic: "/tuː ɪmˈpruːv/", category: "Verbs", example: "Improve yourself.", examplePt: "Melhore-se." },
    { word: "To include", translation: "Incluir", phonetic: "/tuː ɪnˈkluːd/", category: "Verbs", example: "Include everyone.", examplePt: "Inclua todos." },
    { word: "To increase", translation: "Aumentar", phonetic: "/tuː ɪnˈkriːs/", category: "Verbs", example: "Increase sales.", examplePt: "Aumente as vendas." },
    { word: "To influence", translation: "Influenciar", phonetic: "/tuː ˈɪnfluəns/", category: "Verbs", example: "Influence others.", examplePt: "Influencie outros." },
    { word: "To inform", translation: "Informar", phonetic: "/tuː ɪnˈfɔːrm/", category: "Verbs", example: "Inform me.", examplePt: "Me informe." },
    { word: "To insist", translation: "Insistir", phonetic: "/tuː ɪnˈsɪst/", category: "Verbs", example: "I insist.", examplePt: "Eu insisto." },
    { word: "To install", translation: "Instalar", phonetic: "/tuː ɪnˈstɔːl/", category: "Verbs", example: "Install the app.", examplePt: "Instale o app." },
    { word: "To introduce", translation: "Apresentar", phonetic: "/tuː ˌɪntrəˈduːs/", category: "Verbs", example: "Let me introduce.", examplePt: "Deixe-me apresentar." },
    { word: "To invent", translation: "Inventar", phonetic: "/tuː ɪnˈvent/", category: "Verbs", example: "Invent something.", examplePt: "Invente algo." },
    { word: "To invest", translation: "Investir", phonetic: "/tuː ɪnˈvest/", category: "Verbs", example: "Invest wisely.", examplePt: "Invista sabiamente." },
    { word: "To invite", translation: "Convidar", phonetic: "/tuː ɪnˈvaɪt/", category: "Verbs", example: "Invite friends.", examplePt: "Convide amigos." },
    { word: "To involve", translation: "Envolver", phonetic: "/tuː ɪnˈvɑːlv/", category: "Verbs", example: "Involve everyone.", examplePt: "Envolva todos." },
    { word: "To join", translation: "Juntar-se", phonetic: "/tuː dʒɔɪn/", category: "Verbs", example: "Join us.", examplePt: "Junte-se a nós." },
    { word: "To judge", translation: "Julgar", phonetic: "/tuː dʒʌdʒ/", category: "Verbs", example: "Don't judge.", examplePt: "Não julgue." },
    { word: "To jump", translation: "Pular", phonetic: "/tuː dʒʌmp/", category: "Verbs", example: "Jump high.", examplePt: "Pule alto." },
    { word: "To keep", translation: "Manter/Guardar", phonetic: "/tuː kiːp/", category: "Verbs", example: "Keep trying.", examplePt: "Continue tentando." },
    { word: "To kick", translation: "Chutar", phonetic: "/tuː kɪk/", category: "Verbs", example: "Kick the ball.", examplePt: "Chute a bola." },
    { word: "To kill", translation: "Matar", phonetic: "/tuː kɪl/", category: "Verbs", example: "Kill time.", examplePt: "Matar tempo." },
    { word: "To kiss", translation: "Beijar", phonetic: "/tuː kɪs/", category: "Verbs", example: "Kiss me.", examplePt: "Me beije." },
    { word: "To knock", translation: "Bater (porta)", phonetic: "/tuː nɑːk/", category: "Verbs", example: "Knock on the door.", examplePt: "Bata na porta." },
    { word: "To lack", translation: "Faltar", phonetic: "/tuː læk/", category: "Verbs", example: "Lack experience.", examplePt: "Falta experiência." },
    { word: "To last", translation: "Durar", phonetic: "/tuː læst/", category: "Verbs", example: "It will last.", examplePt: "Vai durar." },
    { word: "To laugh", translation: "Rir", phonetic: "/tuː læf/", category: "Verbs", example: "Laugh more.", examplePt: "Ria mais." },
    { word: "To launch", translation: "Lançar", phonetic: "/tuː lɔːntʃ/", category: "Verbs", example: "Launch the product.", examplePt: "Lance o produto." },
    { word: "To lay", translation: "Deitar/Colocar", phonetic: "/tuː leɪ/", category: "Verbs", example: "Lay down.", examplePt: "Deite-se." },
    { word: "To lead", translation: "Liderar", phonetic: "/tuː liːd/", category: "Verbs", example: "Lead the team.", examplePt: "Lidere a equipe." },
    { word: "To lean", translation: "Inclinar", phonetic: "/tuː liːn/", category: "Verbs", example: "Lean forward.", examplePt: "Incline-se para frente." },
    { word: "To leave", translation: "Sair/Deixar", phonetic: "/tuː liːv/", category: "Verbs", example: "Leave now.", examplePt: "Saia agora." },
    { word: "To lend", translation: "Emprestar", phonetic: "/tuː lend/", category: "Verbs", example: "Lend me money.", examplePt: "Me empreste dinheiro." },
    { word: "To let", translation: "Deixar/Permitir", phonetic: "/tuː let/", category: "Verbs", example: "Let me go.", examplePt: "Me deixe ir." },
    { word: "To lie", translation: "Mentir/Deitar", phonetic: "/tuː laɪ/", category: "Verbs", example: "Don't lie.", examplePt: "Não minta." },
    { word: "To lift", translation: "Levantar", phonetic: "/tuː lɪft/", category: "Verbs", example: "Lift weights.", examplePt: "Levante pesos." },
    { word: "To light", translation: "Acender", phonetic: "/tuː laɪt/", category: "Verbs", example: "Light a candle.", examplePt: "Acenda uma vela." },
    { word: "To limit", translation: "Limitar", phonetic: "/tuː ˈlɪmɪt/", category: "Verbs", example: "Limit expenses.", examplePt: "Limite gastos." },
    { word: "To link", translation: "Conectar/Ligar", phonetic: "/tuː lɪŋk/", category: "Verbs", example: "Link accounts.", examplePt: "Conecte contas." },
    { word: "To live", translation: "Viver", phonetic: "/tuː lɪv/", category: "Verbs", example: "Live well.", examplePt: "Viva bem." },
    { word: "To load", translation: "Carregar", phonetic: "/tuː loʊd/", category: "Verbs", example: "Load the truck.", examplePt: "Carregue o caminhão." },
    { word: "To lock", translation: "Trancar", phonetic: "/tuː lɑːk/", category: "Verbs", example: "Lock the door.", examplePt: "Tranque a porta." },
    { word: "To look", translation: "Olhar", phonetic: "/tuː lʊk/", category: "Verbs", example: "Look here.", examplePt: "Olhe aqui." },
    { word: "To lose", translation: "Perder", phonetic: "/tuː luːz/", category: "Verbs", example: "Don't lose hope.", examplePt: "Não perca a esperança." },
    { word: "To maintain", translation: "Manter", phonetic: "/tuː meɪnˈteɪn/", category: "Verbs", example: "Maintain quality.", examplePt: "Mantenha qualidade." },
    { word: "To manage", translation: "Gerenciar", phonetic: "/tuː ˈmænɪdʒ/", category: "Verbs", example: "Manage time.", examplePt: "Gerencie tempo." },
    { word: "To mark", translation: "Marcar", phonetic: "/tuː mɑːrk/", category: "Verbs", example: "Mark the date.", examplePt: "Marque a data." },
    { word: "To match", translation: "Combinar", phonetic: "/tuː mætʃ/", category: "Verbs", example: "Colors match.", examplePt: "Cores combinam." },
    { word: "To matter", translation: "Importar", phonetic: "/tuː ˈmætər/", category: "Verbs", example: "It matters.", examplePt: "Importa." },
    { word: "To measure", translation: "Medir", phonetic: "/tuː ˈmeʒər/", category: "Verbs", example: "Measure twice.", examplePt: "Meça duas vezes." },
    { word: "To meet", translation: "Encontrar/Conhecer", phonetic: "/tuː miːt/", category: "Verbs", example: "Nice to meet you.", examplePt: "Prazer em conhecer." },
    { word: "To mention", translation: "Mencionar", phonetic: "/tuː ˈmenʃn/", category: "Verbs", example: "Don't mention it.", examplePt: "Não há de quê." },
    { word: "To mind", translation: "Importar-se", phonetic: "/tuː maɪnd/", category: "Verbs", example: "Do you mind?", examplePt: "Você se importa?" },
    { word: "To miss", translation: "Sentir falta/Perder", phonetic: "/tuː mɪs/", category: "Verbs", example: "I miss you.", examplePt: "Sinto sua falta." },
    { word: "To mix", translation: "Misturar", phonetic: "/tuː mɪks/", category: "Verbs", example: "Mix well.", examplePt: "Misture bem." },
    { word: "To move", translation: "Mover/Mudar", phonetic: "/tuː muːv/", category: "Verbs", example: "Move forward.", examplePt: "Mova-se para frente." }
];
