// ===== EXPANDED VOCABULARY - PART 3: MORE VERBS & ADJECTIVES =====
const verbsVocabulary2 = [
    // MORE ACTION VERBS N-Z (70 words)
    { word: "To name", translation: "Nomear", phonetic: "/tuː neɪm/", category: "Verbs", example: "Name the baby.", examplePt: "Dê nome ao bebê." },
    { word: "To need", translation: "Precisar", phonetic: "/tuː niːd/", category: "Verbs", example: "I need help.", examplePt: "Preciso de ajuda." },
    { word: "To notice", translation: "Notar", phonetic: "/tuː ˈnoʊtɪs/", category: "Verbs", example: "Notice the difference.", examplePt: "Note a diferença." },
    { word: "To obtain", translation: "Obter", phonetic: "/tuː əbˈteɪn/", category: "Verbs", example: "Obtain permission.", examplePt: "Obtenha permissão." },
    { word: "To occur", translation: "Ocorrer", phonetic: "/tuː əˈkɜːr/", category: "Verbs", example: "Problems occur.", examplePt: "Problemas ocorrem." },
    { word: "To offer", translation: "Oferecer", phonetic: "/tuː ˈɔːfər/", category: "Verbs", example: "Offer help.", examplePt: "Ofereça ajuda." },
    { word: "To open", translation: "Abrir", phonetic: "/tuː ˈoʊpən/", category: "Verbs", example: "Open the door.", examplePt: "Abra a porta." },
    { word: "To order", translation: "Pedir/Ordenar", phonetic: "/tuː ˈɔːrdər/", category: "Verbs", example: "Order food.", examplePt: "Peça comida." },
    { word: "To organize", translation: "Organizar", phonetic: "/tuː ˈɔːrɡənaɪz/", category: "Verbs", example: "Organize events.", examplePt: "Organize eventos." },
    { word: "To own", translation: "Possuir", phonetic: "/tuː oʊn/", category: "Verbs", example: "Own a house.", examplePt: "Possua uma casa." },
    { word: "To pack", translation: "Embalar/Fazer malas", phonetic: "/tuː pæk/", category: "Verbs", example: "Pack your bags.", examplePt: "Faça suas malas." },
    { word: "To paint", translation: "Pintar", phonetic: "/tuː peɪnt/", category: "Verbs", example: "Paint the wall.", examplePt: "Pinte a parede." },
    { word: "To park", translation: "Estacionar", phonetic: "/tuː pɑːrk/", category: "Verbs", example: "Park the car.", examplePt: "Estacione o carro." },
    { word: "To participate", translation: "Participar", phonetic: "/tuː pɑːrˈtɪsɪpeɪt/", category: "Verbs", example: "Participate actively.", examplePt: "Participe ativamente." },
    { word: "To pass", translation: "Passar", phonetic: "/tuː pæs/", category: "Verbs", example: "Pass the test.", examplePt: "Passe no teste." },
    { word: "To pause", translation: "Pausar", phonetic: "/tuː pɔːz/", category: "Verbs", example: "Pause the video.", examplePt: "Pause o vídeo." },
    { word: "To perform", translation: "Executar/Atuar", phonetic: "/tuː pərˈfɔːrm/", category: "Verbs", example: "Perform well.", examplePt: "Desempenhe bem." },
    { word: "To permit", translation: "Permitir", phonetic: "/tuː pərˈmɪt/", category: "Verbs", example: "Permit access.", examplePt: "Permita acesso." },
    { word: "To place", translation: "Colocar", phonetic: "/tuː pleɪs/", category: "Verbs", example: "Place here.", examplePt: "Coloque aqui." },
    { word: "To plan", translation: "Planejar", phonetic: "/tuː plæn/", category: "Verbs", example: "Plan ahead.", examplePt: "Planeje com antecedência." },
    { word: "To plant", translation: "Plantar", phonetic: "/tuː plænt/", category: "Verbs", example: "Plant trees.", examplePt: "Plante árvores." },
    { word: "To play", translation: "Jogar/Brincar", phonetic: "/tuː pleɪ/", category: "Verbs", example: "Play games.", examplePt: "Jogue jogos." },
    { word: "To please", translation: "Agradar", phonetic: "/tuː pliːz/", category: "Verbs", example: "Please everyone.", examplePt: "Agrade a todos." },
    { word: "To point", translation: "Apontar", phonetic: "/tuː pɔɪnt/", category: "Verbs", example: "Point at it.", examplePt: "Aponte para isso." },
    { word: "To post", translation: "Postar", phonetic: "/tuː poʊst/", category: "Verbs", example: "Post online.", examplePt: "Poste online." },
    { word: "To pour", translation: "Derramar/Servir", phonetic: "/tuː pɔːr/", category: "Verbs", example: "Pour water.", examplePt: "Sirva água." },
    { word: "To practice", translation: "Praticar", phonetic: "/tuː ˈpræktɪs/", category: "Verbs", example: "Practice daily.", examplePt: "Pratique diariamente." },
    { word: "To predict", translation: "Prever", phonetic: "/tuː prɪˈdɪkt/", category: "Verbs", example: "Predict the future.", examplePt: "Preveja o futuro." },
    { word: "To prefer", translation: "Preferir", phonetic: "/tuː prɪˈfɜːr/", category: "Verbs", example: "I prefer tea.", examplePt: "Prefiro chá." },
    { word: "To prepare", translation: "Preparar", phonetic: "/tuː prɪˈper/", category: "Verbs", example: "Prepare food.", examplePt: "Prepare comida." },
    { word: "To present", translation: "Apresentar", phonetic: "/tuː prɪˈzent/", category: "Verbs", example: "Present ideas.", examplePt: "Apresente ideias." },
    { word: "To press", translation: "Pressionar", phonetic: "/tuː pres/", category: "Verbs", example: "Press the button.", examplePt: "Pressione o botão." },
    { word: "To prevent", translation: "Prevenir", phonetic: "/tuː prɪˈvent/", category: "Verbs", example: "Prevent problems.", examplePt: "Previna problemas." },
    { word: "To print", translation: "Imprimir", phonetic: "/tuː prɪnt/", category: "Verbs", example: "Print documents.", examplePt: "Imprima documentos." },
    { word: "To produce", translation: "Produzir", phonetic: "/tuː prəˈduːs/", category: "Verbs", example: "Produce quality.", examplePt: "Produza qualidade." },
    { word: "To promise", translation: "Prometer", phonetic: "/tuː ˈprɑːmɪs/", category: "Verbs", example: "I promise.", examplePt: "Eu prometo." },
    { word: "To protect", translation: "Proteger", phonetic: "/tuː prəˈtekt/", category: "Verbs", example: "Protect nature.", examplePt: "Proteja a natureza." },
    { word: "To prove", translation: "Provar", phonetic: "/tuː pruːv/", category: "Verbs", example: "Prove it.", examplePt: "Prove isso." },
    { word: "To provide", translation: "Fornecer", phonetic: "/tuː prəˈvaɪd/", category: "Verbs", example: "Provide service.", examplePt: "Forneça serviço." },
    { word: "To publish", translation: "Publicar", phonetic: "/tuː ˈpʌblɪʃ/", category: "Verbs", example: "Publish content.", examplePt: "Publique conteúdo." },
    { word: "To pull", translation: "Puxar", phonetic: "/tuː pʊl/", category: "Verbs", example: "Pull the rope.", examplePt: "Puxe a corda." },
    { word: "To push", translation: "Empurrar", phonetic: "/tuː pʊʃ/", category: "Verbs", example: "Push the door.", examplePt: "Empurre a porta." },
    { word: "To quit", translation: "Desistir/Sair", phonetic: "/tuː kwɪt/", category: "Verbs", example: "Quit smoking.", examplePt: "Pare de fumar." },
    { word: "To raise", translation: "Levantar/Criar", phonetic: "/tuː reɪz/", category: "Verbs", example: "Raise your hand.", examplePt: "Levante a mão." },
    { word: "To reach", translation: "Alcançar", phonetic: "/tuː riːtʃ/", category: "Verbs", example: "Reach your goals.", examplePt: "Alcance seus objetivos." },
    { word: "To react", translation: "Reagir", phonetic: "/tuː riˈækt/", category: "Verbs", example: "Don't react.", examplePt: "Não reaja." },
    { word: "To realize", translation: "Perceber/Realizar", phonetic: "/tuː ˈriːəlaɪz/", category: "Verbs", example: "Realize dreams.", examplePt: "Realize sonhos." },
    { word: "To receive", translation: "Receber", phonetic: "/tuː rɪˈsiːv/", category: "Verbs", example: "Receive gifts.", examplePt: "Receba presentes." },
    { word: "To recognize", translation: "Reconhecer", phonetic: "/tuː ˈrekəɡnaɪz/", category: "Verbs", example: "Recognize faces.", examplePt: "Reconheça rostos." },
    { word: "To recommend", translation: "Recomendar", phonetic: "/tuː ˌrekəˈmend/", category: "Verbs", example: "I recommend this.", examplePt: "Eu recomendo isto." },
    { word: "To record", translation: "Gravar", phonetic: "/tuː rɪˈkɔːrd/", category: "Verbs", example: "Record audio.", examplePt: "Grave áudio." },
    { word: "To recover", translation: "Recuperar", phonetic: "/tuː rɪˈkʌvər/", category: "Verbs", example: "Recover quickly.", examplePt: "Recupere-se rapidamente." },
    { word: "To reduce", translation: "Reduzir", phonetic: "/tuː rɪˈduːs/", category: "Verbs", example: "Reduce costs.", examplePt: "Reduza custos." },
    { word: "To reflect", translation: "Refletir", phonetic: "/tuː rɪˈflekt/", category: "Verbs", example: "Reflect on life.", examplePt: "Reflita sobre a vida." },
    { word: "To refuse", translation: "Recusar", phonetic: "/tuː rɪˈfjuːz/", category: "Verbs", example: "Refuse to quit.", examplePt: "Recuse desistir." },
    { word: "To regret", translation: "Arrepender-se", phonetic: "/tuː rɪˈɡret/", category: "Verbs", example: "Don't regret.", examplePt: "Não se arrependa." },
    { word: "To relax", translation: "Relaxar", phonetic: "/tuː rɪˈlæks/", category: "Verbs", example: "Just relax.", examplePt: "Apenas relaxe." },
    { word: "To release", translation: "Liberar", phonetic: "/tuː rɪˈliːs/", category: "Verbs", example: "Release tension.", examplePt: "Libere tensão." },
    { word: "To remain", translation: "Permanecer", phonetic: "/tuː rɪˈmeɪn/", category: "Verbs", example: "Remain calm.", examplePt: "Permaneça calmo." },
    { word: "To remember", translation: "Lembrar", phonetic: "/tuː rɪˈmembər/", category: "Verbs", example: "Remember me.", examplePt: "Lembre de mim." },
    { word: "To remind", translation: "Lembrar alguém", phonetic: "/tuː rɪˈmaɪnd/", category: "Verbs", example: "Remind me.", examplePt: "Me lembre." },
    { word: "To remove", translation: "Remover", phonetic: "/tuː rɪˈmuːv/", category: "Verbs", example: "Remove it.", examplePt: "Remova isso." },
    { word: "To rent", translation: "Alugar", phonetic: "/tuː rent/", category: "Verbs", example: "Rent a car.", examplePt: "Alugue um carro." },
    { word: "To repair", translation: "Reparar", phonetic: "/tuː rɪˈper/", category: "Verbs", example: "Repair the damage.", examplePt: "Repare o dano." },
    { word: "To repeat", translation: "Repetir", phonetic: "/tuː rɪˈpiːt/", category: "Verbs", example: "Repeat after me.", examplePt: "Repita depois de mim." },
    { word: "To replace", translation: "Substituir", phonetic: "/tuː rɪˈpleɪs/", category: "Verbs", example: "Replace parts.", examplePt: "Substitua peças." },
    { word: "To reply", translation: "Responder", phonetic: "/tuː rɪˈplaɪ/", category: "Verbs", example: "Reply soon.", examplePt: "Responda logo." },
    { word: "To require", translation: "Exigir", phonetic: "/tuː rɪˈkwaɪər/", category: "Verbs", example: "It requires effort.", examplePt: "Exige esforço." },
    { word: "To research", translation: "Pesquisar", phonetic: "/tuː rɪˈsɜːrtʃ/", category: "Verbs", example: "Research topics.", examplePt: "Pesquise tópicos." },
    { word: "To respect", translation: "Respeitar", phonetic: "/tuː rɪˈspekt/", category: "Verbs", example: "Respect others.", examplePt: "Respeite os outros." }
];

const adjectivesVocabulary = [
    // DESCRIBING PEOPLE (50 words)
    { word: "Beautiful", translation: "Bonito(a)", phonetic: "/ˈbjuːtɪfl/", category: "Appearance", example: "Beautiful woman.", examplePt: "Mulher bonita." },
    { word: "Handsome", translation: "Bonito (homem)", phonetic: "/ˈhænsəm/", category: "Appearance", example: "Handsome man.", examplePt: "Homem bonito." },
    { word: "Pretty", translation: "Bonita", phonetic: "/ˈprɪti/", category: "Appearance", example: "Pretty girl.", examplePt: "Menina bonita." },
    { word: "Ugly", translation: "Feio", phonetic: "/ˈʌɡli/", category: "Appearance", example: "Ugly monster.", examplePt: "Monstro feio." },
    { word: "Thin", translation: "Magro", phonetic: "/θɪn/", category: "Appearance", example: "Thin body.", examplePt: "Corpo magro." },
    { word: "Fat", translation: "Gordo", phonetic: "/fæt/", category: "Appearance", example: "Fat cat.", examplePt: "Gato gordo." },
    { word: "Slim", translation: "Esbelto", phonetic: "/slɪm/", category: "Appearance", example: "Slim figure.", examplePt: "Figura esbelta." },
    { word: "Short", translation: "Baixo/Curto", phonetic: "/ʃɔːrt/", category: "Appearance", example: "Short person.", examplePt: "Pessoa baixa." },
    { word: "Tall", translation: "Alto", phonetic: "/tɔːl/", category: "Appearance", example: "Tall man.", examplePt: "Homem alto." },
    { word: "Young", translation: "Jovem", phonetic: "/jʌŋ/", category: "Appearance", example: "Young people.", examplePt: "Pessoas jovens." },
    { word: "Elderly", translation: "Idoso", phonetic: "/ˈeldərli/", category: "Appearance", example: "Elderly woman.", examplePt: "Mulher idosa." },
    { word: "Strong", translation: "Forte", phonetic: "/strɔːŋ/", category: "Appearance", example: "Strong muscles.", examplePt: "Músculos fortes." },
    { word: "Weak", translation: "Fraco", phonetic: "/wiːk/", category: "Appearance", example: "Weak signal.", examplePt: "Sinal fraco." },
    { word: "Healthy", translation: "Saudável", phonetic: "/ˈhelθi/", category: "Appearance", example: "Healthy lifestyle.", examplePt: "Estilo de vida saudável." },
    { word: "Sick", translation: "Doente", phonetic: "/sɪk/", category: "Appearance", example: "Sick day.", examplePt: "Dia de doença." },

    // PERSONALITY (50 words)
    { word: "Kind", translation: "Gentil", phonetic: "/kaɪnd/", category: "Personality", example: "Kind person.", examplePt: "Pessoa gentil." },
    { word: "Mean", translation: "Maldoso", phonetic: "/miːn/", category: "Personality", example: "Mean comment.", examplePt: "Comentário maldoso." },
    { word: "Nice", translation: "Legal/Simpático", phonetic: "/naɪs/", category: "Personality", example: "Nice guy.", examplePt: "Cara legal." },
    { word: "Funny", translation: "Engraçado", phonetic: "/ˈfʌni/", category: "Personality", example: "Funny joke.", examplePt: "Piada engraçada." },
    { word: "Serious", translation: "Sério", phonetic: "/ˈsɪriəs/", category: "Personality", example: "Serious problem.", examplePt: "Problema sério." },
    { word: "Shy", translation: "Tímido", phonetic: "/ʃaɪ/", category: "Personality", example: "Shy kid.", examplePt: "Criança tímida." },
    { word: "Outgoing", translation: "Extrovertido", phonetic: "/ˈaʊtɡoʊɪŋ/", category: "Personality", example: "Outgoing personality.", examplePt: "Personalidade extrovertida." },
    { word: "Friendly", translation: "Amigável", phonetic: "/ˈfrendli/", category: "Personality", example: "Friendly neighbor.", examplePt: "Vizinho amigável." },
    { word: "Selfish", translation: "Egoísta", phonetic: "/ˈselfɪʃ/", category: "Personality", example: "Selfish behavior.", examplePt: "Comportamento egoísta." },
    { word: "Generous", translation: "Generoso", phonetic: "/ˈdʒenərəs/", category: "Personality", example: "Generous donation.", examplePt: "Doação generosa." },
    { word: "Patient", translation: "Paciente", phonetic: "/ˈpeɪʃnt/", category: "Personality", example: "Be patient.", examplePt: "Seja paciente." },
    { word: "Impatient", translation: "Impaciente", phonetic: "/ɪmˈpeɪʃnt/", category: "Personality", example: "Impatient driver.", examplePt: "Motorista impaciente." },
    { word: "Honest", translation: "Honesto", phonetic: "/ˈɑːnɪst/", category: "Personality", example: "Honest answer.", examplePt: "Resposta honesta." },
    { word: "Dishonest", translation: "Desonesto", phonetic: "/dɪsˈɑːnɪst/", category: "Personality", example: "Dishonest person.", examplePt: "Pessoa desonesta." },
    { word: "Lazy", translation: "Preguiçoso", phonetic: "/ˈleɪzi/", category: "Personality", example: "Lazy Sunday.", examplePt: "Domingo preguiçoso." },
    { word: "Hardworking", translation: "Trabalhador", phonetic: "/ˈhɑːrdˌwɜːrkɪŋ/", category: "Personality", example: "Hardworking student.", examplePt: "Estudante trabalhador." },
    { word: "Smart", translation: "Inteligente", phonetic: "/smɑːrt/", category: "Personality", example: "Smart decision.", examplePt: "Decisão inteligente." },
    { word: "Stupid", translation: "Estúpido", phonetic: "/ˈstuːpɪd/", category: "Personality", example: "Stupid mistake.", examplePt: "Erro estúpido." },
    { word: "Clever", translation: "Esperto", phonetic: "/ˈklevər/", category: "Personality", example: "Clever solution.", examplePt: "Solução esperta." },
    { word: "Wise", translation: "Sábio", phonetic: "/waɪz/", category: "Personality", example: "Wise choice.", examplePt: "Escolha sábia." },
    { word: "Brave", translation: "Corajoso", phonetic: "/breɪv/", category: "Personality", example: "Brave soldier.", examplePt: "Soldado corajoso." },
    { word: "Cowardly", translation: "Covarde", phonetic: "/ˈkaʊərdli/", category: "Personality", example: "Cowardly act.", examplePt: "Ato covarde." },
    { word: "Calm", translation: "Calmo", phonetic: "/kɑːm/", category: "Personality", example: "Stay calm.", examplePt: "Fique calmo." },
    { word: "Nervous", translation: "Nervoso", phonetic: "/ˈnɜːrvəs/", category: "Personality", example: "Nervous feeling.", examplePt: "Sensação nervosa." },
    { word: "Confident", translation: "Confiante", phonetic: "/ˈkɑːnfɪdənt/", category: "Personality", example: "Confident speaker.", examplePt: "Palestrante confiante." },
    { word: "Insecure", translation: "Inseguro", phonetic: "/ˌɪnsɪˈkjʊr/", category: "Personality", example: "Insecure feeling.", examplePt: "Sentimento de insegurança." },
    { word: "Polite", translation: "Educado", phonetic: "/pəˈlaɪt/", category: "Personality", example: "Polite behavior.", examplePt: "Comportamento educado." },
    { word: "Rude", translation: "Grosseiro", phonetic: "/ruːd/", category: "Personality", example: "Rude comment.", examplePt: "Comentário grosseiro." },
    { word: "Humble", translation: "Humilde", phonetic: "/ˈhʌmbl/", category: "Personality", example: "Humble person.", examplePt: "Pessoa humilde." },
    { word: "Arrogant", translation: "Arrogante", phonetic: "/ˈærəɡənt/", category: "Personality", example: "Arrogant attitude.", examplePt: "Atitude arrogante." },

    // DESCRIBING THINGS (60 words)
    { word: "New", translation: "Novo", phonetic: "/nuː/", category: "Things", example: "New car.", examplePt: "Carro novo." },
    { word: "Old", translation: "Velho", phonetic: "/oʊld/", category: "Things", example: "Old house.", examplePt: "Casa velha." },
    { word: "Modern", translation: "Moderno", phonetic: "/ˈmɑːdərn/", category: "Things", example: "Modern design.", examplePt: "Design moderno." },
    { word: "Ancient", translation: "Antigo", phonetic: "/ˈeɪnʃənt/", category: "Things", example: "Ancient ruins.", examplePt: "Ruínas antigas." },
    { word: "Clean", translation: "Limpo", phonetic: "/kliːn/", category: "Things", example: "Clean room.", examplePt: "Quarto limpo." },
    { word: "Dirty", translation: "Sujo", phonetic: "/ˈdɜːrti/", category: "Things", example: "Dirty clothes.", examplePt: "Roupas sujas." },
    { word: "Wet", translation: "Molhado", phonetic: "/wet/", category: "Things", example: "Wet floor.", examplePt: "Chão molhado." },
    { word: "Dry", translation: "Seco", phonetic: "/draɪ/", category: "Things", example: "Dry weather.", examplePt: "Tempo seco." },
    { word: "Hot", translation: "Quente", phonetic: "/hɑːt/", category: "Things", example: "Hot coffee.", examplePt: "Café quente." },
    { word: "Cold", translation: "Frio", phonetic: "/koʊld/", category: "Things", example: "Cold water.", examplePt: "Água fria." },
    { word: "Warm", translation: "Morno/Aquecido", phonetic: "/wɔːrm/", category: "Things", example: "Warm day.", examplePt: "Dia quente." },
    { word: "Cool", translation: "Fresco/Legal", phonetic: "/kuːl/", category: "Things", example: "Cool breeze.", examplePt: "Brisa fresca." },
    { word: "Soft", translation: "Macio", phonetic: "/sɔːft/", category: "Things", example: "Soft pillow.", examplePt: "Travesseiro macio." },
    { word: "Hard", translation: "Duro", phonetic: "/hɑːrd/", category: "Things", example: "Hard rock.", examplePt: "Pedra dura." },
    { word: "Heavy", translation: "Pesado", phonetic: "/ˈhevi/", category: "Things", example: "Heavy box.", examplePt: "Caixa pesada." },
    { word: "Light", translation: "Leve", phonetic: "/laɪt/", category: "Things", example: "Light bag.", examplePt: "Bolsa leve." },
    { word: "Thick", translation: "Grosso/Espesso", phonetic: "/θɪk/", category: "Things", example: "Thick book.", examplePt: "Livro grosso." },
    { word: "Narrow", translation: "Estreito", phonetic: "/ˈnæroʊ/", category: "Things", example: "Narrow street.", examplePt: "Rua estreita." },
    { word: "Wide", translation: "Largo", phonetic: "/waɪd/", category: "Things", example: "Wide road.", examplePt: "Estrada larga." },
    { word: "Deep", translation: "Profundo", phonetic: "/diːp/", category: "Things", example: "Deep water.", examplePt: "Água profunda." },
    { word: "Shallow", translation: "Raso", phonetic: "/ˈʃæloʊ/", category: "Things", example: "Shallow pool.", examplePt: "Piscina rasa." },
    { word: "Long", translation: "Longo/Comprido", phonetic: "/lɔːŋ/", category: "Things", example: "Long hair.", examplePt: "Cabelo longo." },
    { word: "Round", translation: "Redondo", phonetic: "/raʊnd/", category: "Things", example: "Round table.", examplePt: "Mesa redonda." },
    { word: "Square", translation: "Quadrado", phonetic: "/skwer/", category: "Things", example: "Square box.", examplePt: "Caixa quadrada." },
    { word: "Flat", translation: "Plano/Liso", phonetic: "/flæt/", category: "Things", example: "Flat surface.", examplePt: "Superfície plana." },
    { word: "Rough", translation: "Áspero", phonetic: "/rʌf/", category: "Things", example: "Rough texture.", examplePt: "Textura áspera." },
    { word: "Smooth", translation: "Liso/Suave", phonetic: "/smuːð/", category: "Things", example: "Smooth skin.", examplePt: "Pele lisa." },
    { word: "Sharp", translation: "Afiado", phonetic: "/ʃɑːrp/", category: "Things", example: "Sharp knife.", examplePt: "Faca afiada." },
    { word: "Dull", translation: "Sem graça/Sem corte", phonetic: "/dʌl/", category: "Things", example: "Dull blade.", examplePt: "Lâmina sem corte." },
    { word: "Empty", translation: "Vazio", phonetic: "/ˈempti/", category: "Things", example: "Empty bottle.", examplePt: "Garrafa vazia." },
    { word: "Full", translation: "Cheio", phonetic: "/fʊl/", category: "Things", example: "Full tank.", examplePt: "Tanque cheio." },
    { word: "Open", translation: "Aberto", phonetic: "/ˈoʊpən/", category: "Things", example: "Open door.", examplePt: "Porta aberta." },
    { word: "Closed", translation: "Fechado", phonetic: "/kloʊzd/", category: "Things", example: "Closed store.", examplePt: "Loja fechada." },
    { word: "Broken", translation: "Quebrado", phonetic: "/ˈbroʊkən/", category: "Things", example: "Broken glass.", examplePt: "Vidro quebrado." },
    { word: "Fixed", translation: "Consertado", phonetic: "/fɪkst/", category: "Things", example: "Fixed problem.", examplePt: "Problema consertado." },
    { word: "Cheap", translation: "Barato", phonetic: "/tʃiːp/", category: "Things", example: "Cheap price.", examplePt: "Preço barato." },
    { word: "Expensive", translation: "Caro", phonetic: "/ɪkˈspensɪv/", category: "Things", example: "Expensive car.", examplePt: "Carro caro." },
    { word: "Free", translation: "Grátis/Livre", phonetic: "/friː/", category: "Things", example: "Free sample.", examplePt: "Amostra grátis." },
    { word: "Valuable", translation: "Valioso", phonetic: "/ˈvæljuəbl/", category: "Things", example: "Valuable item.", examplePt: "Item valioso." },
    { word: "Useless", translation: "Inútil", phonetic: "/ˈjuːsləs/", category: "Things", example: "Useless object.", examplePt: "Objeto inútil." },
    { word: "Useful", translation: "Útil", phonetic: "/ˈjuːsfl/", category: "Things", example: "Useful tool.", examplePt: "Ferramenta útil." },
    { word: "Necessary", translation: "Necessário", phonetic: "/ˈnesəseri/", category: "Things", example: "Necessary step.", examplePt: "Passo necessário." },
    { word: "Unnecessary", translation: "Desnecessário", phonetic: "/ʌnˈnesəseri/", category: "Things", example: "Unnecessary risk.", examplePt: "Risco desnecessário." },
    { word: "Important", translation: "Importante", phonetic: "/ɪmˈpɔːrtnt/", category: "Things", example: "Important meeting.", examplePt: "Reunião importante." },
    { word: "Ordinary", translation: "Comum", phonetic: "/ˈɔːrdneri/", category: "Things", example: "Ordinary day.", examplePt: "Dia comum." },
    { word: "Special", translation: "Especial", phonetic: "/ˈspeʃl/", category: "Things", example: "Special occasion.", examplePt: "Ocasião especial." },
    { word: "Strange", translation: "Estranho", phonetic: "/streɪndʒ/", category: "Things", example: "Strange noise.", examplePt: "Barulho estranho." },
    { word: "Normal", translation: "Normal", phonetic: "/ˈnɔːrml/", category: "Things", example: "Normal situation.", examplePt: "Situação normal." },
    { word: "Perfect", translation: "Perfeito", phonetic: "/ˈpɜːrfɪkt/", category: "Things", example: "Perfect score.", examplePt: "Nota perfeita." },
    { word: "Terrible", translation: "Terrível", phonetic: "/ˈterəbl/", category: "Things", example: "Terrible weather.", examplePt: "Tempo terrível." },
    { word: "Wonderful", translation: "Maravilhoso", phonetic: "/ˈwʌndərfl/", category: "Things", example: "Wonderful view.", examplePt: "Vista maravilhosa." },
    { word: "Amazing", translation: "Incrível", phonetic: "/əˈmeɪzɪŋ/", category: "Things", example: "Amazing show.", examplePt: "Show incrível." },
    { word: "Awful", translation: "Horrível", phonetic: "/ˈɔːfl/", category: "Things", example: "Awful taste.", examplePt: "Gosto horrível." },
    { word: "Excellent", translation: "Excelente", phonetic: "/ˈeksələnt/", category: "Things", example: "Excellent work.", examplePt: "Trabalho excelente." },
    { word: "Horrible", translation: "Horrível", phonetic: "/ˈhɔːrəbl/", category: "Things", example: "Horrible accident.", examplePt: "Acidente horrível." },
    { word: "Fantastic", translation: "Fantástico", phonetic: "/fænˈtæstɪk/", category: "Things", example: "Fantastic idea.", examplePt: "Ideia fantástica." }
];
