// ===== MEGA VOCABULARY 1: HOME & DAILY LIFE =====
const homeVocabulary = [
    { word: "Lamp", translation: "Lâmpada", phonetic: "/læmp/", category: "Home", example: "Turn on the lamp.", examplePt: "Acenda a lâmpada." },
    { word: "Pillow", translation: "Travesseiro", phonetic: "/ˈpɪloʊ/", category: "Home", example: "Soft pillow.", examplePt: "Travesseiro macio." },
    { word: "Blanket", translation: "Cobertor", phonetic: "/ˈblæŋkɪt/", category: "Home", example: "Warm blanket.", examplePt: "Cobertor quente." },
    { word: "Curtain", translation: "Cortina", phonetic: "/ˈkɜːrtn/", category: "Home", example: "Open the curtains.", examplePt: "Abra as cortinas." },
    { word: "Mirror", translation: "Espelho", phonetic: "/ˈmɪrər/", category: "Home", example: "Look in the mirror.", examplePt: "Olhe no espelho." },
    { word: "Carpet", translation: "Carpete", phonetic: "/ˈkɑːrpɪt/", category: "Home", example: "Soft carpet.", examplePt: "Carpete macio." },
    { word: "Sofa", translation: "Sofá", phonetic: "/ˈsoʊfə/", category: "Home", example: "Sit on the sofa.", examplePt: "Sente no sofá." },
    { word: "Armchair", translation: "Poltrona", phonetic: "/ˈɑːrmtʃer/", category: "Home", example: "Comfortable armchair.", examplePt: "Poltrona confortável." },
    { word: "Shelf", translation: "Prateleira", phonetic: "/ʃelf/", category: "Home", example: "Put it on the shelf.", examplePt: "Ponha na prateleira." },
    { word: "Drawer", translation: "Gaveta", phonetic: "/drɔːr/", category: "Home", example: "Open the drawer.", examplePt: "Abra a gaveta." },
    { word: "Closet", translation: "Armário", phonetic: "/ˈklɑːzɪt/", category: "Home", example: "Clean closet.", examplePt: "Armário limpo." },
    { word: "Wardrobe", translation: "Guarda-roupa", phonetic: "/ˈwɔːrdroʊb/", category: "Home", example: "Full wardrobe.", examplePt: "Guarda-roupa cheio." },
    { word: "Desk", translation: "Escrivaninha", phonetic: "/desk/", category: "Home", example: "Work at the desk.", examplePt: "Trabalhe na escrivaninha." },
    { word: "Stairs", translation: "Escadas", phonetic: "/sterz/", category: "Home", example: "Go up the stairs.", examplePt: "Suba as escadas." },
    { word: "Ceiling", translation: "Teto", phonetic: "/ˈsiːlɪŋ/", category: "Home", example: "High ceiling.", examplePt: "Teto alto." },
    { word: "Floor", translation: "Chão", phonetic: "/flɔːr/", category: "Home", example: "Clean the floor.", examplePt: "Limpe o chão." },
    { word: "Wall", translation: "Parede", phonetic: "/wɔːl/", category: "Home", example: "Paint the wall.", examplePt: "Pinte a parede." },
    { word: "Roof", translation: "Telhado", phonetic: "/ruːf/", category: "Home", example: "Fix the roof.", examplePt: "Conserte o telhado." },
    { word: "Fence", translation: "Cerca", phonetic: "/fens/", category: "Home", example: "Build a fence.", examplePt: "Construa uma cerca." },
    { word: "Gate", translation: "Portão", phonetic: "/ɡeɪt/", category: "Home", example: "Open the gate.", examplePt: "Abra o portão." },
    { word: "Garden", translation: "Jardim", phonetic: "/ˈɡɑːrdn/", category: "Home", example: "Beautiful garden.", examplePt: "Jardim bonito." },
    { word: "Garage", translation: "Garagem", phonetic: "/ɡəˈrɑːʒ/", category: "Home", example: "Park in the garage.", examplePt: "Estacione na garagem." },
    { word: "Basement", translation: "Porão", phonetic: "/ˈbeɪsmənt/", category: "Home", example: "Storage in the basement.", examplePt: "Armazenamento no porão." },
    { word: "Attic", translation: "Sótão", phonetic: "/ˈætɪk/", category: "Home", example: "Old things in the attic.", examplePt: "Coisas velhas no sótão." },
    { word: "Balcony", translation: "Varanda", phonetic: "/ˈbælkəni/", category: "Home", example: "Sit on the balcony.", examplePt: "Sente na varanda." },
    { word: "Doorbell", translation: "Campainha", phonetic: "/ˈdɔːrbel/", category: "Home", example: "Ring the doorbell.", examplePt: "Toque a campainha." },
    { word: "Key", translation: "Chave", phonetic: "/kiː/", category: "Home", example: "House key.", examplePt: "Chave da casa." },
    { word: "Lock", translation: "Fechadura", phonetic: "/lɑːk/", category: "Home", example: "Lock the door.", examplePt: "Tranque a porta." },
    { word: "Switch", translation: "Interruptor", phonetic: "/swɪtʃ/", category: "Home", example: "Light switch.", examplePt: "Interruptor de luz." },
    { word: "Outlet", translation: "Tomada", phonetic: "/ˈaʊtlet/", category: "Home", example: "Plug in the outlet.", examplePt: "Ligue na tomada." },
    { word: "Pot", translation: "Panela", phonetic: "/pɑːt/", category: "Kitchen", example: "Cooking pot.", examplePt: "Panela de cozinhar." },
    { word: "Pan", translation: "Frigideira", phonetic: "/pæn/", category: "Kitchen", example: "Frying pan.", examplePt: "Frigideira." },
    { word: "Kettle", translation: "Chaleira", phonetic: "/ˈketl/", category: "Kitchen", example: "Electric kettle.", examplePt: "Chaleira elétrica." },
    { word: "Knife", translation: "Faca", phonetic: "/naɪf/", category: "Kitchen", example: "Sharp knife.", examplePt: "Faca afiada." },
    { word: "Fork", translation: "Garfo", phonetic: "/fɔːrk/", category: "Kitchen", example: "Silver fork.", examplePt: "Garfo de prata." },
    { word: "Spoon", translation: "Colher", phonetic: "/spuːn/", category: "Kitchen", example: "Soup spoon.", examplePt: "Colher de sopa." },
    { word: "Plate", translation: "Prato", phonetic: "/pleɪt/", category: "Kitchen", example: "Dinner plate.", examplePt: "Prato de jantar." },
    { word: "Bowl", translation: "Tigela", phonetic: "/boʊl/", category: "Kitchen", example: "Soup bowl.", examplePt: "Tigela de sopa." },
    { word: "Cup", translation: "Xícara", phonetic: "/kʌp/", category: "Kitchen", example: "Coffee cup.", examplePt: "Xícara de café." },
    { word: "Glass", translation: "Copo", phonetic: "/ɡlæs/", category: "Kitchen", example: "Water glass.", examplePt: "Copo de água." },
    { word: "Mug", translation: "Caneca", phonetic: "/mʌɡ/", category: "Kitchen", example: "Tea mug.", examplePt: "Caneca de chá." },
    { word: "Tray", translation: "Bandeja", phonetic: "/treɪ/", category: "Kitchen", example: "Serving tray.", examplePt: "Bandeja de servir." },
    { word: "Napkin", translation: "Guardanapo", phonetic: "/ˈnæpkɪn/", category: "Kitchen", example: "Paper napkin.", examplePt: "Guardanapo de papel." },
    { word: "Blender", translation: "Liquidificador", phonetic: "/ˈblendər/", category: "Kitchen", example: "Make a smoothie.", examplePt: "Faça um smoothie." },
    { word: "Microwave", translation: "Micro-ondas", phonetic: "/ˈmaɪkroʊweɪv/", category: "Kitchen", example: "Heat it in the microwave.", examplePt: "Aqueça no micro-ondas." },
    { word: "Oven", translation: "Forno", phonetic: "/ˈʌvn/", category: "Kitchen", example: "Bake in the oven.", examplePt: "Asse no forno." },
    { word: "Stove", translation: "Fogão", phonetic: "/stoʊv/", category: "Kitchen", example: "Cook on the stove.", examplePt: "Cozinhe no fogão." },
    { word: "Refrigerator", translation: "Geladeira", phonetic: "/rɪˈfrɪdʒəreɪtər/", category: "Kitchen", example: "Keep it cold.", examplePt: "Mantenha gelado." },
    { word: "Freezer", translation: "Congelador", phonetic: "/ˈfriːzər/", category: "Kitchen", example: "Store in the freezer.", examplePt: "Armazene no congelador." },
    { word: "Sink", translation: "Pia", phonetic: "/sɪŋk/", category: "Kitchen", example: "Wash in the sink.", examplePt: "Lave na pia." }
];

console.log('🏠 Home Vocabulary loaded:', homeVocabulary.length, 'words');
