// ===== EXPANDED VOCABULARY - PART 4: ADVERBS, PREPOSITIONS, PROFESSIONS & MORE =====

const adverbsVocabulary = [
    // ADVERBS OF FREQUENCY (20 words)
    { word: "Always", translation: "Sempre", phonetic: "/ˈɔːlweɪz/", category: "Adverbs", example: "I always wake up early.", examplePt: "Sempre acordo cedo." },
    { word: "Usually", translation: "Geralmente", phonetic: "/ˈjuːʒuəli/", category: "Adverbs", example: "I usually have coffee.", examplePt: "Geralmente tomo café." },
    { word: "Often", translation: "Frequentemente", phonetic: "/ˈɔːfn/", category: "Adverbs", example: "I often exercise.", examplePt: "Frequentemente me exercito." },
    { word: "Sometimes", translation: "Às vezes", phonetic: "/ˈsʌmtaɪmz/", category: "Adverbs", example: "Sometimes I'm late.", examplePt: "Às vezes estou atrasado." },
    { word: "Rarely", translation: "Raramente", phonetic: "/ˈrerli/", category: "Adverbs", example: "I rarely eat fast food.", examplePt: "Raramente como fast food." },
    { word: "Never", translation: "Nunca", phonetic: "/ˈnevər/", category: "Adverbs", example: "I never smoke.", examplePt: "Nunca fumo." },
    { word: "Seldom", translation: "Raramente", phonetic: "/ˈseldəm/", category: "Adverbs", example: "I seldom watch TV.", examplePt: "Raramente assisto TV." },
    { word: "Occasionally", translation: "Ocasionalmente", phonetic: "/əˈkeɪʒnəli/", category: "Adverbs", example: "I occasionally travel.", examplePt: "Ocasionalmente viajo." },
    { word: "Frequently", translation: "Frequentemente", phonetic: "/ˈfriːkwəntli/", category: "Adverbs", example: "Frequently asked questions.", examplePt: "Perguntas frequentes." },
    { word: "Constantly", translation: "Constantemente", phonetic: "/ˈkɑːnstəntli/", category: "Adverbs", example: "Constantly improving.", examplePt: "Melhorando constantemente." },

    // ADVERBS OF MANNER (30 words)
    { word: "Quickly", translation: "Rapidamente", phonetic: "/ˈkwɪkli/", category: "Adverbs", example: "Run quickly.", examplePt: "Corra rapidamente." },
    { word: "Slowly", translation: "Lentamente", phonetic: "/ˈsloʊli/", category: "Adverbs", example: "Walk slowly.", examplePt: "Ande lentamente." },
    { word: "Carefully", translation: "Cuidadosamente", phonetic: "/ˈkerfəli/", category: "Adverbs", example: "Drive carefully.", examplePt: "Dirija cuidadosamente." },
    { word: "Easily", translation: "Facilmente", phonetic: "/ˈiːzɪli/", category: "Adverbs", example: "Easily done.", examplePt: "Feito facilmente." },
    { word: "Hardly", translation: "Dificilmente", phonetic: "/ˈhɑːrdli/", category: "Adverbs", example: "I can hardly hear.", examplePt: "Dificilmente ouço." },
    { word: "Loudly", translation: "Alto/Em voz alta", phonetic: "/ˈlaʊdli/", category: "Adverbs", example: "Speak loudly.", examplePt: "Fale alto." },
    { word: "Quietly", translation: "Silenciosamente", phonetic: "/ˈkwaɪətli/", category: "Adverbs", example: "Speak quietly.", examplePt: "Fale baixo." },
    { word: "Suddenly", translation: "De repente", phonetic: "/ˈsʌdənli/", category: "Adverbs", example: "Suddenly it happened.", examplePt: "De repente aconteceu." },
    { word: "Happily", translation: "Felizmente", phonetic: "/ˈhæpɪli/", category: "Adverbs", example: "Happily ever after.", examplePt: "Felizes para sempre." },
    { word: "Sadly", translation: "Tristemente", phonetic: "/ˈsædli/", category: "Adverbs", example: "Sadly, he left.", examplePt: "Tristemente, ele partiu." },
    { word: "Badly", translation: "Mal", phonetic: "/ˈbædli/", category: "Adverbs", example: "Badly hurt.", examplePt: "Machucado gravemente." },
    { word: "Well", translation: "Bem", phonetic: "/wel/", category: "Adverbs", example: "Done well.", examplePt: "Feito bem." },
    { word: "Hard", translation: "Com esforço", phonetic: "/hɑːrd/", category: "Adverbs", example: "Work hard.", examplePt: "Trabalhe duro." },
    { word: "Fast", translation: "Rápido", phonetic: "/fæst/", category: "Adverbs", example: "Run fast.", examplePt: "Corra rápido." },
    { word: "Properly", translation: "Apropriadamente", phonetic: "/ˈprɑːpərli/", category: "Adverbs", example: "Do it properly.", examplePt: "Faça apropriadamente." },
    { word: "Correctly", translation: "Corretamente", phonetic: "/kəˈrektli/", category: "Adverbs", example: "Answer correctly.", examplePt: "Responda corretamente." },
    { word: "Completely", translation: "Completamente", phonetic: "/kəmˈpliːtli/", category: "Adverbs", example: "Completely finished.", examplePt: "Completamente terminado." },
    { word: "Exactly", translation: "Exatamente", phonetic: "/ɪɡˈzæktli/", category: "Adverbs", example: "Exactly right.", examplePt: "Exatamente certo." },
    { word: "Extremely", translation: "Extremamente", phonetic: "/ɪkˈstriːmli/", category: "Adverbs", example: "Extremely hot.", examplePt: "Extremamente quente." },
    { word: "Really", translation: "Realmente", phonetic: "/ˈriːəli/", category: "Adverbs", example: "Really good.", examplePt: "Realmente bom." },
    { word: "Nearly", translation: "Quase", phonetic: "/ˈnɪrli/", category: "Adverbs", example: "Nearly done.", examplePt: "Quase pronto." },
    { word: "Almost", translation: "Quase", phonetic: "/ˈɔːlmoʊst/", category: "Adverbs", example: "Almost there.", examplePt: "Quase lá." },
    { word: "Quite", translation: "Bastante", phonetic: "/kwaɪt/", category: "Adverbs", example: "Quite good.", examplePt: "Bastante bom." },
    { word: "Pretty", translation: "Bem/Bastante", phonetic: "/ˈprɪti/", category: "Adverbs", example: "Pretty much.", examplePt: "Praticamente." },
    { word: "Very", translation: "Muito", phonetic: "/ˈveri/", category: "Adverbs", example: "Very nice.", examplePt: "Muito legal." },
    { word: "Too", translation: "Demais", phonetic: "/tuː/", category: "Adverbs", example: "Too much.", examplePt: "Demais." },
    { word: "Enough", translation: "Suficiente", phonetic: "/ɪˈnʌf/", category: "Adverbs", example: "Good enough.", examplePt: "Bom o suficiente." },
    { word: "Probably", translation: "Provavelmente", phonetic: "/ˈprɑːbəbli/", category: "Adverbs", example: "Probably yes.", examplePt: "Provavelmente sim." },
    { word: "Certainly", translation: "Certamente", phonetic: "/ˈsɜːrtnli/", category: "Adverbs", example: "Certainly true.", examplePt: "Certamente verdadeiro." },
    { word: "Possibly", translation: "Possivelmente", phonetic: "/ˈpɑːsəbli/", category: "Adverbs", example: "Possibly wrong.", examplePt: "Possivelmente errado." }
];

const professionsVocabulary = [
    // PROFESSIONS (80 words)
    { word: "Doctor", translation: "Médico", phonetic: "/ˈdɑːktər/", category: "Professions", example: "I'm a doctor.", examplePt: "Sou médico." },
    { word: "Nurse", translation: "Enfermeiro(a)", phonetic: "/nɜːrs/", category: "Professions", example: "Kind nurse.", examplePt: "Enfermeira gentil." },
    { word: "Teacher", translation: "Professor(a)", phonetic: "/ˈtiːtʃər/", category: "Professions", example: "Great teacher.", examplePt: "Ótimo professor." },
    { word: "Student", translation: "Estudante", phonetic: "/ˈstuːdnt/", category: "Professions", example: "University student.", examplePt: "Estudante universitário." },
    { word: "Lawyer", translation: "Advogado", phonetic: "/ˈlɔːjər/", category: "Professions", example: "Criminal lawyer.", examplePt: "Advogado criminal." },
    { word: "Engineer", translation: "Engenheiro", phonetic: "/ˌendʒɪˈnɪr/", category: "Professions", example: "Software engineer.", examplePt: "Engenheiro de software." },
    { word: "Architect", translation: "Arquiteto", phonetic: "/ˈɑːrkɪtekt/", category: "Professions", example: "Famous architect.", examplePt: "Arquiteto famoso." },
    { word: "Dentist", translation: "Dentista", phonetic: "/ˈdentɪst/", category: "Professions", example: "Good dentist.", examplePt: "Bom dentista." },
    { word: "Accountant", translation: "Contador", phonetic: "/əˈkaʊntənt/", category: "Professions", example: "Tax accountant.", examplePt: "Contador tributário." },
    { word: "Chef", translation: "Chef/Cozinheiro", phonetic: "/ʃef/", category: "Professions", example: "Professional chef.", examplePt: "Chef profissional." },
    { word: "Waiter", translation: "Garçom", phonetic: "/ˈweɪtər/", category: "Professions", example: "Friendly waiter.", examplePt: "Garçom amigável." },
    { word: "Waitress", translation: "Garçonete", phonetic: "/ˈweɪtrəs/", category: "Professions", example: "Young waitress.", examplePt: "Garçonete jovem." },
    { word: "Driver", translation: "Motorista", phonetic: "/ˈdraɪvər/", category: "Professions", example: "Taxi driver.", examplePt: "Motorista de táxi." },
    { word: "Pilot", translation: "Piloto", phonetic: "/ˈpaɪlət/", category: "Professions", example: "Airline pilot.", examplePt: "Piloto de avião." },
    { word: "Police officer", translation: "Policial", phonetic: "/pəˈliːs ˈɔːfɪsər/", category: "Professions", example: "Police officer on duty.", examplePt: "Policial de serviço." },
    { word: "Firefighter", translation: "Bombeiro", phonetic: "/ˈfaɪərfaɪtər/", category: "Professions", example: "Brave firefighter.", examplePt: "Bombeiro corajoso." },
    { word: "Journalist", translation: "Jornalista", phonetic: "/ˈdʒɜːrnəlɪst/", category: "Professions", example: "TV journalist.", examplePt: "Jornalista de TV." },
    { word: "Writer", translation: "Escritor", phonetic: "/ˈraɪtər/", category: "Professions", example: "Famous writer.", examplePt: "Escritor famoso." },
    { word: "Artist", translation: "Artista", phonetic: "/ˈɑːrtɪst/", category: "Professions", example: "Talented artist.", examplePt: "Artista talentoso." },
    { word: "Musician", translation: "Músico", phonetic: "/mjuˈzɪʃn/", category: "Professions", example: "Jazz musician.", examplePt: "Músico de jazz." },
    { word: "Actor", translation: "Ator", phonetic: "/ˈæktər/", category: "Professions", example: "Famous actor.", examplePt: "Ator famoso." },
    { word: "Actress", translation: "Atriz", phonetic: "/ˈæktrəs/", category: "Professions", example: "Award-winning actress.", examplePt: "Atriz premiada." },
    { word: "Singer", translation: "Cantor", phonetic: "/ˈsɪŋər/", category: "Professions", example: "Pop singer.", examplePt: "Cantor pop." },
    { word: "Dancer", translation: "Dançarino", phonetic: "/ˈdænsər/", category: "Professions", example: "Ballet dancer.", examplePt: "Bailarino." },
    { word: "Photographer", translation: "Fotógrafo", phonetic: "/fəˈtɑːɡrəfər/", category: "Professions", example: "Wedding photographer.", examplePt: "Fotógrafo de casamento." },
    { word: "Designer", translation: "Designer", phonetic: "/dɪˈzaɪnər/", category: "Professions", example: "Graphic designer.", examplePt: "Designer gráfico." },
    { word: "Programmer", translation: "Programador", phonetic: "/ˈproʊɡræmər/", category: "Professions", example: "Computer programmer.", examplePt: "Programador de computador." },
    { word: "Developer", translation: "Desenvolvedor", phonetic: "/dɪˈveləpər/", category: "Professions", example: "Web developer.", examplePt: "Desenvolvedor web." },
    { word: "Scientist", translation: "Cientista", phonetic: "/ˈsaɪəntɪst/", category: "Professions", example: "Research scientist.", examplePt: "Cientista pesquisador." },
    { word: "Researcher", translation: "Pesquisador", phonetic: "/rɪˈsɜːrtʃər/", category: "Professions", example: "Medical researcher.", examplePt: "Pesquisador médico." },
    { word: "Secretary", translation: "Secretário(a)", phonetic: "/ˈsekrəteri/", category: "Professions", example: "Executive secretary.", examplePt: "Secretária executiva." },
    { word: "Receptionist", translation: "Recepcionista", phonetic: "/rɪˈsepʃənɪst/", category: "Professions", example: "Hotel receptionist.", examplePt: "Recepcionista de hotel." },
    { word: "Salesperson", translation: "Vendedor", phonetic: "/ˈseɪlzˌpɜːrsn/", category: "Professions", example: "Car salesperson.", examplePt: "Vendedor de carros." },
    { word: "Cashier", translation: "Caixa", phonetic: "/kæˈʃɪr/", category: "Professions", example: "Bank cashier.", examplePt: "Caixa de banco." },
    { word: "Banker", translation: "Banqueiro", phonetic: "/ˈbæŋkər/", category: "Professions", example: "Investment banker.", examplePt: "Banqueiro de investimentos." },
    { word: "Businessman", translation: "Empresário", phonetic: "/ˈbɪznəsmæn/", category: "Professions", example: "Successful businessman.", examplePt: "Empresário bem-sucedido." },
    { word: "Mechanic", translation: "Mecânico", phonetic: "/məˈkænɪk/", category: "Professions", example: "Car mechanic.", examplePt: "Mecânico de carros." },
    { word: "Electrician", translation: "Eletricista", phonetic: "/ɪˌlekˈtrɪʃn/", category: "Professions", example: "Licensed electrician.", examplePt: "Eletricista licenciado." },
    { word: "Plumber", translation: "Encanador", phonetic: "/ˈplʌmər/", category: "Professions", example: "Emergency plumber.", examplePt: "Encanador de emergência." },
    { word: "Carpenter", translation: "Carpinteiro", phonetic: "/ˈkɑːrpəntər/", category: "Professions", example: "Skilled carpenter.", examplePt: "Carpinteiro habilidoso." },
    { word: "Painter", translation: "Pintor", phonetic: "/ˈpeɪntər/", category: "Professions", example: "House painter.", examplePt: "Pintor de casas." },
    { word: "Builder", translation: "Construtor", phonetic: "/ˈbɪldər/", category: "Professions", example: "Home builder.", examplePt: "Construtor de casas." },
    { word: "Farmer", translation: "Fazendeiro", phonetic: "/ˈfɑːrmər/", category: "Professions", example: "Organic farmer.", examplePt: "Fazendeiro orgânico." },
    { word: "Baker", translation: "Padeiro", phonetic: "/ˈbeɪkər/", category: "Professions", example: "Local baker.", examplePt: "Padeiro local." },
    { word: "Butcher", translation: "Açougueiro", phonetic: "/ˈbʊtʃər/", category: "Professions", example: "Village butcher.", examplePt: "Açougueiro da vila." },
    { word: "Hairdresser", translation: "Cabeleireiro(a)", phonetic: "/ˈherˌdresər/", category: "Professions", example: "Creative hairdresser.", examplePt: "Cabeleireiro criativo." },
    { word: "Barber", translation: "Barbeiro", phonetic: "/ˈbɑːrbər/", category: "Professions", example: "Old-fashioned barber.", examplePt: "Barbeiro tradicional." },
    { word: "Athlete", translation: "Atleta", phonetic: "/ˈæθliːt/", category: "Professions", example: "Professional athlete.", examplePt: "Atleta profissional." },
    { word: "Coach", translation: "Treinador", phonetic: "/koʊtʃ/", category: "Professions", example: "Football coach.", examplePt: "Treinador de futebol." },
    { word: "Veterinarian", translation: "Veterinário", phonetic: "/ˌvetərɪˈneriən/", category: "Professions", example: "Animal veterinarian.", examplePt: "Veterinário de animais." },
    { word: "Pharmacist", translation: "Farmacêutico", phonetic: "/ˈfɑːrməsɪst/", category: "Professions", example: "Hospital pharmacist.", examplePt: "Farmacêutico de hospital." },
    { word: "Psychologist", translation: "Psicólogo", phonetic: "/saɪˈkɑːlədʒɪst/", category: "Professions", example: "Child psychologist.", examplePt: "Psicólogo infantil." },
    { word: "Therapist", translation: "Terapeuta", phonetic: "/ˈθerəpɪst/", category: "Professions", example: "Physical therapist.", examplePt: "Fisioterapeuta." },
    { word: "Consultant", translation: "Consultor", phonetic: "/kənˈsʌltənt/", category: "Professions", example: "Business consultant.", examplePt: "Consultor de negócios." },
    { word: "Translator", translation: "Tradutor", phonetic: "/trænsˈleɪtər/", category: "Professions", example: "Professional translator.", examplePt: "Tradutor profissional." },
    { word: "Interpreter", translation: "Intérprete", phonetic: "/ɪnˈtɜːrprɪtər/", category: "Professions", example: "Conference interpreter.", examplePt: "Intérprete de conferências." },
    { word: "Librarian", translation: "Bibliotecário", phonetic: "/laɪˈbreriən/", category: "Professions", example: "School librarian.", examplePt: "Bibliotecário escolar." },
    { word: "Janitor", translation: "Zelador", phonetic: "/ˈdʒænɪtər/", category: "Professions", example: "Building janitor.", examplePt: "Zelador do prédio." },
    { word: "Security guard", translation: "Segurança", phonetic: "/sɪˈkjʊrəti ɡɑːrd/", category: "Professions", example: "Night security guard.", examplePt: "Segurança noturno." },
    { word: "Flight attendant", translation: "Comissário(a) de bordo", phonetic: "/flaɪt əˈtendənt/", category: "Professions", example: "Friendly flight attendant.", examplePt: "Comissária de bordo simpática." }
];

const prepositionsVocabulary = [
    // PREPOSITIONS OF PLACE (20 words)
    { word: "In", translation: "Em/Dentro", phonetic: "/ɪn/", category: "Prepositions", example: "In the box.", examplePt: "Dentro da caixa." },
    { word: "On", translation: "Sobre/Em cima", phonetic: "/ɑːn/", category: "Prepositions", example: "On the table.", examplePt: "Na mesa." },
    { word: "At", translation: "Em/No", phonetic: "/æt/", category: "Prepositions", example: "At school.", examplePt: "Na escola." },
    { word: "Under", translation: "Embaixo", phonetic: "/ˈʌndər/", category: "Prepositions", example: "Under the bed.", examplePt: "Embaixo da cama." },
    { word: "Above", translation: "Acima", phonetic: "/əˈbʌv/", category: "Prepositions", example: "Above the clouds.", examplePt: "Acima das nuvens." },
    { word: "Below", translation: "Abaixo", phonetic: "/bɪˈloʊ/", category: "Prepositions", example: "Below zero.", examplePt: "Abaixo de zero." },
    { word: "Between", translation: "Entre (dois)", phonetic: "/bɪˈtwiːn/", category: "Prepositions", example: "Between us.", examplePt: "Entre nós." },
    { word: "Among", translation: "Entre (vários)", phonetic: "/əˈmʌŋ/", category: "Prepositions", example: "Among friends.", examplePt: "Entre amigos." },
    { word: "Behind", translation: "Atrás", phonetic: "/bɪˈhaɪnd/", category: "Prepositions", example: "Behind the door.", examplePt: "Atrás da porta." },
    { word: "In front of", translation: "Na frente de", phonetic: "/ɪn frʌnt əv/", category: "Prepositions", example: "In front of the house.", examplePt: "Na frente da casa." },
    { word: "Next to", translation: "Ao lado de", phonetic: "/nekst tuː/", category: "Prepositions", example: "Next to me.", examplePt: "Ao meu lado." },
    { word: "Beside", translation: "Ao lado", phonetic: "/bɪˈsaɪd/", category: "Prepositions", example: "Beside the river.", examplePt: "Ao lado do rio." },
    { word: "Near", translation: "Perto", phonetic: "/nɪr/", category: "Prepositions", example: "Near the park.", examplePt: "Perto do parque." },
    { word: "Far from", translation: "Longe de", phonetic: "/fɑːr frəm/", category: "Prepositions", example: "Far from home.", examplePt: "Longe de casa." },
    { word: "Inside", translation: "Dentro", phonetic: "/ɪnˈsaɪd/", category: "Prepositions", example: "Inside the building.", examplePt: "Dentro do prédio." },
    { word: "Outside", translation: "Fora", phonetic: "/ˌaʊtˈsaɪd/", category: "Prepositions", example: "Outside the city.", examplePt: "Fora da cidade." },
    { word: "Through", translation: "Através", phonetic: "/θruː/", category: "Prepositions", example: "Through the window.", examplePt: "Através da janela." },
    { word: "Around", translation: "Ao redor", phonetic: "/əˈraʊnd/", category: "Prepositions", example: "Around the world.", examplePt: "Ao redor do mundo." },
    { word: "Along", translation: "Ao longo", phonetic: "/əˈlɔːŋ/", category: "Prepositions", example: "Along the road.", examplePt: "Ao longo da estrada." },
    { word: "Across", translation: "Do outro lado", phonetic: "/əˈkrɔːs/", category: "Prepositions", example: "Across the street.", examplePt: "Do outro lado da rua." },

    // PREPOSITIONS OF TIME (15 words)
    { word: "Before", translation: "Antes", phonetic: "/bɪˈfɔːr/", category: "Prepositions", example: "Before noon.", examplePt: "Antes do meio-dia." },
    { word: "After", translation: "Depois", phonetic: "/ˈæftər/", category: "Prepositions", example: "After lunch.", examplePt: "Depois do almoço." },
    { word: "During", translation: "Durante", phonetic: "/ˈdʊrɪŋ/", category: "Prepositions", example: "During the meeting.", examplePt: "Durante a reunião." },
    { word: "Until", translation: "Até", phonetic: "/ənˈtɪl/", category: "Prepositions", example: "Until tomorrow.", examplePt: "Até amanhã." },
    { word: "Since", translation: "Desde", phonetic: "/sɪns/", category: "Prepositions", example: "Since morning.", examplePt: "Desde de manhã." },
    { word: "For", translation: "Por/Para", phonetic: "/fɔːr/", category: "Prepositions", example: "For two hours.", examplePt: "Por duas horas." },
    { word: "By", translation: "Até/Por", phonetic: "/baɪ/", category: "Prepositions", example: "By Friday.", examplePt: "Até sexta-feira." },
    { word: "From...to", translation: "De...até", phonetic: "/frəm tuː/", category: "Prepositions", example: "From 9 to 5.", examplePt: "Das 9 às 5." },
    { word: "Within", translation: "Dentro de", phonetic: "/wɪˈðɪn/", category: "Prepositions", example: "Within a week.", examplePt: "Dentro de uma semana." },
    { word: "Throughout", translation: "Durante todo", phonetic: "/θruːˈaʊt/", category: "Prepositions", example: "Throughout the year.", examplePt: "Durante todo o ano." }
];

const moreWordsVocabulary = [
    // SCHOOL & EDUCATION (30 words)
    { word: "School", translation: "Escola", phonetic: "/skuːl/", category: "Education", example: "Go to school.", examplePt: "Ir para a escola." },
    { word: "University", translation: "Universidade", phonetic: "/ˌjuːnɪˈvɜːrsəti/", category: "Education", example: "Study at university.", examplePt: "Estudar na universidade." },
    { word: "College", translation: "Faculdade", phonetic: "/ˈkɑːlɪdʒ/", category: "Education", example: "College student.", examplePt: "Estudante de faculdade." },
    { word: "Classroom", translation: "Sala de aula", phonetic: "/ˈklæsruːm/", category: "Education", example: "Large classroom.", examplePt: "Sala de aula grande." },
    { word: "Library", translation: "Biblioteca", phonetic: "/ˈlaɪbreri/", category: "Education", example: "Public library.", examplePt: "Biblioteca pública." },
    { word: "Homework", translation: "Dever de casa", phonetic: "/ˈhoʊmwɜːrk/", category: "Education", example: "Do your homework.", examplePt: "Faça seu dever de casa." },
    { word: "Exam", translation: "Prova", phonetic: "/ɪɡˈzæm/", category: "Education", example: "Final exam.", examplePt: "Prova final." },
    { word: "Test", translation: "Teste", phonetic: "/test/", category: "Education", example: "Take a test.", examplePt: "Fazer um teste." },
    { word: "Grade", translation: "Nota", phonetic: "/ɡreɪd/", category: "Education", example: "Good grade.", examplePt: "Nota boa." },
    { word: "Subject", translation: "Matéria", phonetic: "/ˈsʌbdʒɪkt/", category: "Education", example: "Favorite subject.", examplePt: "Matéria favorita." },
    { word: "Lesson", translation: "Lição", phonetic: "/ˈlesn/", category: "Education", example: "English lesson.", examplePt: "Aula de inglês." },
    { word: "Course", translation: "Curso", phonetic: "/kɔːrs/", category: "Education", example: "Online course.", examplePt: "Curso online." },
    { word: "Degree", translation: "Diploma/Grau", phonetic: "/dɪˈɡriː/", category: "Education", example: "Bachelor's degree.", examplePt: "Diploma de bacharel." },
    { word: "Certificate", translation: "Certificado", phonetic: "/sərˈtɪfɪkət/", category: "Education", example: "Get a certificate.", examplePt: "Obter um certificado." },
    { word: "Semester", translation: "Semestre", phonetic: "/sɪˈmestər/", category: "Education", example: "Fall semester.", examplePt: "Semestre de outono." },
    { word: "Notebook", translation: "Caderno", phonetic: "/ˈnoʊtbʊk/", category: "Education", example: "New notebook.", examplePt: "Caderno novo." },
    { word: "Textbook", translation: "Livro didático", phonetic: "/ˈtekstbʊk/", category: "Education", example: "Math textbook.", examplePt: "Livro de matemática." },
    { word: "Pencil", translation: "Lápis", phonetic: "/ˈpensl/", category: "Education", example: "Sharpened pencil.", examplePt: "Lápis apontado." },
    { word: "Pen", translation: "Caneta", phonetic: "/pen/", category: "Education", example: "Blue pen.", examplePt: "Caneta azul." },
    { word: "Eraser", translation: "Borracha", phonetic: "/ɪˈreɪzər/", category: "Education", example: "Rubber eraser.", examplePt: "Borracha." },
    { word: "Ruler", translation: "Régua", phonetic: "/ˈruːlər/", category: "Education", example: "Plastic ruler.", examplePt: "Régua de plástico." },
    { word: "Scissors", translation: "Tesoura", phonetic: "/ˈsɪzərz/", category: "Education", example: "Safety scissors.", examplePt: "Tesoura de segurança." },
    { word: "Backpack", translation: "Mochila", phonetic: "/ˈbækpæk/", category: "Education", example: "School backpack.", examplePt: "Mochila escolar." },
    { word: "Blackboard", translation: "Quadro negro", phonetic: "/ˈblækbɔːrd/", category: "Education", example: "Write on the blackboard.", examplePt: "Escreva no quadro." },
    { word: "Whiteboard", translation: "Quadro branco", phonetic: "/ˈwaɪtbɔːrd/", category: "Education", example: "Clean whiteboard.", examplePt: "Quadro branco limpo." },

    // SPORTS & HOBBIES (30 words)
    { word: "Soccer", translation: "Futebol", phonetic: "/ˈsɑːkər/", category: "Sports", example: "Play soccer.", examplePt: "Jogar futebol." },
    { word: "Football", translation: "Futebol americano", phonetic: "/ˈfʊtbɔːl/", category: "Sports", example: "Football game.", examplePt: "Jogo de futebol americano." },
    { word: "Basketball", translation: "Basquete", phonetic: "/ˈbæskɪtbɔːl/", category: "Sports", example: "Basketball court.", examplePt: "Quadra de basquete." },
    { word: "Tennis", translation: "Tênis", phonetic: "/ˈtenɪs/", category: "Sports", example: "Tennis match.", examplePt: "Partida de tênis." },
    { word: "Swimming", translation: "Natação", phonetic: "/ˈswɪmɪŋ/", category: "Sports", example: "Swimming pool.", examplePt: "Piscina." },
    { word: "Running", translation: "Corrida", phonetic: "/ˈrʌnɪŋ/", category: "Sports", example: "Morning running.", examplePt: "Corrida matinal." },
    { word: "Volleyball", translation: "Vôlei", phonetic: "/ˈvɑːlibɔːl/", category: "Sports", example: "Beach volleyball.", examplePt: "Vôlei de praia." },
    { word: "Golf", translation: "Golfe", phonetic: "/ɡɑːlf/", category: "Sports", example: "Golf course.", examplePt: "Campo de golfe." },
    { word: "Boxing", translation: "Boxe", phonetic: "/ˈbɑːksɪŋ/", category: "Sports", example: "Boxing match.", examplePt: "Luta de boxe." },
    { word: "Yoga", translation: "Yoga", phonetic: "/ˈjoʊɡə/", category: "Sports", example: "Yoga class.", examplePt: "Aula de yoga." },
    { word: "Gym", translation: "Academia", phonetic: "/dʒɪm/", category: "Sports", example: "Go to the gym.", examplePt: "Ir à academia." },
    { word: "Exercise", translation: "Exercício", phonetic: "/ˈeksərsaɪz/", category: "Sports", example: "Daily exercise.", examplePt: "Exercício diário." },
    { word: "Hiking", translation: "Caminhada", phonetic: "/ˈhaɪkɪŋ/", category: "Hobbies", example: "Mountain hiking.", examplePt: "Caminhada na montanha." },
    { word: "Camping", translation: "Acampamento", phonetic: "/ˈkæmpɪŋ/", category: "Hobbies", example: "Go camping.", examplePt: "Ir acampar." },
    { word: "Fishing", translation: "Pesca", phonetic: "/ˈfɪʃɪŋ/", category: "Hobbies", example: "Fishing trip.", examplePt: "Pescaria." },
    { word: "Cooking", translation: "Cozinha/Culinária", phonetic: "/ˈkʊkɪŋ/", category: "Hobbies", example: "Love cooking.", examplePt: "Amo cozinhar." },
    { word: "Reading", translation: "Leitura", phonetic: "/ˈriːdɪŋ/", category: "Hobbies", example: "Reading books.", examplePt: "Ler livros." },
    { word: "Writing", translation: "Escrita", phonetic: "/ˈraɪtɪŋ/", category: "Hobbies", example: "Creative writing.", examplePt: "Escrita criativa." },
    { word: "Drawing", translation: "Desenho", phonetic: "/ˈdrɔːɪŋ/", category: "Hobbies", example: "Drawing class.", examplePt: "Aula de desenho." },
    { word: "Painting", translation: "Pintura", phonetic: "/ˈpeɪntɪŋ/", category: "Hobbies", example: "Oil painting.", examplePt: "Pintura a óleo." },
    { word: "Photography", translation: "Fotografia", phonetic: "/fəˈtɑːɡrəfi/", category: "Hobbies", example: "Digital photography.", examplePt: "Fotografia digital." },
    { word: "Gardening", translation: "Jardinagem", phonetic: "/ˈɡɑːrdnɪŋ/", category: "Hobbies", example: "Enjoy gardening.", examplePt: "Gosto de jardinagem." },
    { word: "Shopping", translation: "Compras", phonetic: "/ˈʃɑːpɪŋ/", category: "Hobbies", example: "Go shopping.", examplePt: "Fazer compras." },
    { word: "Traveling", translation: "Viajar", phonetic: "/ˈtrævəlɪŋ/", category: "Hobbies", example: "Love traveling.", examplePt: "Amo viajar." },
    { word: "Gaming", translation: "Jogar videogame", phonetic: "/ˈɡeɪmɪŋ/", category: "Hobbies", example: "Online gaming.", examplePt: "Jogar online." }
];
