// ===== EXPANDED VOCABULARY - PART 1: NOUNS =====
const nounsVocabulary = [
    // HOUSE & HOME (50 words)
    { word: "Apartment", translation: "Apartamento", phonetic: "/əˈpɑːrtmənt/", category: "House", example: "I live in an apartment.", examplePt: "Eu moro em um apartamento." },
    { word: "Building", translation: "Prédio", phonetic: "/ˈbɪldɪŋ/", category: "House", example: "Tall building.", examplePt: "Prédio alto." },
    { word: "Floor", translation: "Andar/Chão", phonetic: "/flɔːr/", category: "House", example: "First floor.", examplePt: "Primeiro andar." },
    { word: "Ceiling", translation: "Teto", phonetic: "/ˈsiːlɪŋ/", category: "House", example: "High ceiling.", examplePt: "Teto alto." },
    { word: "Wall", translation: "Parede", phonetic: "/wɔːl/", category: "House", example: "White wall.", examplePt: "Parede branca." },
    { word: "Door", translation: "Porta", phonetic: "/dɔːr/", category: "House", example: "Open the door.", examplePt: "Abra a porta." },
    { word: "Window", translation: "Janela", phonetic: "/ˈwɪndoʊ/", category: "House", example: "Big window.", examplePt: "Janela grande." },
    { word: "Roof", translation: "Telhado", phonetic: "/ruːf/", category: "House", example: "Red roof.", examplePt: "Telhado vermelho." },
    { word: "Garage", translation: "Garagem", phonetic: "/ɡəˈrɑːʒ/", category: "House", example: "Two-car garage.", examplePt: "Garagem para dois carros." },
    { word: "Garden", translation: "Jardim", phonetic: "/ˈɡɑːrdn/", category: "House", example: "Beautiful garden.", examplePt: "Jardim bonito." },
    { word: "Yard", translation: "Quintal", phonetic: "/jɑːrd/", category: "House", example: "Backyard.", examplePt: "Quintal dos fundos." },
    { word: "Stairs", translation: "Escadas", phonetic: "/sterz/", category: "House", example: "Take the stairs.", examplePt: "Pegue as escadas." },
    { word: "Elevator", translation: "Elevador", phonetic: "/ˈelɪveɪtər/", category: "House", example: "Use the elevator.", examplePt: "Use o elevador." },
    { word: "Balcony", translation: "Varanda", phonetic: "/ˈbælkəni/", category: "House", example: "Nice balcony.", examplePt: "Varanda bonita." },
    { word: "Basement", translation: "Porão", phonetic: "/ˈbeɪsmənt/", category: "House", example: "Dark basement.", examplePt: "Porão escuro." },
    { word: "Attic", translation: "Sótão", phonetic: "/ˈætɪk/", category: "House", example: "Old attic.", examplePt: "Sótão antigo." },
    { word: "Hallway", translation: "Corredor", phonetic: "/ˈhɔːlweɪ/", category: "House", example: "Long hallway.", examplePt: "Corredor longo." },
    { word: "Fence", translation: "Cerca", phonetic: "/fens/", category: "House", example: "Wooden fence.", examplePt: "Cerca de madeira." },
    { word: "Gate", translation: "Portão", phonetic: "/ɡeɪt/", category: "House", example: "Iron gate.", examplePt: "Portão de ferro." },
    { word: "Chimney", translation: "Chaminé", phonetic: "/ˈtʃɪmni/", category: "House", example: "Brick chimney.", examplePt: "Chaminé de tijolos." },

    // FURNITURE (40 words)
    { word: "Table", translation: "Mesa", phonetic: "/ˈteɪbl/", category: "Furniture", example: "Dining table.", examplePt: "Mesa de jantar." },
    { word: "Chair", translation: "Cadeira", phonetic: "/tʃer/", category: "Furniture", example: "Comfortable chair.", examplePt: "Cadeira confortável." },
    { word: "Sofa", translation: "Sofá", phonetic: "/ˈsoʊfə/", category: "Furniture", example: "Leather sofa.", examplePt: "Sofá de couro." },
    { word: "Couch", translation: "Sofá", phonetic: "/kaʊtʃ/", category: "Furniture", example: "Big couch.", examplePt: "Sofá grande." },
    { word: "Bed", translation: "Cama", phonetic: "/bed/", category: "Furniture", example: "King size bed.", examplePt: "Cama king size." },
    { word: "Desk", translation: "Escrivaninha", phonetic: "/desk/", category: "Furniture", example: "Office desk.", examplePt: "Escrivaninha de escritório." },
    { word: "Drawer", translation: "Gaveta", phonetic: "/drɔːr/", category: "Furniture", example: "Top drawer.", examplePt: "Gaveta de cima." },
    { word: "Closet", translation: "Armário", phonetic: "/ˈklɑːzɪt/", category: "Furniture", example: "Walk-in closet.", examplePt: "Closet." },
    { word: "Wardrobe", translation: "Guarda-roupa", phonetic: "/ˈwɔːrdroʊb/", category: "Furniture", example: "Wooden wardrobe.", examplePt: "Guarda-roupa de madeira." },
    { word: "Shelf", translation: "Prateleira", phonetic: "/ʃelf/", category: "Furniture", example: "Book shelf.", examplePt: "Prateleira de livros." },
    { word: "Cabinet", translation: "Armário/Gabinete", phonetic: "/ˈkæbɪnət/", category: "Furniture", example: "Kitchen cabinet.", examplePt: "Armário de cozinha." },
    { word: "Mirror", translation: "Espelho", phonetic: "/ˈmɪrər/", category: "Furniture", example: "Large mirror.", examplePt: "Espelho grande." },
    { word: "Lamp", translation: "Luminária/Lâmpada", phonetic: "/læmp/", category: "Furniture", example: "Table lamp.", examplePt: "Luminária de mesa." },
    { word: "Carpet", translation: "Tapete", phonetic: "/ˈkɑːrpɪt/", category: "Furniture", example: "Persian carpet.", examplePt: "Tapete persa." },
    { word: "Rug", translation: "Tapete pequeno", phonetic: "/rʌɡ/", category: "Furniture", example: "Area rug.", examplePt: "Tapete de área." },
    { word: "Curtain", translation: "Cortina", phonetic: "/ˈkɜːrtn/", category: "Furniture", example: "White curtains.", examplePt: "Cortinas brancas." },
    { word: "Pillow", translation: "Travesseiro", phonetic: "/ˈpɪloʊ/", category: "Furniture", example: "Soft pillow.", examplePt: "Travesseiro macio." },
    { word: "Blanket", translation: "Cobertor", phonetic: "/ˈblæŋkɪt/", category: "Furniture", example: "Warm blanket.", examplePt: "Cobertor quente." },
    { word: "Sheet", translation: "Lençol", phonetic: "/ʃiːt/", category: "Furniture", example: "Clean sheets.", examplePt: "Lençóis limpos." },
    { word: "Mattress", translation: "Colchão", phonetic: "/ˈmætrəs/", category: "Furniture", example: "New mattress.", examplePt: "Colchão novo." },

    // KITCHEN ITEMS (40 words)
    { word: "Stove", translation: "Fogão", phonetic: "/stoʊv/", category: "Kitchen", example: "Gas stove.", examplePt: "Fogão a gás." },
    { word: "Oven", translation: "Forno", phonetic: "/ˈʌvn/", category: "Kitchen", example: "Hot oven.", examplePt: "Forno quente." },
    { word: "Microwave", translation: "Micro-ondas", phonetic: "/ˈmaɪkroʊweɪv/", category: "Kitchen", example: "Microwave safe.", examplePt: "Seguro para micro-ondas." },
    { word: "Refrigerator", translation: "Geladeira", phonetic: "/rɪˈfrɪdʒəreɪtər/", category: "Kitchen", example: "Full refrigerator.", examplePt: "Geladeira cheia." },
    { word: "Fridge", translation: "Geladeira", phonetic: "/frɪdʒ/", category: "Kitchen", example: "Check the fridge.", examplePt: "Verifique a geladeira." },
    { word: "Freezer", translation: "Freezer", phonetic: "/ˈfriːzər/", category: "Kitchen", example: "Deep freezer.", examplePt: "Freezer profundo." },
    { word: "Sink", translation: "Pia", phonetic: "/sɪŋk/", category: "Kitchen", example: "Kitchen sink.", examplePt: "Pia da cozinha." },
    { word: "Faucet", translation: "Torneira", phonetic: "/ˈfɔːsɪt/", category: "Kitchen", example: "Leaky faucet.", examplePt: "Torneira vazando." },
    { word: "Knife", translation: "Faca", phonetic: "/naɪf/", category: "Kitchen", example: "Sharp knife.", examplePt: "Faca afiada." },
    { word: "Fork", translation: "Garfo", phonetic: "/fɔːrk/", category: "Kitchen", example: "Silver fork.", examplePt: "Garfo de prata." },
    { word: "Spoon", translation: "Colher", phonetic: "/spuːn/", category: "Kitchen", example: "Soup spoon.", examplePt: "Colher de sopa." },
    { word: "Plate", translation: "Prato", phonetic: "/pleɪt/", category: "Kitchen", example: "Dinner plate.", examplePt: "Prato de jantar." },
    { word: "Bowl", translation: "Tigela", phonetic: "/boʊl/", category: "Kitchen", example: "Cereal bowl.", examplePt: "Tigela de cereal." },
    { word: "Cup", translation: "Xícara", phonetic: "/kʌp/", category: "Kitchen", example: "Coffee cup.", examplePt: "Xícara de café." },
    { word: "Glass", translation: "Copo", phonetic: "/ɡlæs/", category: "Kitchen", example: "Water glass.", examplePt: "Copo de água." },
    { word: "Pot", translation: "Panela", phonetic: "/pɑːt/", category: "Kitchen", example: "Cooking pot.", examplePt: "Panela de cozinhar." },
    { word: "Pan", translation: "Frigideira", phonetic: "/pæn/", category: "Kitchen", example: "Frying pan.", examplePt: "Frigideira." },
    { word: "Blender", translation: "Liquidificador", phonetic: "/ˈblendər/", category: "Kitchen", example: "Kitchen blender.", examplePt: "Liquidificador." },
    { word: "Toaster", translation: "Torradeira", phonetic: "/ˈtoʊstər/", category: "Kitchen", example: "Bread toaster.", examplePt: "Torradeira de pão." },
    { word: "Kettle", translation: "Chaleira", phonetic: "/ˈketl/", category: "Kitchen", example: "Electric kettle.", examplePt: "Chaleira elétrica." },

    // BATHROOM (25 words)
    { word: "Toilet", translation: "Vaso sanitário", phonetic: "/ˈtɔɪlət/", category: "Bathroom", example: "Flush the toilet.", examplePt: "Dê descarga." },
    { word: "Shower", translation: "Chuveiro", phonetic: "/ˈʃaʊər/", category: "Bathroom", example: "Hot shower.", examplePt: "Chuveiro quente." },
    { word: "Bathtub", translation: "Banheira", phonetic: "/ˈbæθtʌb/", category: "Bathroom", example: "Big bathtub.", examplePt: "Banheira grande." },
    { word: "Towel", translation: "Toalha", phonetic: "/ˈtaʊəl/", category: "Bathroom", example: "Clean towel.", examplePt: "Toalha limpa." },
    { word: "Soap", translation: "Sabonete", phonetic: "/soʊp/", category: "Bathroom", example: "Hand soap.", examplePt: "Sabonete de mão." },
    { word: "Shampoo", translation: "Shampoo", phonetic: "/ʃæmˈpuː/", category: "Bathroom", example: "Hair shampoo.", examplePt: "Shampoo de cabelo." },
    { word: "Toothbrush", translation: "Escova de dente", phonetic: "/ˈtuːθbrʌʃ/", category: "Bathroom", example: "Electric toothbrush.", examplePt: "Escova elétrica." },
    { word: "Toothpaste", translation: "Pasta de dente", phonetic: "/ˈtuːθpeɪst/", category: "Bathroom", example: "Mint toothpaste.", examplePt: "Pasta de dente de menta." },
    { word: "Razor", translation: "Barbeador", phonetic: "/ˈreɪzər/", category: "Bathroom", example: "Sharp razor.", examplePt: "Barbeador afiado." },
    { word: "Comb", translation: "Pente", phonetic: "/koʊm/", category: "Bathroom", example: "Hair comb.", examplePt: "Pente de cabelo." },
    { word: "Brush", translation: "Escova", phonetic: "/brʌʃ/", category: "Bathroom", example: "Hair brush.", examplePt: "Escova de cabelo." },

    // CLOTHES (50 words)
    { word: "Shirt", translation: "Camisa", phonetic: "/ʃɜːrt/", category: "Clothes", example: "White shirt.", examplePt: "Camisa branca." },
    { word: "T-shirt", translation: "Camiseta", phonetic: "/ˈtiːʃɜːrt/", category: "Clothes", example: "Cotton t-shirt.", examplePt: "Camiseta de algodão." },
    { word: "Pants", translation: "Calça", phonetic: "/pænts/", category: "Clothes", example: "Blue pants.", examplePt: "Calça azul." },
    { word: "Jeans", translation: "Jeans", phonetic: "/dʒiːnz/", category: "Clothes", example: "Denim jeans.", examplePt: "Jeans de denim." },
    { word: "Shorts", translation: "Shorts", phonetic: "/ʃɔːrts/", category: "Clothes", example: "Summer shorts.", examplePt: "Shorts de verão." },
    { word: "Dress", translation: "Vestido", phonetic: "/dres/", category: "Clothes", example: "Red dress.", examplePt: "Vestido vermelho." },
    { word: "Skirt", translation: "Saia", phonetic: "/skɜːrt/", category: "Clothes", example: "Short skirt.", examplePt: "Saia curta." },
    { word: "Jacket", translation: "Jaqueta", phonetic: "/ˈdʒækɪt/", category: "Clothes", example: "Leather jacket.", examplePt: "Jaqueta de couro." },
    { word: "Coat", translation: "Casaco", phonetic: "/koʊt/", category: "Clothes", example: "Winter coat.", examplePt: "Casaco de inverno." },
    { word: "Sweater", translation: "Suéter", phonetic: "/ˈswetər/", category: "Clothes", example: "Wool sweater.", examplePt: "Suéter de lã." },
    { word: "Hoodie", translation: "Moletom", phonetic: "/ˈhʊdi/", category: "Clothes", example: "Black hoodie.", examplePt: "Moletom preto." },
    { word: "Suit", translation: "Terno", phonetic: "/suːt/", category: "Clothes", example: "Business suit.", examplePt: "Terno de negócios." },
    { word: "Tie", translation: "Gravata", phonetic: "/taɪ/", category: "Clothes", example: "Silk tie.", examplePt: "Gravata de seda." },
    { word: "Belt", translation: "Cinto", phonetic: "/belt/", category: "Clothes", example: "Leather belt.", examplePt: "Cinto de couro." },
    { word: "Socks", translation: "Meias", phonetic: "/sɑːks/", category: "Clothes", example: "White socks.", examplePt: "Meias brancas." },
    { word: "Shoes", translation: "Sapatos", phonetic: "/ʃuːz/", category: "Clothes", example: "Running shoes.", examplePt: "Tênis de corrida." },
    { word: "Boots", translation: "Botas", phonetic: "/buːts/", category: "Clothes", example: "Leather boots.", examplePt: "Botas de couro." },
    { word: "Sneakers", translation: "Tênis", phonetic: "/ˈsniːkərz/", category: "Clothes", example: "Casual sneakers.", examplePt: "Tênis casual." },
    { word: "Sandals", translation: "Sandálias", phonetic: "/ˈsændlz/", category: "Clothes", example: "Beach sandals.", examplePt: "Sandálias de praia." },
    { word: "Hat", translation: "Chapéu", phonetic: "/hæt/", category: "Clothes", example: "Sun hat.", examplePt: "Chapéu de sol." },
    { word: "Cap", translation: "Boné", phonetic: "/kæp/", category: "Clothes", example: "Baseball cap.", examplePt: "Boné de baseball." },
    { word: "Gloves", translation: "Luvas", phonetic: "/ɡlʌvz/", category: "Clothes", example: "Winter gloves.", examplePt: "Luvas de inverno." },
    { word: "Scarf", translation: "Cachecol", phonetic: "/skɑːrf/", category: "Clothes", example: "Warm scarf.", examplePt: "Cachecol quente." },
    { word: "Underwear", translation: "Roupa íntima", phonetic: "/ˈʌndərwer/", category: "Clothes", example: "Cotton underwear.", examplePt: "Roupa íntima de algodão." },
    { word: "Pajamas", translation: "Pijama", phonetic: "/pəˈdʒæməz/", category: "Clothes", example: "Silk pajamas.", examplePt: "Pijama de seda." },
    { word: "Swimsuit", translation: "Maiô/Roupa de banho", phonetic: "/ˈswɪmsuːt/", category: "Clothes", example: "New swimsuit.", examplePt: "Maiô novo." },
    { word: "Uniform", translation: "Uniforme", phonetic: "/ˈjuːnɪfɔːrm/", category: "Clothes", example: "School uniform.", examplePt: "Uniforme escolar." },
    { word: "Pocket", translation: "Bolso", phonetic: "/ˈpɑːkɪt/", category: "Clothes", example: "Front pocket.", examplePt: "Bolso da frente." },
    { word: "Button", translation: "Botão", phonetic: "/ˈbʌtn/", category: "Clothes", example: "Shirt button.", examplePt: "Botão de camisa." },
    { word: "Zipper", translation: "Zíper", phonetic: "/ˈzɪpər/", category: "Clothes", example: "Broken zipper.", examplePt: "Zíper quebrado." },

    // VEHICLES (30 words)
    { word: "Car", translation: "Carro", phonetic: "/kɑːr/", category: "Vehicles", example: "New car.", examplePt: "Carro novo." },
    { word: "Bus", translation: "Ônibus", phonetic: "/bʌs/", category: "Vehicles", example: "City bus.", examplePt: "Ônibus urbano." },
    { word: "Train", translation: "Trem", phonetic: "/treɪn/", category: "Vehicles", example: "Fast train.", examplePt: "Trem rápido." },
    { word: "Plane", translation: "Avião", phonetic: "/pleɪn/", category: "Vehicles", example: "Commercial plane.", examplePt: "Avião comercial." },
    { word: "Airplane", translation: "Avião", phonetic: "/ˈerpleɪn/", category: "Vehicles", example: "Private airplane.", examplePt: "Avião particular." },
    { word: "Helicopter", translation: "Helicóptero", phonetic: "/ˈhelɪkɑːptər/", category: "Vehicles", example: "Police helicopter.", examplePt: "Helicóptero da polícia." },
    { word: "Boat", translation: "Barco", phonetic: "/boʊt/", category: "Vehicles", example: "Fishing boat.", examplePt: "Barco de pesca." },
    { word: "Ship", translation: "Navio", phonetic: "/ʃɪp/", category: "Vehicles", example: "Cruise ship.", examplePt: "Navio de cruzeiro." },
    { word: "Bicycle", translation: "Bicicleta", phonetic: "/ˈbaɪsɪkl/", category: "Vehicles", example: "Mountain bicycle.", examplePt: "Bicicleta de montanha." },
    { word: "Bike", translation: "Bicicleta/Moto", phonetic: "/baɪk/", category: "Vehicles", example: "Ride a bike.", examplePt: "Andar de bicicleta." },
    { word: "Motorcycle", translation: "Motocicleta", phonetic: "/ˈmoʊtərsaɪkl/", category: "Vehicles", example: "Harley motorcycle.", examplePt: "Moto Harley." },
    { word: "Truck", translation: "Caminhão", phonetic: "/trʌk/", category: "Vehicles", example: "Big truck.", examplePt: "Caminhão grande." },
    { word: "Van", translation: "Van", phonetic: "/væn/", category: "Vehicles", example: "Delivery van.", examplePt: "Van de entrega." },
    { word: "Taxi", translation: "Táxi", phonetic: "/ˈtæksi/", category: "Vehicles", example: "Yellow taxi.", examplePt: "Táxi amarelo." },
    { word: "Subway", translation: "Metrô", phonetic: "/ˈsʌbweɪ/", category: "Vehicles", example: "Take the subway.", examplePt: "Pegue o metrô." },
    { word: "Scooter", translation: "Patinete/Scooter", phonetic: "/ˈskuːtər/", category: "Vehicles", example: "Electric scooter.", examplePt: "Patinete elétrico." },
    { word: "Ambulance", translation: "Ambulância", phonetic: "/ˈæmbjələns/", category: "Vehicles", example: "Call an ambulance.", examplePt: "Chame uma ambulância." },
    { word: "Tire", translation: "Pneu", phonetic: "/ˈtaɪər/", category: "Vehicles", example: "Flat tire.", examplePt: "Pneu furado." },
    { word: "Wheel", translation: "Roda", phonetic: "/wiːl/", category: "Vehicles", example: "Steering wheel.", examplePt: "Volante." },
    { word: "Engine", translation: "Motor", phonetic: "/ˈendʒɪn/", category: "Vehicles", example: "Car engine.", examplePt: "Motor do carro." },

    // ANIMALS (50 words)
    { word: "Dog", translation: "Cachorro", phonetic: "/dɔːɡ/", category: "Animals", example: "Friendly dog.", examplePt: "Cachorro amigável." },
    { word: "Cat", translation: "Gato", phonetic: "/kæt/", category: "Animals", example: "Black cat.", examplePt: "Gato preto." },
    { word: "Bird", translation: "Pássaro", phonetic: "/bɜːrd/", category: "Animals", example: "Wild bird.", examplePt: "Pássaro selvagem." },
    { word: "Horse", translation: "Cavalo", phonetic: "/hɔːrs/", category: "Animals", example: "White horse.", examplePt: "Cavalo branco." },
    { word: "Cow", translation: "Vaca", phonetic: "/kaʊ/", category: "Animals", example: "Dairy cow.", examplePt: "Vaca leiteira." },
    { word: "Pig", translation: "Porco", phonetic: "/pɪɡ/", category: "Animals", example: "Farm pig.", examplePt: "Porco de fazenda." },
    { word: "Sheep", translation: "Ovelha", phonetic: "/ʃiːp/", category: "Animals", example: "Wool sheep.", examplePt: "Ovelha de lã." },
    { word: "Chicken", translation: "Galinha", phonetic: "/ˈtʃɪkɪn/", category: "Animals", example: "Farm chicken.", examplePt: "Galinha de fazenda." },
    { word: "Duck", translation: "Pato", phonetic: "/dʌk/", category: "Animals", example: "Wild duck.", examplePt: "Pato selvagem." },
    { word: "Rabbit", translation: "Coelho", phonetic: "/ˈræbɪt/", category: "Animals", example: "White rabbit.", examplePt: "Coelho branco." },
    { word: "Mouse", translation: "Rato", phonetic: "/maʊs/", category: "Animals", example: "Small mouse.", examplePt: "Rato pequeno." },
    { word: "Lion", translation: "Leão", phonetic: "/ˈlaɪən/", category: "Animals", example: "African lion.", examplePt: "Leão africano." },
    { word: "Tiger", translation: "Tigre", phonetic: "/ˈtaɪɡər/", category: "Animals", example: "Bengal tiger.", examplePt: "Tigre de Bengala." },
    { word: "Bear", translation: "Urso", phonetic: "/ber/", category: "Animals", example: "Brown bear.", examplePt: "Urso marrom." },
    { word: "Elephant", translation: "Elefante", phonetic: "/ˈelɪfənt/", category: "Animals", example: "Big elephant.", examplePt: "Elefante grande." },
    { word: "Monkey", translation: "Macaco", phonetic: "/ˈmʌŋki/", category: "Animals", example: "Smart monkey.", examplePt: "Macaco inteligente." },
    { word: "Snake", translation: "Cobra", phonetic: "/sneɪk/", category: "Animals", example: "Dangerous snake.", examplePt: "Cobra perigosa." },
    { word: "Frog", translation: "Sapo", phonetic: "/frɔːɡ/", category: "Animals", example: "Green frog.", examplePt: "Sapo verde." },
    { word: "Turtle", translation: "Tartaruga", phonetic: "/ˈtɜːrtl/", category: "Animals", example: "Sea turtle.", examplePt: "Tartaruga marinha." },
    { word: "Shark", translation: "Tubarão", phonetic: "/ʃɑːrk/", category: "Animals", example: "Great white shark.", examplePt: "Tubarão branco." },
    { word: "Whale", translation: "Baleia", phonetic: "/weɪl/", category: "Animals", example: "Blue whale.", examplePt: "Baleia azul." },
    { word: "Dolphin", translation: "Golfinho", phonetic: "/ˈdɑːlfɪn/", category: "Animals", example: "Friendly dolphin.", examplePt: "Golfinho amigável." },
    { word: "Wolf", translation: "Lobo", phonetic: "/wʊlf/", category: "Animals", example: "Gray wolf.", examplePt: "Lobo cinza." },
    { word: "Fox", translation: "Raposa", phonetic: "/fɑːks/", category: "Animals", example: "Red fox.", examplePt: "Raposa vermelha." },
    { word: "Deer", translation: "Veado", phonetic: "/dɪr/", category: "Animals", example: "Wild deer.", examplePt: "Veado selvagem." },
    { word: "Butterfly", translation: "Borboleta", phonetic: "/ˈbʌtərflaɪ/", category: "Animals", example: "Beautiful butterfly.", examplePt: "Borboleta bonita." },
    { word: "Bee", translation: "Abelha", phonetic: "/biː/", category: "Animals", example: "Busy bee.", examplePt: "Abelha ocupada." },
    { word: "Ant", translation: "Formiga", phonetic: "/ænt/", category: "Animals", example: "Small ant.", examplePt: "Formiga pequena." },
    { word: "Spider", translation: "Aranha", phonetic: "/ˈspaɪdər/", category: "Animals", example: "Big spider.", examplePt: "Aranha grande." },
    { word: "Mosquito", translation: "Mosquito", phonetic: "/məˈskiːtoʊ/", category: "Animals", example: "Annoying mosquito.", examplePt: "Mosquito irritante." },

    // NATURE (40 words)
    { word: "Tree", translation: "Árvore", phonetic: "/triː/", category: "Nature", example: "Tall tree.", examplePt: "Árvore alta." },
    { word: "Flower", translation: "Flor", phonetic: "/ˈflaʊər/", category: "Nature", example: "Beautiful flower.", examplePt: "Flor bonita." },
    { word: "Grass", translation: "Grama", phonetic: "/ɡræs/", category: "Nature", example: "Green grass.", examplePt: "Grama verde." },
    { word: "Plant", translation: "Planta", phonetic: "/plænt/", category: "Nature", example: "Indoor plant.", examplePt: "Planta de interior." },
    { word: "Leaf", translation: "Folha", phonetic: "/liːf/", category: "Nature", example: "Green leaf.", examplePt: "Folha verde." },
    { word: "Branch", translation: "Galho", phonetic: "/bræntʃ/", category: "Nature", example: "Tree branch.", examplePt: "Galho de árvore." },
    { word: "Root", translation: "Raiz", phonetic: "/ruːt/", category: "Nature", example: "Deep root.", examplePt: "Raiz profunda." },
    { word: "Seed", translation: "Semente", phonetic: "/siːd/", category: "Nature", example: "Sunflower seed.", examplePt: "Semente de girassol." },
    { word: "Forest", translation: "Floresta", phonetic: "/ˈfɔːrɪst/", category: "Nature", example: "Dense forest.", examplePt: "Floresta densa." },
    { word: "Jungle", translation: "Selva", phonetic: "/ˈdʒʌŋɡl/", category: "Nature", example: "Amazon jungle.", examplePt: "Selva amazônica." },
    { word: "Mountain", translation: "Montanha", phonetic: "/ˈmaʊntən/", category: "Nature", example: "High mountain.", examplePt: "Montanha alta." },
    { word: "Hill", translation: "Colina", phonetic: "/hɪl/", category: "Nature", example: "Green hill.", examplePt: "Colina verde." },
    { word: "Valley", translation: "Vale", phonetic: "/ˈvæli/", category: "Nature", example: "Deep valley.", examplePt: "Vale profundo." },
    { word: "River", translation: "Rio", phonetic: "/ˈrɪvər/", category: "Nature", example: "Long river.", examplePt: "Rio longo." },
    { word: "Lake", translation: "Lago", phonetic: "/leɪk/", category: "Nature", example: "Beautiful lake.", examplePt: "Lago bonito." },
    { word: "Ocean", translation: "Oceano", phonetic: "/ˈoʊʃn/", category: "Nature", example: "Pacific ocean.", examplePt: "Oceano Pacífico." },
    { word: "Sea", translation: "Mar", phonetic: "/siː/", category: "Nature", example: "Deep sea.", examplePt: "Mar profundo." },
    { word: "Wave", translation: "Onda", phonetic: "/weɪv/", category: "Nature", example: "Big wave.", examplePt: "Onda grande." },
    { word: "Waterfall", translation: "Cachoeira", phonetic: "/ˈwɔːtərfɔːl/", category: "Nature", example: "Beautiful waterfall.", examplePt: "Cachoeira bonita." },
    { word: "Island", translation: "Ilha", phonetic: "/ˈaɪlənd/", category: "Nature", example: "Tropical island.", examplePt: "Ilha tropical." },
    { word: "Desert", translation: "Deserto", phonetic: "/ˈdezərt/", category: "Nature", example: "Hot desert.", examplePt: "Deserto quente." },
    { word: "Sand", translation: "Areia", phonetic: "/sænd/", category: "Nature", example: "White sand.", examplePt: "Areia branca." },
    { word: "Rock", translation: "Pedra", phonetic: "/rɑːk/", category: "Nature", example: "Big rock.", examplePt: "Pedra grande." },
    { word: "Stone", translation: "Pedra", phonetic: "/stoʊn/", category: "Nature", example: "Small stone.", examplePt: "Pedra pequena." },
    { word: "Cave", translation: "Caverna", phonetic: "/keɪv/", category: "Nature", example: "Dark cave.", examplePt: "Caverna escura." },

    // WEATHER (25 words)
    { word: "Weather", translation: "Clima/Tempo", phonetic: "/ˈweðər/", category: "Weather", example: "Nice weather.", examplePt: "Tempo bom." },
    { word: "Sun", translation: "Sol", phonetic: "/sʌn/", category: "Weather", example: "Bright sun.", examplePt: "Sol brilhante." },
    { word: "Moon", translation: "Lua", phonetic: "/muːn/", category: "Weather", example: "Full moon.", examplePt: "Lua cheia." },
    { word: "Star", translation: "Estrela", phonetic: "/stɑːr/", category: "Weather", example: "Shining star.", examplePt: "Estrela brilhante." },
    { word: "Cloud", translation: "Nuvem", phonetic: "/klaʊd/", category: "Weather", example: "White cloud.", examplePt: "Nuvem branca." },
    { word: "Rain", translation: "Chuva", phonetic: "/reɪn/", category: "Weather", example: "Heavy rain.", examplePt: "Chuva forte." },
    { word: "Snow", translation: "Neve", phonetic: "/snoʊ/", category: "Weather", example: "White snow.", examplePt: "Neve branca." },
    { word: "Wind", translation: "Vento", phonetic: "/wɪnd/", category: "Weather", example: "Strong wind.", examplePt: "Vento forte." },
    { word: "Storm", translation: "Tempestade", phonetic: "/stɔːrm/", category: "Weather", example: "Dangerous storm.", examplePt: "Tempestade perigosa." },
    { word: "Thunder", translation: "Trovão", phonetic: "/ˈθʌndər/", category: "Weather", example: "Loud thunder.", examplePt: "Trovão alto." },
    { word: "Lightning", translation: "Relâmpago", phonetic: "/ˈlaɪtnɪŋ/", category: "Weather", example: "Bright lightning.", examplePt: "Relâmpago brilhante." },
    { word: "Fog", translation: "Neblina", phonetic: "/fɔːɡ/", category: "Weather", example: "Dense fog.", examplePt: "Neblina densa." },
    { word: "Ice", translation: "Gelo", phonetic: "/aɪs/", category: "Weather", example: "Black ice.", examplePt: "Gelo negro." },
    { word: "Temperature", translation: "Temperatura", phonetic: "/ˈtemprətʃər/", category: "Weather", example: "High temperature.", examplePt: "Temperatura alta." },
    { word: "Humidity", translation: "Umidade", phonetic: "/hjuːˈmɪdəti/", category: "Weather", example: "High humidity.", examplePt: "Umidade alta." },
    { word: "Rainbow", translation: "Arco-íris", phonetic: "/ˈreɪnboʊ/", category: "Weather", example: "Beautiful rainbow.", examplePt: "Arco-íris bonito." }
];
